### ISSUE TITLE
[docs]: tag edits 

### ISSUE THREAD

**Issue by brianferry** [RedHat-UX/red-hat-design-system#1019]
Place to hold docs edits for `rh-tag`

**Comment by coreyvickery** [comment]
@brianferry Edits below, thanks for opening this issue.

### Overview page
- Under the `Sample element` h2, change the `Filled` and `Unfilled` text to h3
- `Repo status` table is missing

### Style page
- Under the `Anatomy` h3, under the container, the 1 - 3 text styling should be: Red Hat Text, 14px, 1.5/21 line height, #4D4D4D
- Change the `Theme` heading text to h2 (28px)
- Change the `Light theme` and `Dark theme` heading text to h3 (24px)
- Change the `Configuration`, `Space`, and `Interaction states` headings to h2 (28px)
- Under the `Space` h2, in the table, change the spacer images to code (Steven fixed this)

### Guidelines tab
- Change the `Tag vs. Badge` text to `Tag vs. badge` and change the size to h3
- Under the `Variations` h2, in the alert, only the word `Accessibility` should be linked
- Change the `White Tag` text to `White tag`
- Under the `White tag` h2, the image should not be in a container
- Change the `Writing Content` text to `Writing content`
