### ISSUE TITLE
[feat] Add Firefox ESR testing to the test matrix

### ISSUE THREAD

**Issue by zhawkins** [RedHat-UX/red-hat-design-system#1028]
### Description

>  if it's not too much trouble can you open an issue on pfe and rhds to add ff esr to the testing matrix? cheers
- Benny

😄 

### Suggested solution

Add Firefox ESR testing to the test matrix

**Comment by bennypowers** [comment]
https://github.com/microsoft/playwright/issues/13080#issuecomment-1079552993
https://github.com/microsoft/playwright/issues/10284
https://github.com/microsoft/playwright/issues/8613#issuecomment-910202632

We'll need to convince microsoft to support firefox esr in playwright

**Comment by bennypowers** [comment]
https://github.com/microsoft/playwright/issues/27542
