### ISSUE TITLE
[docs] remove traces of subnav links

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1029]
Breaking this comment out to its own issue:

From @coreyvickery in https://github.com/RedHat-UX/red-hat-design-system/pull/1011

> Remove all traces of Subnav links, we are delaying that page because it is used so rarely

**Comment by bennypowers** [comment]
I'd like to keep these links around, being as that we've already shipped the element and don't intend to remove it. We can loop back and update the docs down the line.
