### ISSUE TITLE
[docs]: global changes

### ISSUE THREAD

**Issue by eyevana** [RedHat-UX/red-hat-design-system#1037]
@coreyvickery  Edits:

### Global
- Images are 0.5x, but I assume there is a PR out there to fix this
- Do a find and replace: Change `Variants` to `Variations` and `variants` to `variations`

**Comment by bennypowers** [comment]
Let's keep `variant`, as that's the nomenclature we adopted for HTML attributes, and it would be confusing to change that at this late stage

**Comment by coreyvickery** [comment]
@eyevana Some of the new docs pages include the words `Variations` and `variations`. Just curious, is it a big lift to do a find and replace and change all of them?

**Comment by bennypowers** [comment]
@eyevana what's left to do here?

**Comment by eyevana** [comment]
I'm pretty sure it's just making those changes that @coreyvickery requested in his last comment (switching from variations to variants). The issue with the images was fixed already. I'll knock this one out today.
