### ISSUE TITLE
[docs] Audio player docs need review/cleanup

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#1072]
Please review sections and ensure docs are complete.

https://ux.redhat.com/elements/audio-player/

Current tabs: Overview, Style, Guidelines

Tag @coreyvickery for final design review.

**Comment by coreyvickery** [comment]
XD: https://xd.adobe.com/view/7b3c25f5-88fc-4864-a25d-b6fc9e6e7958-2e6f/
Content doc: https://docs.google.com/document/d/1TcDrLGN5PbYem54SUz62bMNJt-vYhBQJI7jOsWItN1o/edit
Images: https://www.dropbox.com/sh/0vaephegntmd0sk/AAByuwdE1Qx8mLRzp0RKZQq4a?dl=0

**Comment by coreyvickery** [comment]
@nikkimk Can you please make a new issue for this tiny change?

### Guidelines page
- Change all blue alert states from `info` to `warning`
