### ISSUE TITLE
[bug] padding issues on docs pages due to example css conflicts

### ISSUE THREAD

**Issue by diwanshi** [RedHat-UX/red-hat-design-system#1080]
### Describe the bug

@coreyvickery pointed out a few issues (mentioned below) with the paddings on [docs(cta) PR](https://github.com/RedHat-UX/red-hat-design-system/pull/1045) and it looks like these issues are related to example css for docs.

- Ensure there is 5.0rem (80px) of padding in between content and the Related elements or patterns and Feedback sections
- Ensure the padding in between image containers is 2.0rem (32px) (Example: On the Style page under the Light and dark themes h3)
- Ensure the padding in between an image container and a table is 2.0rem (32px) (Example: On the Style page under the Light and dark themes h3)
- Ensure the padding in between an h2 and h3 is 2.0rem (32px) (Example: On the Guidelines page under the Writing content h2)

### Which Component?

rh-cta

### Steps to reproduce

- Go to this url https://deploy-preview-1045--red-hat-design-system.netlify.app/elements/call-to-action/
- Observe padding issues between
   - images and tables
   - h2 & h3
   - content and the Related elements or patterns and Feedback sections
   - image containers

### Expected behaviour

- Ensure there is 5.0rem (80px) of padding in between content and the Related elements or patterns and Feedback sections - Ensure the padding in between image containers is 2.0rem (32px) (Example: On the Style page under the Light and dark themes h3)
- Ensure the padding in between an image container and a table is 2.0rem (32px) (Example: On the Style page under the Light and dark themes h3)
- Ensure the padding in between an h2 and h3 is 2.0rem (32px) (Example: On the Guidelines page under the Writing content h2)

### Operating System (OS)

macOS

### Browser

Chrome, Safari, Safari iOS, Microsoft Edge, Firefox

**Comment by bennypowers** [comment]
#1066 fixes the margins between adjacent example image containers
