### ISSUE TITLE
[bug] rh-audio-player overlap with title

### ISSUE THREAD

**Issue by dcaryll** [RedHat-UX/red-hat-design-system#1087]
### Describe the bug

When clicking the more menu, the tooltip title overlaps the menu itself. 

### Which Component?

rh-audio-player

### Steps to reproduce

1. Use audio player
2. Hit three dot menu
3. See overlap

### Expected behaviour

No overlap

### Screenshots

![IMG_2219](https://github.com/RedHat-UX/red-hat-design-system/assets/1249747/1bfbbfe1-8b53-4d61-955e-c24d933cbdfc)

### Operating System (OS)

iOS

### Browser

Chrome

**Comment by bennypowers** [comment]
This might be related to https://github.com/RedHat-UX/red-hat-design-system/issues/506
