### ISSUE TITLE
[docs]: some SVGs double scaled in patterns folder

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1119]
Some SVG files in the patterns folder are double scaled from what their rendered form should be.  ~~When used in an example shortcode this then makes the image larger then it should be.~~. This is more likely a function of export settings.  

Need to rescale these images to the appropriate rendered size. 

We can replace these by PNGs if necessary, @coreyvickery has mentioned issues with exporting from SVGs from XD.

Images scaled up 2x at render: 

- [x] https://ux.redhat.com/patterns/disclosure/#mobile
- [x] https://ux.redhat.com/patterns/sticky-card/#style
- [x] https://ux.redhat.com/patterns/sticky-card/#content

**Comment by coreyvickery** [comment]
@zeroedin Image locations below.

### disclosure-responsive-3.png
https://www.dropbox.com/scl/fi/vcvf0kj08lyrj9mwfwq4l/disclosure-responsive-3.png?rlkey=wkepv7hvmyufovad4fg754c3h&dl=0

### sticky-card-style.png
https://www.dropbox.com/scl/fi/zh1tl93qfiatsncgflmqf/sticky-card-style.png?rlkey=f984ds6zadsrax7xyezx51sir&dl=0

### sticky-card-content.png
https://www.dropbox.com/scl/fi/79nffomaydey30b1vbf2x/sticky-card-content.png?rlkey=4zuj3a68fhmaeurwyg5wfckf9&dl=0

**Comment by markcaron** [comment]
@zeroedin re-assigning to you.

**Comment by brianferry** [comment]
This was fixed with #1221 , closing
