### ISSUE TITLE
[bug] rh-avatar includes base 64 png which is bloating file size

### ISSUE THREAD

**Issue by zhawkins** [RedHat-UX/red-hat-design-system#1153]
### Describe the bug

When bundling rh-audio-player, I noticed that there were base 64'd pngs in the bundle. With @nikkimk 's help we tracked it down to rh-avatar.

https://github.com/RedHat-UX/red-hat-design-system/blob/main/elements/rh-avatar/rh-avatar.ts#L13

Can we either break those out into separate svg's or external png files? That should reduce the JS file dramatically.

With the base 64'd png:

```
│ rh-audio-player-entry.js               │ 132.46 kB │
```

Without:

```
│ rh-audio-player-entry.js               │ 77.45 kB  │
```

### Which Component?

rh-avatar

### Steps to reproduce

1. Look at https://github.com/RedHat-UX/red-hat-design-system/blob/main/elements/rh-avatar/rh-avatar.ts#L13

### Expected behaviour

Base 64 images aren't included in JavaScript files

### Screenshots

![Screen Shot 2023-07-19 at 11 28 26 AM](https://github.com/RedHat-UX/red-hat-design-system/assets/2671663/a416268b-6080-42fc-b924-42eb51062daa)

### Operating System (OS)

macOS

**Comment by coreyvickery** [comment]
@zhawkins @nikkimk SVGs attached.

![avatar-light-theme](https://github.com/RedHat-UX/red-hat-design-system/assets/45767595/2ed26e71-4f22-4adc-988c-aa02e43fd027)

![avatar-dark-theme](https://github.com/RedHat-UX/red-hat-design-system/assets/45767595/143a55fa-5e9b-490f-af13-6b705f3f9dc5)
