### ISSUE TITLE
[bug] Safari 16.3 support dropped in RHDS/Elements v1.1.0

### ISSUE THREAD

**Issue by zhawkins** [RedHat-UX/red-hat-design-system#1157]
### Describe the bug

Hi all,

After publishing [v1.1.0](https://github.com/RedHat-UX/red-hat-design-system/releases/tag/v1.1.0) to www.redhat.com, folks started reporting Secondary Nav was broken on product pages for mobile devices. 

- https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux
- https://www.redhat.com/en/technologies/cloud-computing/openshift
- https://www.redhat.com/en/technologies/management/ansible

The secondary nav broke in a way that obscured page content.

We narrowed the breaking change down to this [merge request](https://github.com/patternfly/patternfly-elements/commit/f4a7ae7d74113a79edc7cf5a6a6acd8e1d7f8e00#diff-6d9dfe806b0aeffa01011c28e580110501b307dc617ec8f214dc1c6986dbcdf4) which switches tsconfig settings from target `es2020` to `es2022`.  This changed how `Static initialization blocks` were transpiled which breaks Safari 16.3 support. Since Safari 16.3 was released Jan of this year and wasn't updated until March, I think it qualifies as a "recent version" per the [Red Hat browser support policy](https://www.redhat.com/en/about/browser-support).

I went back to look at the release notes to see if it mentioned anything about the es2022 change but didn't find anything 😢

We've temporarily fixed this for www.redhat.com with overrides pointing to the previous version of pfe-core.

```
    "overrides": {
        "@patternfly/elements": "2.2.2",
        "@patternfly/pfe-core": "2.3.1"
    },
```

I'd recommend moving back to es2020 _for now_, and look at reintroducing it in 6 months or so.

### Which Component?

all

### Steps to reproduce

Use Safari 16.3 and visit a page that loads the most recent version of RHDS/elements.

See JS errors out on unexpected token.

### Expected behaviour

it loads, yo.

### Operating System (OS)

iOS

### Browser

Safari, Safari iOS

### More browser information

- Safari 16.3 or older on mobile or desktop browsers.

**Comment by zeroedin** [comment]
Just a follow up there was an update to the @patternfly/pfe-tools dependency that should correct this: https://github.com/patternfly/patternfly-elements/blob/main/tools/pfe-tools/CHANGELOG.md#patch-changes

@zhawkins let me know if you can verify?

**Comment by zeroedin** [comment]
@zhawkins does this fix upstream fix the problem for you? https://github.com/patternfly/patternfly-elements/pull/2571. Can we close this issue?

**Comment by zeroedin** [comment]
Closed as fixed in [https://github.com/patternfly/patternfly-elements/pull/2571](https://github.com/patternfly/patternfly-elements/pull/2571)
