### ISSUE TITLE
[docs] Design system kit getting started grid not uniform

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#1159]
### Describe the bug

The grid under the "Getting Started" section is not of uniform size.

### Steps to reproduce

1. Go to https://ux.redhat.com/get-started/design-system-kit/
2. See that the grid below the "Getting Started" section is not uniform

### Expected behaviour

Each section should be of uniform size

### Screenshots

![Screenshot 2023-07-24 at 4 39 04 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/3428964/ce5ec6d6-848b-486d-a4d6-d3128272783e)

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by bennypowers** [comment]
@coreyvickery should these be rh-cards?
