### ISSUE TITLE
[docs]: add missing image on badge docs

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#1170]
see commit https://github.com/RedHat-UX/red-hat-design-system/commit/c30f69782d9e91131d41fc3f4882329bc7b6caee

**Comment by coreyvickery** [comment]
Image location:

https://www.dropbox.com/scl/fi/f18nos1hmrqhhg8i8qvqg/badge-variants.png?rlkey=am85tt2r9y2jee98lzxth9kxx&dl=0

**Comment by coreyvickery** [comment]
@brianferry Is this something you can fix?
