### ISSUE TITLE
[docs] Create CDN section on Developers Getting Started

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1177]
We'll need a CDN page with information on how to implement RHDS using the CDN as well as information about getting your site/domain whitelisted.

- [ ] Write content
- [ ] Design page
- [ ] Build page

Related: #1450 and #1484

**Comment by markcaron** [comment]
Good first issue. If you're picking this up, see me with questions.

**Comment by bennypowers** [comment]
#1690 might be enough to close this. PTAL @markcaron

**Comment by coreyvickery** [comment]
@markcaron Is [this section](https://ux.redhat.com/get-started/developers/installation/#red-hat-cdn) enough to close this or is more content required?

**Comment by bennypowers** [comment]
Closed by #1690, we can always iterate in _new issues_ for cubone
