### ISSUE TITLE
[bug] cta secondary variant line break issue

### ISSUE THREAD

**Issue by mfwells** [RedHat-UX/red-hat-design-system#1192]
### Describe the bug

in a multi word cta, on primary or secondary cta's, when testing responsiveness and the width of the cta is less than all the words on a single line, it breaks down to a second line, however is not left aligned or center aligned.

### Which Component?

rh-cta

### Steps to reproduce

change browser width to force the cta to be smaller than the full width of all the words on one line, breaking the words onto multiple lines. 

### Expected behaviour

It should either be left aligned or center aligned, functioning similar to the default variant cta

### Screenshots

![Screenshot 2023-08-10 at 9 07 36 AM](https://github.com/RedHat-UX/red-hat-design-system/assets/141932945/f1e0881c-aa52-4610-ac2e-10de2018d97c)

### Element HTML

```HTML
<div class="card-footer pb-2 pb-xl-3">
<rh-cta variant="secondary" color-palette="dark">
<a href="#">Get product details</a>
</rh-cta>
</div>
```

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by bennypowers** [comment]
This will go out with [v1.1.1](https://github.com/RedHat-UX/red-hat-design-system/pull/1141)
