### ISSUE TITLE
Request to add an issue link for the site

### ISSUE THREAD

**Issue by castastrophe** [RedHat-UX/red-hat-design-system#120]
It would be nice to include a direct link for site feedback to the page so it's easy for users to open issues against this repository.

**Comment by dcaryll** [comment]
@coreyvickery thinking we can add a "Submit a bug" button in the top right of the header. Would you supply a design for that?

**Comment by coreyvickery** [comment]
@castastrophe @dcaryll 

Here's an example of a `Submit a bug` button in the title area. I think the positioning can work with all of the component names. The location on mobile has to be a little different.

https://xd.adobe.com/view/2bc4c20e-e89e-4a19-8f6d-172a5a64db36-7e97/

**Comment by markcaron** [comment]
@coreyvickery @dcaryll We currently have a submit a bug feature (or really "Submit feedback") on ux.redhat.com through Usersnap. Are we considering these implementations synonymous (and thus closing this request)? Or do we want to handle this differently?

![image](https://user-images.githubusercontent.com/1890950/164232611-0c05ed83-500d-4e9d-885d-9f3c6e4ffcce.png)

**Comment by coreyvickery** [comment]
@markcaron I'm more of a fan of the `Submit feedback` function because it's more robust than a simple button (thanks to Usersnap). However, you need to be a Red Hat employee to use Usersnap, so it depends on how open source we want the website to be right now.

**Comment by bennypowers** [comment]
if there's going to be a direct link, perhaps it should be to the discussion board rather than issues. so far we've been treating the issue board as directly actionable things only - bug reports or prioritized work.

**Comment by coreyvickery** [comment]
@bennypowers @markcaron Here's what I've been experimenting with. The link can't stay in the header navigation at small breakpoints, so I'm advocating to move it into the menu.

https://xd.adobe.com/view/112e18ea-305f-4017-bc39-d5edbb9db801-447d/

cc @marionnegp

**Comment by coreyvickery** [comment]
@bennypowers Thoughts about the above?

**Comment by bennypowers** [comment]
position and responsiveness LGTM

labeling and target: does this just dump on the repo readme? does it link to /issues/new?

What about when I'm on an element page, does it now link to the element's subdirectory in the repo file tree?

**Comment by brianferry** [comment]
I would think a GitHub link on the top level would take me to the repo readme, maybe inside the component pages themselves we can link to the specific sub-directory?  We could also add a link in the readme to the discussion board though for new ideas / thoughts?

**Comment by coreyvickery** [comment]
@bennypowers Thoughts on what Brian is proposing?

**Comment by bennypowers** [comment]
makes sense.

**Comment by coreyvickery** [comment]
@markcaron @hellogreg Could we close this and open a new issue for adding GitHub to the website instead?

**Comment by markcaron** [comment]
Closing in favor of #1443
