### ISSUE TITLE
[docs] Clean up feedback links

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#1201]
Currently, we have two "Submit feedback" elements at ux.redhat.com--each with different purposes and actions:

![Submit feedback links](https://github.com/RedHat-UX/red-hat-design-system/assets/642695/16543d4a-227c-4ccc-a0df-ce9526dbcf5e)

One is a button near the nav section across the entire site that opens a website bug reporting interface.

The other is a link within the "Contribute" section of the homepage. This link then points to the "Feedback" section of the Overview section's Get Started page. In this section is then a "contact us" link pointing to ~~a "digital-design-system" email address~~ the GitHub discussions page (changed from the email at some point):

![Contact us link on the Overview Get started page](https://github.com/RedHat-UX/red-hat-design-system/assets/642695/2c3c2b9b-215f-441d-b0a5-246ec7924ff6)

We should rethink how our feedback/contact/contribute process works and looks (as they may all be separate things).

At the very least, we definitely need to clear up the two "Submit feedback" elements that have the same text but different purposes, which is an accessibility error.

_12/12/23 update: The associated PR is set to change the text to "Join the discussion" and point directly to the discussions page._

**Comment by coreyvickery** [comment]
@hellogreg Still a priority to get done by EOY? If yes, shouldn't take long for us to fix.

**Comment by hellogreg** [comment]
@coreyvickery Yeah, I'll just change the text to clarify. You're right that it shouldn't take long.
