### ISSUE TITLE
[bug] headings on full width image card aren't working

### ISSUE THREAD

**Issue by diwanshi** [RedHat-UX/red-hat-design-system#1205]
### Describe the bug

We should be able to provide a heading below the full width image on rh-card, but it seems it doesn't work

### Which Component?

rh-card

### Steps to reproduce

1. Go to [this page](https://ux.redhat.com/elements/card/demo/variants/)  and check the variant with full width image (last card)
2. Add any of the heading tags before `<p>` and provide a slot="header"
3. Check the heading, it doesn't show up
4. Try providing h2 as part of the body
5. The styles for heading doesn't take any effect

The only way we could make this work was to wrap the whole body inside a div and applying styles to the div but thats not the recommended approach.

### Expected behaviour

The heading is shown below the full width image card

### Screenshots

![Screenshot 2023-08-28 at 12 26 36 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/5659299/8ce72bda-b629-41fd-9115-e5015f8cf21a)

![Screenshot 2023-08-28 at 12 26 11 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/5659299/7bc7c971-b04d-484b-bb34-b1aaed817f68)

### Element HTML

```HTML
<rh-card class="full">
      <img slot="header" src="../kitten-400x250.jpeg">
      <h2 slot="header">Heading h2</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
         Nullam eleifend elit sed est egestas, a sollicitudin mauris
         tincidunt. Pellentesque vel dapibus risus. Nullam aliquam
         felis orci, eget cursus mi lacinia quis. Vivamus at felis sem.</p>
      <rh-cta priority="primary" slot="footer">
        <a href="#">Call to action</a>
      </rh-cta>
</rh-card>
```

### Operating System (OS)

macOS

### Browser

Chrome, Safari, Firefox

**Comment by brianferry** [comment]
@diwanshi 

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/9708152/6ae8ea1e-f86b-4175-86de-221518addb6d)


Is this something like what you would expect?

& with the following html?

```html
  <rh-card class="full">
    <img slot="thumbnail" src="kitten-400x250.jpeg"></img>
    <h2 slot="header">Headline, sm</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
       Nullam eleifend elit sed est egestas, a sollicitudin mauris
       tincidunt. Pellentesque vel dapibus risus. Nullam aliquam
       felis orci, eget cursus mi lacinia quis. Vivamus at felis sem.</p>
    <rh-cta priority="primary" slot="footer">
      <a href="#">Call to action</a>
    </rh-cta>
  </rh-card>
```

**Comment by diwanshi** [comment]
@brianferry yes thats exactly what we want

**Comment by brianferry** [comment]
@diwanshi 

I have updated the pull request to instead of setting up a new slot in the header it instead allows for multiple items to be slotted in the header. 

The following html should work and is valid in the new update:

```html
<rh-card class="full">
      <img slot="header" src="../kitten-400x250.jpeg">
      <h2 slot="header">Heading h2</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
         Nullam eleifend elit sed est egestas, a sollicitudin mauris
         tincidunt. Pellentesque vel dapibus risus. Nullam aliquam
         felis orci, eget cursus mi lacinia quis. Vivamus at felis sem.</p>
      <rh-cta priority="primary" slot="footer">
        <a href="#">Call to action</a>
      </rh-cta>
</rh-card>
```
