### ISSUE TITLE
[bug] rh-navigation-secondary desktop height 

### ISSUE THREAD

**Issue by wesleymiles** [RedHat-UX/red-hat-design-system#1208]
### Describe the bug

the implementation of the secondary nav on product pages has the height shorter than the docs says it should be. 

- live [redhat.com product pages](https://www.redhat.com/en/technologies/cloud-computing/openshift) height: desktop = 74px, mobile 74px
- [component](https://ux.redhat.com/elements/navigation-secondary/style/#configuration) height: desktop = 86px, mobile = 80px

@coreyvickery confirmed that the ux dot specs were correct 

> _"For large viewports, the line height of the product logo text at two lines (54px) combined with the top and bottom padding (32px) should come to 86px.
> For small viewports, the line height of the product logo text at two lines is 48px. 48 + 32 = 80px.
> A minimum height could be 80px."_

### Which Component?

rh-navigation-secondary

### Steps to reproduce

compare the secondary nav height from a product page, like this one https://www.redhat.com/en/technologies/cloud-computing/openshift to the specs on https://ux.redhat.com/elements/navigation-secondary/style/#configuration

### Expected behaviour

We expect the height of the secondary nav to be taller to match the component specs.

### Screenshots

![unnamed](https://github.com/RedHat-UX/red-hat-design-system/assets/613815/d2c8a34e-95cb-41ed-bac3-44f8188ce50c)

### Operating System (OS)

macOS

**Comment by zeroedin** [comment]
Will get a PR in for this ASAP.
