### ISSUE TITLE
[bug] `<rh-card>` slotted title pattern padding not aligned

### ISSUE THREAD

**Issue by brianferry** [RedHat-UX/red-hat-design-system#1209]
### Describe the bug

[Link](https://deploy-preview-1200--red-hat-design-system.netlify.app/patterns/card/#sample---slotted-title)

In the "Slotted Title" pattern for card, the padding for the **Header** and the **Body** are not aligned.  The heading has a padding-inline of 24px and the body has a padding-inline of 32px.  Put more simply, the heading is using `--rh-space-xl` and the body is using  `--rh-space-2xl`.  

### Which Component?

rh-card

### Steps to reproduce

1. Go to https://deploy-preview-1200--red-hat-design-system.netlify.app/patterns/card/#sample---slotted-title
2. Inspect the **Header** for the "Slotted Title" pattern
3. Confirm the padding-inline is 24px
4. Inspect the **Body** of the card
5. Confirm the padding-inline is 32px.

### Expected behaviour

The heading and the body should be inline the same amount

### Operating System (OS)

macOS

**Comment by marionnegp** [comment]
@brianferry, the padding in the title bar (16px) looks correct. I was wondering if we wanted to allow the header text to look like this:
<img width="352" alt="Screenshot 2023-09-06 at 9 35 08 AM" src="https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/64081d74-a207-4af1-bed6-e6d8d60654b8">
or lock it down to look like this always:
<img width="201" alt="Screenshot 2023-09-06 at 9 36 39 AM" src="https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/739495b6-19d6-4a19-a80e-446088301264">

cc: @coreyvickery

**Comment by markcaron** [comment]
Fixed by #1380
