### ISSUE TITLE
[feat]: Create `<rh-back-to-top>`

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1213]
`<rh-back-to-top>`

Back-to-top link that will scroll page back up to the top of page that is longer then viewport.

Best practices: https://www.nngroup.com/articles/back-to-top/

Stackoverflow with a detailed response that contains more best practices: https://stackoverflow.com/questions/73376430/back-to-top-link-accessibility

**Comment by coreyvickery** [comment]
@markcaron @hellogreg Proposing moving this to the `Chansey` release.

**Comment by hellogreg** [comment]
@coreyvickery Done.

**Comment by markcaron** [comment]
Customer Portal homepage: 

![Image](https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/89a648ee-e083-4a4e-8134-7cd0ddc517d3)

**Comment by hellogreg** [comment]
[Red Hat Architecture center](https://www.redhat.com/architect/portfolio/):

![Back to top at RHDC](https://github.com/RedHat-UX/red-hat-design-system/assets/642695/9df01ec7-2cb2-4619-a27c-1106bbdeac7c)

**Comment by coreyvickery** [comment]
@zeroedin I say we just use the same one as PatternFly.

https://www.figma.com/proto/yXp4lxkrrh2r0Sj4gb07Wf/rh-back-to-top?page-id=3%3A29&type=design&node-id=4-2&viewport=573%2C441%2C1&t=b3kiY7fVKQdsJOC5-1&scaling=min-zoom&mode=design
