### ISSUE TITLE
[bug] Installation section for all components is broken

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1218]
Looks like something is going on with the installation section for all elements/**/code pages.  Section currently returning `None`

https://ux.redhat.com/elements/navigation-secondary/code/

https://ux.redhat.com/elements/accordion/code/

https://ux.redhat.com/elements/footer/code/

**Comment by brianferry** [comment]
I'll take a look at this if you're cool with that @zeroedin

**Comment by zeroedin** [comment]
> I'll take a look at this if you're cool with that @zeroedin

All yours!  Thanks @brianferry

**Comment by brianferry** [comment]
Looks like this is being caused by both the PFE and RHDS using the same shortcode name 'renderInstallation' that was released in the newest pfe-tools.  Going to update the PFE install doc so that both RHDS and PFE can use the same one and reduce duplication.
