### ISSUE TITLE
[docs] Provide proper <table> markup guidance

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1224]
I'm not sure if this would live under the Accessibility section or part of code guidelines for a Table pattern or element, but we should provide proper markup guidance for tables.

Looking to include things like:

- [What constitute tabular data](https://heyoka.medium.com/lets-bring-table-to-the-table-again-f1ae751159d5) and when to use a list instead
- Use of `<thead>`, `<th>` elements, including inside `<tbody>`
- Use of `scope` attribute
- Use of the `headers` attribute
- Use of `<caption>` element
- Etc.

**Comment by bennypowers** [comment]
should this not be closed by #431 ?

we shouldn't issue a guideline which recommends using table without rh-table, should we? wouldn't that be confusing and lead to divergent user experience and decreased quality for customer?

**Comment by markcaron** [comment]
@bennypowers I was actually envisioning a deeper dive into the proper way to mark up a table within `<rh-table>` (or really tables in general), under `Accessibility`. The only helpful attribute we really mention is `scope` under the `Code` tab. Most developers rarely even add that, and could benefit from a better understanding of how `id` and `headers` attributes are utilized to build better, more accessible tables.
