### ISSUE TITLE
[bug] vite bundler breaks <pf-icon> imports

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#1241]
### Describe the bug

When trying to use the Vite dev server we get an error saying that the `PfIcon.getIconUrl` has resolved the url to `undefined`.  This is because Vite doesn't support import.meta.url when using dynamic values:

```js
PfIcon.getIconUrl = (set, icon) => {
  return new URL(`/icons/js/${set}/${icon}.js`, import.meta.url);
}
```

results in `http://localhost:5173/undefined`

From the Vite docs

```
However, the URL string must be static so it can be analyzed, otherwise the code will be left as is, which can cause runtime errors if build.target does not support import.meta.url
```

source: https://vitejs.dev/guide/assets.html#new-url-url-import-meta-url

### Which Component?

pf-icon

### Steps to reproduce

1. Create react app with Vite `npm create vite@latest`
2. Choose the `React` and `Typescript` options
3. Install PFE `npm i -s @patternfly/elements`
4. Add this to App.tsx
```ts
import { Icon } from '@patternfly/elements/react/pf-icon/pf-icon.js';
```tsx
import { Icon } from '@patternfly/elements/react/pf-icon/pf-icon.js';

function App() {
  return (
    <>
      <Icon icon='ad' />
    </>
  )
}

export default App
```
5. Run the dev server `npm run dev`
6. Visit http://localhost:5173/
7. Verify that you see the following error in the console.
```
[pf-icon] Failed to fetch dynamically imported module: http://localhost:5173/undefined
```

### Expected behaviour

We need a work around documented for why this is happening and a happy path for Vite users

**Comment by bennypowers** [comment]
This is not a bug in pfe, which uses the now quite will established import.meta.url standard. Rather, this is a limitation of vite, which imposes it's opinions and technical limitations on project maintainers.

However, *it is still absolutely possible to use pf-icon in vite projects*: users that wish to work within the limitations of vite can return a bare module specifier and apply an import map. This is in fact an ideal setup regardless of the delivery mechanism.

Example: https://stackblitz.com/edit/vitejs-vite-mbjkdx?file=src%2FApp.tsx%3AL15

**Comment by bennypowers** [comment]
Clefairy introduces rh-icon, which should play nicer with bundlers

**Comment by bennypowers** [comment]
Please open a new issue after 2.1.0 if this persists
