### ISSUE TITLE
[bug] <rh-tile> instance in the hero of the interactive lab pages has elements that look off

### ISSUE THREAD

**Issue by wesleymiles** [RedHat-UX/red-hat-design-system#1243]
### Describe the bug

The way that the tiles in the hero were changed recently. 
- the linked heading no longer is blue
- the "introductory lab" text is no longer 14px
- the footer element "60 mins" should also be 14px

https://www.redhat.com/en/interactive-labs/openshift

### Which Component?

rh-tile

### Steps to reproduce

1. go to https://www.redhat.com/en/interactive-labs/openshift
2. look at the tile in the hero

### Expected behaviour

The hero tile should match the styles of the cards below -- they seem fine

### Screenshots

as is
![as is](https://github.com/RedHat-UX/red-hat-design-system/assets/613815/f6f504a4-8f7e-4452-96e7-26a7cff84df5)

should be
![should be](https://github.com/RedHat-UX/red-hat-design-system/assets/613815/f1e21de5-84aa-480c-a731-ef966fee466a)

### Operating System (OS)

macOS

**Comment by wesleymiles** [comment]
It looks like rh-tile is not available for "custom hero" in drupal, which is what these pages use. The cards in the hero are built in a general raw box to achieve the styles that are intended to match rh-tile.

Something in a recent update to rh-tile, must have changed the support of the manual styles.

Adam Lazzara has opened a ticket to add the ability to add rh-tile to the hero pattern. --> https://issues.redhat.com/browse/DXFED-1078 After which, we can add the component properly.

Closing for now because the bug wasn't with the component but with implementation.

**Comment by nikkimk** [comment]
@wesleymiles we don't have an `rh-tile` component on [RHDS](https://ux.redhat.com/) yet. It's still in [development](https://github.com/RedHat-UX/red-hat-design-system/issues/898).
