### ISSUE TITLE
[feat] `<rh-video-embed>` element

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1247]
We need a new Video element/component with the following criteria:

- Accepts placeholder / thumbnail image (optional)
- Overlays a play button
- Handles cookie consent for YouTube
  - If no, "error messaging" with button to update preferences
  - If yes, plays video from YouTube embed
- Plays video from `<video>` element (no need for cookie consent)

### Mockups

- [Video play button](https://xd.adobe.com/view/d20a1c17-375c-4c7f-6827-5fe2f8c2d92f-a43b/screen/a74b2e0f-4d8d-4461-8314-c64f6f3e8329)
- [Cookie consent messaging](https://xd.adobe.com/view/b77881a0-d0d8-4ab6-a00a-62cd535feff2-e22b/)

**Comment by markcaron** [comment]
@marionnegp can you provide the assets for this? Seems like there's a logo backdrop behind the cookie consent.

**Comment by marionnegp** [comment]
![cookie-opt-in-video-thumbnail-bg](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/bda3e898-0fd1-4c06-ab3a-5bd84d832e6c)

**Comment by bennypowers** [comment]
prior art:
- https://ux.redhat.com/elements/dialog/guidelines/#video-player-dialog
- https://ux.redhat.com/elements/audio-player/

**Comment by markcaron** [comment]
@nikkimk to do some discovery work around whether there is a need for separate components/elements for 3rd party videos vs. the native `<video>` element, and how we'd tackle the APIs.

**Comment by coreyvickery** [comment]
@nikkimk @hellogreg Proposing to move this to the `Chansey` release.

**Comment by hellogreg** [comment]
@coreyvickery Done. Thanks! If we decide it needs to go to Charmander, we can do that, too.

**Comment by nikkimk** [comment]
Questions for discussion at Monday's office hours:
- Should the component open the cookies dialog out of the box, or is this a pattern that consumers have to implement?
- Given there's a lot of microcopy, do we handle it like audio player with translations, have the consumers slot in their own text, or some other method?

**Comment by bennypowers** [comment]
- composition is better, we can maybe make a wrapper component at a later date. we can't know how the translation systems on different pages will work
- probably prudent for the CMS devs to proactively fill in the defaults on all slots / content attributes, in their CMS patterns
- transcript API should be as similar to rh-audio-player as possible, preferably using the very same rh-cue elements

**Comment by nikkimk** [comment]
> * Should the component open the cookies dialog out of the box, or is this a pattern that consumers have to implement?
Nikki will reach out to ask more about the cookies modal.
> * Given there's a lot of microcopy, do we handle it like audio player with translations, have the consumers slot in their own text, or some other method?
Microcopy will be slotted. English will be default text in the slot, but patterns in Drupal should explicitly slot in microcopy for translations.

**Comment by nikkimk** [comment]
For the opt-in part:
- slots for `consent-message` and `consent-button-text`
- properties `require-consent` and `has-consent`
- `on-consent-click` event to open cookie dialog
