### ISSUE TITLE
[bug] `<rh-playground>` external content included in demo editor

### ISSUE THREAD

**Issue by brianferry** [RedHat-UX/red-hat-design-system#1255]
### Describe the bug

In the playground editor on components (such as https://ux.redhat.com/elements/tabs/) when the "Load Demo" button is clicked we are seeing external content being included in the editor such as context provider and external stylesheets. 

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/9708152/f6ce1b51-2cb9-48fb-ba7d-82e1619a3013)

### Which Component?

rh-playground

### Steps to reproduce

1. Go to [tabs repo overview](https://ux.redhat.com/elements/tabs/#demo)
2. Go to the "Demo" section
3. Click on the "Load Demo" button in the bottom right of the code block
4. In the editor you should see code such as the `<head>` and `<link>` tag.

### Expected behaviour

We only show the code related to the component demos and not the external content.

### Operating System (OS)

macOS, Linux

### Browser

Chrome, Safari, Firefox

**Comment by bennypowers** [comment]
Closed by #1648
