### ISSUE TITLE
[docs] Revisit and reimplement design/code repo statuses

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1268]
Not long ago, we removed the `repoStatus` shortcode from the elements' docs since it didn't provide much value in its current state. I'd like to revisit that as well as repurpose it (or build a similar function) to autogenerate rows in a larger table on the `Design/code status` top-level page since it's woefully out of date (and has little to no value as is).

I'm thinking each element and pattern should have the following status (paired with an icon):

- Ready — available for use
- Partially ready — available, but some features may be missing
- Planned — upcoming or WIP
- Deprecated
- Not available — currently not available

And these statuses would be across the following repos/libraries (as columns):

- Documentation
- Figma library
- XD library — soon to be deprecated
- RH Elements
- webRH*

In addition, it might be nice to have the following `tags` (paired with each element/pattern name):

- New
- Beta
- Experimental

Open to ideas, too, of course.

**Comment by markcaron** [comment]
@marionnegp @coreyvickery Can we get a mockup on how these status tags might look? We can work together offline in January.

**Comment by coreyvickery** [comment]
@markcaron @marionnegp @kylebuch8 @diwanshi Current design is below.

https://www.figma.com/proto/TaPXWNuUzEupDIH9w3L3hC/Design%2Fcode-status-redesign?page-id=0%3A1&type=design&node-id=3-3073&viewport=125%2C144%2C2&t=M9xgjCdbvXxTzqqQ-1&scaling=scale-down&mode=design

**Comment by markcaron** [comment]
`Closes` didn't close again.
