### ISSUE TITLE
[docs] Table code documentation is missing explanation of mobile breakpoints

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1286]
Under `Code` on RH Table's documentation, we're showing usage examples of `data-label` without clarifying its purpose. Since it's a Light DOM solution for providing "headers" inside `<td>` elements on mobile (like Tablesaw), we should provide guidance around its usage.

<img width="1062" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/466e4028-1b49-41f9-95bc-2792ec468732">

**Comment by zeroedin** [comment]
Note switching to @container queries as well in #1881

**Comment by bennypowers** [comment]
Closed by f665cc9e
