### ISSUE TITLE
[bug] Table's mobile breakpoints exclude `<th>` inside `<tbody>`

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1288]
The CSS for the mobile breakpoints is excludes the potential for a `<th>` to exist inside a `<tbody>`. For example:

```
:is(rh-table) thead ~ tbody tr td:before {
    font-weight: var(--rh-font-weight-heading-bold, 700);
    text-align: left;
    content: attr(data-label);
    display: inline-block;
  }
```

We should expand the CSS rules/selectors to include a `<th>` inside `<tbody>` for those edge cases where there might be one along with its column header:

```
:is(rh-table) thead ~ tbody tr td::before,
:is(rh-table) thead ~ tbody tr th::before {
    font-weight: var(--rh-font-weight-heading-bold, 700);
    text-align: left;
    content: attr(data-label);
    display: inline-block;
  }
```

Note: also adding the extra `:` to the `::before` pseudo-element.

Can be tested on the following demos:

- https://ux.redhat.com/elements/table/demo/row-and-column-headers/
- https://ux.redhat.com/elements/table/demo/column-headers/

**Comment by bennypowers** [comment]
I put together a branch which makes this change, but the `::before` pseudo element is only for the `data-label` attr's contents.

Notice how, after making this change, the new pseudo-element has 0 width and height:

<figure><figcaption>Before: existing pseudo on td has content from label</figcaption>

![Screenshot from 2024-01-11 09-15-34](https://github.com/RedHat-UX/red-hat-design-system/assets/1466420/e0ee8314-90ab-4ab3-8f44-36585afd964f)

</figure>
<figure><figcaption>After: new pseudo on th has no content</figcaption>

![Screenshot from 2024-01-11 09-15-19](https://github.com/RedHat-UX/red-hat-design-system/assets/1466420/7b707bba-14c0-4d63-9436-aad35bcd116e)

</figure>
