### ISSUE TITLE
[docs] rh-tag: fix example formatting under Best Practices

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1295]
The best practices examples for `<rh-tag>` are formatted like this:
<img width="928" alt="Screenshot 2023-10-23 at 10 09 20 AM" src="https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/feaa6289-cb75-41a9-b628-108d78299ac5">

The border should be red and have an error/danger icon like this:
<img width="917" alt="Screenshot 2023-10-23 at 10 09 07 AM" src="https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/67cfcf49-3a94-4619-8aa3-518a0813d140">

**Comment by bennypowers** [comment]
use {% example %} shortcode
