### ISSUE TITLE
[bug] `<rh-tile-group>`: built in style guidelines

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#1303]
### Description

The style guidelines give some terse advice about tile group grid widths. 

Tile and Tile Group should implement those styles, not page devs.

### Suggested solution

If you check the tile demos, you'll see that the demo files include global css in order to layout the tile groups. These styles should be built-in to the tile group element, such that we'd be able to delete all the global css from the tile demo files, and they would still 
a) look like they do now
b) work in multiple ds grid layout circumstances

### Additional context

Good excuse to work on grid tokens, play with subgrid as well.

**Comment by markcaron** [comment]
Moved to Chansey release.

IMO, `<rh-tile-group>` should handle only the functionality needed for radio and checkbox tile groups, like a `<fieldset>`. Any layout or grid styling/patterns should be handled with a separate layer of CSS that can be applied to any element, including `<rh-tile-group>`. This way we won't have to maintain layout/grid in multiple components while also providing a larger degree of flexibility.

Let's focus on coming up with a layout/grid CSS solution in CY24 Q1.

**Comment by bennypowers** [comment]
here's what it looks like when the user *doesn't* customize the layout

![Image](https://github.com/RedHat-UX/red-hat-design-system/assets/1466420/67a752c3-e2a5-4e16-830f-bcc2e90c3e6b)

**Comment by markcaron** [comment]
As discussed in standup + refinement today, we're looking to utilize `container queries` to apply some basic grid styles per our docs reflected in the [Tile mockup](https://www.figma.com/design/8cZsqpCsq3KyiHf5VyBuRO/Element---Tile?node-id=1-885&t=48d1lJH46XKinsSY-0).

The grid is applied irrespective of whether they're link tiles or checkbox/radio tiles, and can easily be overwritten by some CSS.

Good first issue.

**Comment by bennypowers** [comment]
@OneEightyFirst heads up we're planning on baking in the _internal_ layout of tile group
