### ISSUE TITLE
[bug] `<rh-tabs>` mobile overflow buttons are broken for RTL

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1304]
mobile overflow button are broken for RTL

icons face the wrong way and do scroll the overlfow

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/02a1d313-1c47-4820-a46c-3bfd7d8409d8)

**Comment by bennypowers** [comment]
check the demos pr, i noticed that the scroll buttons don't appear until user performs a scroll action on the tab bar. this may be related here, or it may not be

**Comment by zeroedin** [comment]
> check the demos pr, i noticed that the scroll buttons don't appear until user performs a scroll action on the tab bar. this may be related here, or it may not be

Interestingly enough the button's initialize correclty (just not the icons) in the playground output iframe but not in your implementation for the playground demo tabs.  Related /shrug

**Comment by bennypowers** [comment]
Interesting indeed. I'm sure we'll crack that chestnut soon

**Comment by zeroedin** [comment]
This issue is currently blocked by upstream change to `<pf-tabs>` and Base class removal.  Once the base class is removed from upstream and the implementation for how overflow functionality is enabled is exposed in the render method explicity in `rh-tabs`. This will allow us to add the RHDS only `DirController`  to swap the left(previous) and right(next) buttons functionality as necessary with RTL.  Additional changes maybe warranted in the shadowDOM.

psuedo code
```js
const rtl = this.#dir.dir === 'rtl';
return html`
<button id="previousTab" tabindex="-1"
  aria-label="${this.labelScrollPrevious}" /* might have to rename labels to support  as currently named directional*/
  ?disabled="${!rtl ? this.#overflow.overflowLeft : this.#overflow.overflowRight}"
  @click="${!rtl ? this.#scrollLeft: this.#scrollRight}">
  <pf-icon icon="angle-left" set="fas" loading="eager"></pf-icon>
</button>
`
```

**Comment by zeroedin** [comment]
@markcaron this one was blocked see above comment, going to move it to Chansey.
