### ISSUE TITLE
`<rh-context-picker>`: use radio group instead of datalist

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1305]
After #1291 lands, we should use radio group instead of datalist for `rh-context-picker`

**Comment by zeroedin** [comment]
Related: https://github.com/RedHat-UX/red-hat-design-system/pull/1317#pullrequestreview-1704678210

**Comment by markcaron** [comment]
@zeroedin how are we doing on this? Do we need to kick it to Chansey?
