### ISSUE TITLE
[bug] <rh-card> padding

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1324]
### Describe the bug

The block padding for card's body and footer needs to be adjusted. Right now the space between the body and footer is 64px because of padding in both sections. The space between the body and footer should be 24px (`--rh-space-xl`).

Additionally, can the padding-inline of header be changed to `--rh-space-2xl`? It'll help the content in the header align with the rest of the content.

### Which Component?

rh-card

### Steps to reproduce

1. Pull up a demo of card.
2. Check to see if padding matches screenshots below.

### Expected behaviour

The space between the body and footer should be 24px (--rh-space-2xl). Inline padding of header should change to 32px (--rh-space-2xl).

### Screenshots

**Current padding/spacing:**

![Screenshot 2023-11-08 at 9 26 29 AM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/a8bf59ce-b380-4fb6-bb44-14e7c39729e2)

![Screenshot 2023-11-08 at 9 26 35 AM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/9552a0dc-3c5a-40ff-acfe-affc2b262b16)

**Expected spacing:**
 
![Screenshot 2023-11-01 at 11 32 03 AM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/3b7b9829-4039-490b-a4ee-b71e4f47a1eb)

### Operating System (OS)

macOS

**Comment by bennypowers** [comment]
i see now, so this maybe could be solved with [`margin-trim`](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-trim), which is experimental

but in the mean time we can work this out maximum with empty classes and some oldschool css
