### ISSUE TITLE
[bug] `<rh-tag>` inherits font styles that it shouldn't

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1331]
### Describe the bug

`<rh-tag>` currently inherits the font weight, font family, and line height if it's in a heading or paragraph tag.

### Which Component?

rh-tag

### Steps to reproduce

View the [deploy preview](https://deploy-preview-1321--red-hat-design-system.netlify.app/foundations/color/theming/) of the Color page (pr #1321).

### Expected behaviour

These properties should be set in the element.

### Screenshots

![Screenshot 2023-11-10 at 12 13 09 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/a3b78315-c7cc-4d8d-bfc3-8175c7cdc45c)

![Screenshot 2023-11-10 at 12 12 53 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/438fe525-469f-4815-b1aa-6e1d1c1f290e)

### Operating System (OS)

macOS

**Comment by zeroedin** [comment]
@marionnegp assigned myself to this I'll get a patch PR up for this asap.

**Comment by zeroedin** [comment]
Closed by  #1574
