### ISSUE TITLE
[feat] `<rh-navigation-secondary>` add the `aria-current="page"` attribute to logo

### ISSUE THREAD

**Issue by max-messmer** [RedHat-UX/red-hat-design-system#1337]
### Description

Per Hadley and Liz Wood: The OpenShift, Ansible, and RHEL secondary should include the styling on each landing page's logo for the respective products, so users will be able to quickly tell they are on the 'home' page.  @marionnegp @coreyvickery 

### Suggested solution

The `aria-current="page"` attribute for `<rh-navigation-secondary>` should get extended to include the logo.

**Comment by hellogreg** [comment]
Resolved
