### ISSUE TITLE
[docs] Broken images on Breakpoint page

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system#1343]
### Description

https://ux.redhat.com/tokens/breakpoint/

**Comment by zeroedin** [comment]
> Reopening because breakpoint token images are still broken

Out of curiosity any reason these need to be images and not just html css?  Example: https://red-hat-design-tokens.netlify.app/#space

**Comment by marionnegp** [comment]
@zeroedin, I think it's because the images are more complex icons than the space or length images.

**Comment by zeroedin** [comment]
> @zeroedin, I think it's because the images are more complex icons than the space or length images.

I just realized they were the icons not the spacer boxes, sorry, deleted my reply right before you responded.
