### ISSUE TITLE
[bug] `<rh-tab-panel>` has color provider decorator however not implemented

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1353]
`<rh-tab-panel>` should only be a consumer.  There is no current design spec that calls for a panel to provide its own context.  

That said there is precedent in `<rh-accordion>` where a panel provides it's own context:
<img width="707" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/13666/4a8f86fb-2694-451c-8f7e-dc627da5b4ef">

However maybe doing the same to a tab panel might cause the panel to feel detached from the tab that activated it when the panels color context is different?  Accordion is more self contained so the relationship still exists visually.

I believe the addition of the decorator was a mistake and we should remove the color context provider decorator.  As it stands there is no current style implementation for panel to switch even if `color-palette` is set and I don't believe doing so would be a breaking change.

@coreyvickery @marionnegp @bennypowers thoughts?

**Comment by marionnegp** [comment]
@zeroedin, my gut says to keep `<rh-tab-panel>` a consumer only, at least until someone comes to us with a use case that requires it to be a provider.

I think we could get away with `<rh-tab-panel>` providing its own context when using open tabs. With box tabs, we'd want the active tab color to match the tab panel. Here's a screenshot of some (very shoddy) mockups just to see what it would look like if someone added a pink background to the panel.

<img width="941" alt="Screenshot 2023-11-16 at 4 24 11 PM" src="https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/d587d50d-fec7-433e-ba7e-6771f90c76bc">

**Comment by zeroedin** [comment]
> 
> ```
> <rh-surface color-palette="darkest">
> 
> <rh-tabs>
>   <rh-tab slot="tab">Consumer</rh-tab>
>   <rh-tab-panel>... normal ...</rh-tab-panel>
> 
>   <rh-tab slot="tab">Override</rh-tab>
>   <rh-tab-panel id="override">
>     <rh-surface color-palette="darkest"> ... overridden ... </rh-surface>
>   <rh-tab-panel>
> </rh-tabs>
> 
> </rh-surface>
> ```
> 
> ```css
> #override {
>   padding: 0;
>   & > rh-surface {
>     padding: var(--rh-space-2xl, 32px);
>   }
> }
> ```


Just for clarity, did you mean to override with a new value for `color-palette` in the above example?  

ex: surface 1 providing `darkest` then surface 2 inside the tab panel maybe providing `lighter`?

If so I would think this would provide that separation of concerns, clearly defining a more complex scenario that would have extra design considerations.

**Comment by bennypowers** [comment]
Yes that's what I meant, that's for correcting

**Comment by zeroedin** [comment]
Closed in https://github.com/RedHat-UX/red-hat-design-system/pull/1376
