### ISSUE TITLE
[feat] Add fallbacks for new tokens

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1355]
### Description

Once RHDS Tokens 2.0 is added to this repo, elements using crayon color tokens in their CSS will need to have fallbacks.

### Suggested solution

CSS with fallbacks will look something like this:

```
tag.yellow { 
   thing: var(--rh-color-yellow-20, var(rh-color-gold-500));
}
```

**Comment by markcaron** [comment]
@marionnegp is this still valid? IIRC, we moved away from this type of fallback in the tokens work, eh?

**Comment by marionnegp** [comment]
@bennypowers, I linked #1399 to this issue. Not sure if we can still use those old crayon tokens as fallbacks for the new ones, but I did check for any tokens that stylelint rules mistakenly replaced.
