### ISSUE TITLE
[docs] `<rh-tile>`: broken link

### ISSUE THREAD

**Issue by nikkimk** [RedHat-UX/red-hat-design-system#1356]
### Describe the bug

There is a broken link in the tile docs.

### Which Component?

rh-tile

### Steps to reproduce

1. Got to https://ux.redhat.com/elements/tile/code/
2. Click "View the demo in a new tab".
3. Link does not work because it directs to https://ux.redhat.com/elements/tile/code/demo/

### Expected behaviour

Link should be https://ux.redhat.com/elements/tile/demo/

### Operating System (OS)

macOS

**Comment by diwanshi** [comment]
@nikkimk hey I see the same issue for rh-audio-player, rh-button and rh-tooltip. 
Also, it seems the docs for these components are not updated overall (there might be issue created for that already). do you want me to fix the link in all these component for now as a quick fix and later update the docs overall
