### ISSUE TITLE
[bug] rh-tile-group doesn't set the height correctly for multiple rh-tile(s)

### ISSUE THREAD

**Issue by diwanshi** [RedHat-UX/red-hat-design-system#1359]
### Describe the bug

Using `rh-tile-group` with multiple `rh-tile`s should auto adjust the height based on the content but currently we all the tiles have varied height.

### Which Component?

rh-tile

### Steps to reproduce

1. Go to rh-tile [demo ](https://ux.redhat.com/elements/tile/demo/) 
2. Inspect element and edit html
3. Update rh-tile's code with the snippet below
```html
<rh-tile-group style="
    display: flex;
    align-items: top;
    flex-wrap: wrap;
    column-gap: var(--rh-space-2xl, 32px);
    row-gap: var(--rh-space-2xl, 32px);
">
    <rh-tile style="width: 320px;">
      <img slot="image" src="https://fakeimg.pl/296x50" alt="296 X 50 placeholder image">
      <div slot="title">Title</div>
      <h2 slot="headline"><a href="#top">Link</a></h2>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      <div slot="footer">Suspendisse eu turpis elementum</div>
    </rh-tile>
    <rh-tile>
      <img slot="image" src="https://fakeimg.pl/296x50" alt="296 X 50 placeholder image">
      <div slot="title">Title</div>
      <h2 slot="headline"><a href="#top">Link</a></h2>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      <div slot="footer">Suspendisse eu turpis elementum</div>
    </rh-tile>  
</rh-tile-group>
```

4. Observe the variation in the height

### Expected behaviour

The height for each rh-tile inside rh-tile-group should be the same and based on the rh-tile with most content

### Screenshots

<img width="966" alt="Screenshot 2023-11-22 at 8 28 53 AM" src="https://github.com/RedHat-UX/red-hat-design-system/assets/5659299/2f95ce4e-5f09-49db-97bd-8dfcc7deedb4">

### Operating System (OS)

macOS

### Browser

Chrome, Firefox

**Comment by bennypowers** [comment]
We had a similar problem with card. I think we can likely solve this the same way
