### ISSUE TITLE
[bug] hex codes for color-context.css will change with tokens update

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1363]
From @marionnegp on https://github.com/RedHat-UX/red-hat-design-system/pull/1318#discussion_r1381665659
> FYI, the fallback hex code for rh-color-surface-darker will change to #292929 in the next tokens update.

@bennypowers follows up with https://github.com/RedHat-UX/red-hat-design-system/pull/1318#discussion_r1382617057
> As long as we specify the mappings between old and new names, the linter should fix this automatically. Let's sync on this early this week Nov 6

Reference https://github.com/RedHat-UX/red-hat-design-tokens/pull/119

**Comment by bennypowers** [comment]
1. after https://github.com/RedHat-UX/red-hat-design-tokens/pull/115 merges and we release `@rhds/tokens@2.0.0`, we will need to
2. update the dep here
3. copy over the stylelint rules from the tokens 2 changeset
4. run `stylelint --fix` here
5. check for visual regressions
