### ISSUE TITLE
[tools] border radius - design library update

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1364]
### Description

We have some discrepancies for the border radii of the elements in this repo and in our Figma component library. @marionnegp will add audit of which ones. `<rh-cta>` and `<rh-button>` are examples.

### Suggested solution

Make Figma component library match what we have in RHDS. In the future, we can make border radius changes in collaboration with PF, and the border radius tokens can be updated.

**Comment by bennypowers** [comment]
we don't have such a token, we go from 0, to 3px, then all the way to 64px

https://ux.redhat.com/tokens/border/

cc @coreyvickery this should be workshopped

**Comment by markcaron** [comment]
@marionnegp @bennypowers, I think the outlier is Figma, and we should fix this in Figma to match the system.

Our token has a value of `3px` and PF4 uses `3px`, so Figma using the wrong value.

If we change RHDS to be `4px`, then we're not moving toward PF6 nor are we matching PF4. We'd be just introducing yet another value that has us diverge from a single look and feel across RHDS and PF/E.

CC: @coreyvickery

**Comment by marionnegp** [comment]
@markcaron, yeah, I've noticed some discrepancies in the border radius of other Figma components too, so I want to do a quick audit of which ones need to match what we have in RHDS. If we want to match the rounder border radius planned in PFv6, we can change the `--rh-border-width-lg` token then.

**Comment by marionnegp** [comment]
Updates are done!
