### ISSUE TITLE
[bug] Secondary nav showing CTA and acting wonky on iphone

### ISSUE THREAD

**Issue by wesleymiles** [RedHat-UX/red-hat-design-system#1365]
### Describe the bug

Upon testing out the new secondary nav updates on the openshift page, the secondary nav displays the CTA link which it should not, according to docs. The breadcrumbs also appear to be above instead of underneath the nav and nav panel. 

### Which Component?

rh-secondary-nav

### Steps to reproduce

1. using an iphone 14, open [the openshift product page](https://www.redhat.com/en/technologies/cloud-computing/openshift#cloud-services-editions)
2. see the overlapping wonkiness (image attached)
**_note:_** _i was unable to reproduce on my laptop, but i do see a flash of the same error before it fixes itself._
![IMG_2283](https://github.com/RedHat-UX/red-hat-design-system/assets/613815/6254d944-5716-44ce-a275-6356dac953e2)

### Expected behaviour

The CTA link disappears on small screens and the breadcrumbs live below the nav menus / have a lower z-index #

### Screenshots

image scrolled down below the breadcrumbs 
![IMG_2284](https://github.com/RedHat-UX/red-hat-design-system/assets/613815/fa01c1de-df08-4cf3-8029-6ed7e739fca1)

### Operating System (OS)

iOS

### Browser

Firefox

### More browser information

tried in firefox 120.1 and safari

**Comment by wesleymiles** [comment]
weird, it is still happening for me and on my wife’s iphone 11…On Dec 1, 2023, at 4:48 PM, Marionne Patel ***@***.***> wrote:﻿
It looks fine when I use Firefox (120.3), Safari, and Chrome on my iPhone, but I also see it flash before resolving. @wesleymiles, do you still see the CTA and overlapping breadcrumbs?

**Comment by bennypowers** [comment]
which version (os and browser)?

**Comment by marionnegp** [comment]
@wesleymiles, do you see the same wonkiness or the flash of the same error when you view the [secondary navigation demo](https://ux.redhat.com/elements/navigation-secondary/demo/) from your phone? If not, it might be an issue in the Drupal implementation.

**Comment by zeroedin** [comment]
Pretty two there is 2 separate issues here.

1. Additional HTML + CSS in drupal implementation causes overlapping issue.
2. Older iOS versions with older safari will present a importmap/polyfill bug with ux. demos.  I see this using browserstack on iOS devices <= 16.

**Comment by zeroedin** [comment]
After a discussion with @zhawkins , what we are looking at here is a device that is running currently unsupported iOS version.

iOS 16.3 is currently supported, but not <= 16.2.  Safari versions release numbers are similar if not in sync with iOS versions, so Safari 16.3 is the oldest we currently support.   16.3 will be unsupported early next year.

Apple devices all the way back to iPhone XS can support the latest iOS17 and should upgrade to gain security updates.
