### ISSUE TITLE
[wiki] Remove Docs Cleanup Q2 2023 Checklist from Wiki

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1367]
@nikkimk should we remove our [Docs Cleanup Q2 2023 Checklist](https://github.com/RedHat-UX/red-hat-design-system/wiki/Docs-Cleanup-Q2-2023-Checklist) from the wiki?

**Comment by nikkimk** [comment]
@markcaron Yep. I'll do that.

**Comment by nikkimk** [comment]
Done.
