### ISSUE TITLE
[docs] Add terms of use for CSS Parts and Custom Properties

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1369]
We should explicitly say in our docs—like a terms of use—that we reserve the right to remove CSS parts and CSS custom properties from the API, since these are often more advanced / "warranty free" customization options as opposed to the standard custom element attribute API.

**Comment by bennypowers** [comment]
we should remove a bunch of css parts and slots from footer and others, but they have to be in major releases
