### ISSUE TITLE
[bug] RH-table messing up markup

### ISSUE THREAD

**Issue by LyndseyR** [RedHat-UX/red-hat-design-system#1370]
### Describe the bug

RH-table when added in the WYSIWYG in Drupal on RHDC the formatting overlaps with text and results in showing broken styles. 

Manually adding rh-table { height: auto; } has fixed it 

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/20518754/ad654690-f2ac-4ef6-b446-20b9a3debfe4)

RH-table also isn't working on mobile see https://www.redhat.com/en/services/support/technical-relationship-management-service

### Which Component?

rh-table

### Steps to reproduce

1. Go to https://www.redhat.com/en/about/redemptiontable-apr2023

Or 

1. Go https://redhat.com/en/topics/financial-services/the-role-of-cloud-in-embedded-finance
2. Open layout tab
3. Configure LFA
4. Scroll to "Why are cloud platforms important for embedded finance?" Click on <>Source to view html
5. Delete <style>
 rh-table { height: auto; }
</style>
6. Save block
7. Watch styles now broken

### Expected behaviour

The text shouldn't overlap

### Screenshots

![Screenshot 2023-12-07 at 8 39 07 AM](https://github.com/RedHat-UX/red-hat-design-system/assets/20518754/aeadea76-1122-483f-a0fe-67059c0a25d0)
![image](https://github.com/RedHat-UX/red-hat-design-system/assets/20518754/7404f3c9-cef7-40a2-a29f-c5bc95eb9888)
<img width="504" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/20518754/4c4ce5df-e9a8-44f6-b205-5cfc003dabb3">

### Operating System (OS)

macOS

### Browser

Chrome

### More browser information

MacOS Sonoma Version 14.1.1

**Comment by zeroedin** [comment]
As noted in chat the following CSS fixes the issue.  I'm wondering if we should be setting relative positioning and a height to begin with on `:host`. 

```
rh-table { height: auto };
```

**Comment by zeroedin** [comment]
> RH-table also isn't working on mobile see https://www.redhat.com/en/services/support/technical-relationship-management-service

Just following up on this part of this issue as it snuck by me on first read.

@LyndseyR here is a codepen that shows fixes for the mobile view: https://codepen.io/zeroedin/pen/BabBxgj

You'll need to remove the additional styles being added inline on columns, and you'll need to add `data-label` attributes so the responsive table css styles will work correctly.  

This issue will close when https://github.com/RedHat-UX/red-hat-design-system/pull/1372 is merged.
