### ISSUE TITLE
[docs][feat] `<rh-logo-wall>`

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1382]
### Description

This component would display a grid of logos that can be clickable.

### Acceptance Criteria

- [ ] Design done
- [ ] Development done

### Link to design doc

[Figma file](https://www.figma.com/design/dXXfj67M2kPKyGpwaaxmvj/rh-logo-wall?node-id=1-21&t=KG2M8kbvTPmsxc8p-1)

### Other resources

[Drive with images and docs](https://drive.google.com/drive/folders/1f0OsxoRJTjOVm4XV1dF8r5yNERGfUzHm)

**Comment by marionnegp** [comment]
A few examples: 

![Screenshot 2023-12-13 at 4 15 18 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/bb89d465-f3c4-412c-b576-c70ccd14c0b6)
(on [redhat.com](https://www.redhat.com/en))

![Screenshot 2023-12-13 at 4 15 57 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/6c476fcc-5cf3-476b-b5bd-bb9c863948f0)
![Screenshot 2023-12-13 at 4 16 07 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/88fedfd1-0155-4cd2-ac4c-596a895ac0bb)
(on the [OpenShift product page](https://www.redhat.com/en/technologies/cloud-computing/openshift))

**Comment by diwanshi** [comment]
I'd like to work on this one, once its ready for the dev as I've build something similar in cp-elements

**Comment by markcaron** [comment]
@diwanshi @marionnegp, I wonder if this is more of a Pattern than a component/Element. Not sure we'd need to use Web Components to do something that's simple CSS and an `<a>` around an image or SVG.

**Comment by marionnegp** [comment]
Additional examples on [Partners machine learning page](https://www.redhat.com/en/partners/machine-learning-software) and [OpenShift AI page](https://www.redhat.com/en/technologies/cloud-computing/openshift/openshift-ai)'

- Need to determine number of logos per row, amount of spacing in between, and maybe a max height or width
- This should be a pattern, not a component

**Comment by markcaron** [comment]
@diwanshi, @gradymcgee will work on this with @marionnegp and once the design is ready (and in Figma), they can hand it off to development.

One thing left to discuss on the engineering side is where `Patterns` will official live in the repo. Currently, they're under `docs/patterns`, but perhaps they should be at the root (parallel to `elements`)? I'm thinking we'd want patterns and their CSS packaged, right?

CC: @bennypowers @zeroedin @nikkimk

**Comment by bennypowers** [comment]
@markcaron @nikkimk when our heads are cleared of pfe 3 release, we should just go ahead and publish v0.x of pattern manifest, maybe take this as a first example

**Comment by markcaron** [comment]
@gradymcgee when you get the element mockup and documentation mockups done, can you provide those links at the top in the main description?
