### ISSUE TITLE
[feat] `rh-table` no data-label

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1390]
`<rh-table>` when no `[data-label]`'s are present on headers and columns, the table should still present itself in a manner that is still visually logical/readable.

Also to note after a discussion with @LyndseyR `data-label` will not get translated via the XML for RHDC.  Because we use these labels as visual output to the user, on translations they would show as english counterparts which also isn't ideal.  A special translation case maybe able to be made here, but this also might be a good reason to look at alternatives.

**Comment by zeroedin** [comment]
Alternative?: https://codepen.io/smashingmag/pen/bGKBNNr

**Comment by brianferry** [comment]
Can you provide an example of what happens with and without the data-labels being present?  I am trying to see a difference in our local table files with the data-labels being removed but not noticing anything so I'm not sure what I'm missing.

**Comment by zeroedin** [comment]
https://codepen.io/zeroedin/pen/YzgyOM

**Comment by LyndseyR** [comment]
Here is a page example that does not have data labels. https://www.redhat.com/en/about/social. So when viewing on smaller viewport can see it's no longer a great visual experience as there is no table heading and the alignment is off for the table cells

**Comment by zhawkins** [comment]
Would it be possible to have the web component automatically set the data-attribute based on values within a `<th>`? In that way you wouldn't have to count on a user manually setting them.
