### ISSUE TITLE
[bug] `rh-pagination` missing dark theme

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1393]
`rh-pagination` is missing dark theme, although has [specifications in figma](https://www.figma.com/file/j7Rjo2W6PLloxOSXQOpll0/Red-Hat-Design-System-library?type=design&node-id=232%3A17978&mode=dev) and [style tab](https://ux.redhat.com/elements/pagination/style/#dark-theme) on ux.redhat.com

**Comment by adamjohnson** [comment]
Dark theme support added in #1393. ✔️
