### ISSUE TITLE
[docs] details ::marker arrow off center

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1422]
From chat:

Mark C
  [1 hour ago]
Is it just me or are the arrows on the "accordions" off center?

Mark C
  [1 hour ago]
![image](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/09904843-0507-4014-9074-70f8d7f973b4)

...

sspriggs
  [1 hour ago]
tab order should technically still follow visual order if possible

sspriggs
  [1 hour ago]
thinking a toggle button with some small js to toggle the details element would clear it up

**Comment by markcaron** [comment]
Closed in #1465
