### ISSUE TITLE
[bug] Duplicate token on ux dot

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system#1424]
https://ux.redhat.com/tokens/color/

Under `Red orange`, the `40` and `50` values are the same.

<img width="145" alt="Screenshot 2024-01-16 at 1 06 30 PM" src="https://github.com/RedHat-UX/red-hat-design-tokens/assets/45767595/8df57389-1fc8-4dea-9e3e-b566ef8d11c6">

**Comment by marionnegp** [comment]
This will be fixed once [v2.1.0](https://github.com/RedHat-UX/red-hat-design-tokens/pull/127) is released. @bennypowers, is there a particular release cadence for tokens, or can this be released soon?

**Comment by bennypowers** [comment]
@marionnegp we can release 2.1.0 whenever you like. you're welcome to merge the release pr yourself

**Comment by bennypowers** [comment]
this will be address with clefairy so i'm closing now
