### ISSUE TITLE
[docs] Table of Contents on pages

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1433]
For a quick easy win while we wait on [Jump Links discovery](https://github.com/RedHat-UX/red-hat-design-system/issues/1434), let's add a static Table of Contents at top of our docs page (coupled with a back to top).

- [x] Design mockup
- [ ] Dev

**Comment by marionnegp** [comment]
@coreyvickery @markcaron, here are two options for the table of contents:

Option 1: Simple list
![Screenshot 2024-02-20 at 10 15 36 AM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/831920a3-7233-44c4-b93a-f7072d7943d9)

Option 2: List with icons
![Screenshot 2024-02-20 at 10 15 40 AM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/db5b4b48-8c7b-490c-94cd-986e7dd96203)

I mocked up both in [this Figma file](https://www.figma.com/file/8TYHw7u7HGEaacrbEvmF8m/ux-dot-component---table-of-contents?type=design&node-id=0%3A1&mode=design&t=H7aepsTmsuKtNBH4-1).

**Comment by zeroedin** [comment]
@marionnegp @coreyvickery @markcaron  super early implementation of this can be found: https://deploy-preview-1465--red-hat-design-system.netlify.app/foundations/personalization/

**Comment by coreyvickery** [comment]
@zeroedin I thought for this issue, we wanted to do static jump links at the top of a page instead of sticky jump links in the gutter.

**Comment by coreyvickery** [comment]
@marionnegp I like `Option 2`. I made some spacing adjustments, see if you like them. I like the heading size and content as well. I say this feels ready to go.

@markcaron Thoughts?

**Comment by coreyvickery** [comment]
@marionnegp One remaining question (I might have more later) is how many links are there per column before a second column is visible?

**Comment by marionnegp** [comment]
@coreyvickery, I was thinking 4 links.

**Comment by zeroedin** [comment]
> @coreyvickery, I was thinking 4 links.

Consider at different viewport size / container query you may not be able to keep this how many columns rule

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/a925366a-6fe2-4550-b34c-8b01a3adda2e)

In #1465 i used the css `columns` on  a `<ol>` list which has a max width of 16rem per column created depending on the number of links.  This rule tries to "even out" the columns with the number of links.  We can move to a more rigid grid layout for this if we deem necessary.

```
aside ol {
    columns: 16rem auto;
    list-style: none;
    padding: 0;
}
```

**Comment by marionnegp** [comment]
@zeroedin, that sounds fine with me.
