### ISSUE TITLE
[feat] Discovery on Jump Links

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1434]
Discovery work on whether a Jump Links pattern outside of layout/grid is better than a static Table of Contents at top of a page (coupled with a back to top).

Will potentially impact [RH Jump Links element](https://github.com/RedHat-UX/red-hat-design-system/issues/539) as well as usage within our docs.

**Comment by markcaron** [comment]
Related to #1465

**Comment by coreyvickery** [comment]
@zeroedin @markcaron Maybe we answered this yesterday, but is the end goal to have two sets of styles?

The ToC has one set and `rh-jump-links` has another. The ToC might be a ux dot only thing, which is fine with me, but are we proposing that the ToC change to `rh-jump-links` on ux dot?
