### ISSUE TITLE
[docs] Add GitHub repo link in Nav/Header

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1440]
Add a GitHub repo link to the Side Nav -or- the Header Bar for quick access.

- [x] Design it up
- [x] Dev it up

**Comment by coreyvickery** [comment]
Issue with preview is [here](https://github.com/RedHat-UX/red-hat-design-system/pull/1465).

@zeroedin Can I provide you with my design edits in this issue?

**Comment by markcaron** [comment]
Handled in #1465
