### ISSUE TITLE
[docs] Create a Help (or Support) page

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1443]
We need a Help page for our users to

- Submit feedback — [Issue 120](https://github.com/RedHat-UX/red-hat-design-system/issues/120)
- File a bug
- Request a feature / component
- Chat with us in Slack
- Etc.

Make this a top-level nav item. (Maybe below "Release notes.")

[Figma mockup](https://www.figma.com/proto/s2jasqNAZ2LljpbbmfEPog/Support?node-id=335-686&t=izZWPVt8onYGs1iE-1) (Here it is in [Dev mode](https://www.figma.com/design/s2jasqNAZ2LljpbbmfEPog/Support?m=dev&node-id=335-686&t=Bw8sOAXoIbyqKPc5-1) if that's available to you.)

**Comment by marionnegp** [comment]
Here's a [mockup](https://www.figma.com/proto/s2jasqNAZ2LljpbbmfEPog/Support?node-id=335-686&t=izZWPVt8onYGs1iE-1) for the page. Content or design feedback is appreciated.

**Comment by marionnegp** [comment]
@markcaron, I added links to the mockup at the top of this issue!
