### ISSUE TITLE
[docs] About this Site page improvements

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1446]
Update/improve the About this Site pages where needed:

- [x] About this Site
- [x] How We Build
- [x] Roadmap

Seems like some of the content might be a little out of date or need a refresh.

**Comment by marionnegp** [comment]
@markcaron @coreyvickery, after removing some content on the "How we build" page that was out-of-date, it felt like the content of the "How we build" and "About the design system" pages could be combined. What do you think about the content in [this mockup](https://www.figma.com/proto/fmXhKUuKAgX2ZPz6UddywP/About---About-the-design-system?node-id=0-1&t=yakXy8PCvz1Wh2H7-1)? Do we need to add back in info about Drupal?
