### ISSUE TITLE
[docs] Make Installation / CDN tabs look nicer on Elements' Code pages

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1450]
Improve the look of the Installation/CDN tabs at the top of the Elements' Code pages. We'll need a different visual solution than the vertical tabs on the left.

- [ ] Design new tabs / display concept
- [ ] Dev _(may need new issue to track solution in later release)_

### Current situation

<img width="558" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/7b1da347-efa4-4b4d-a0bf-27d177f97cbc">

Awkward left side visual alignment. Makes it feel clunky.

<img width="537" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/32cf31b2-eb85-4fe3-8ab8-324fd95d0355">

### Potential tab variant?

Pill group

<img width="257" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/33671b23-f786-481b-b22b-b3bc54aff371">

**Comment by markcaron** [comment]
Discussed in standup today that we could easily begin this with a `uxdot` component, making this a good first issue.

**Comment by bennypowers** [comment]
#1690

**Comment by markcaron** [comment]
Moving to Clefairy release

**Comment by bennypowers** [comment]
Closed by #1690, we can always iterate in _new issues_ for cubone
