### ISSUE TITLE
[docs] View full demo link

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1451]
Improve the look on the view full demo link below our playground.

### Current
<img width="458" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/1ce5c093-0925-4b08-9eea-d88c78c94d79">

**Comment by zeroedin** [comment]
Stopgap change: add a unordered list to access all the demos for a specific element.

**Comment by bennypowers** [comment]
let's get to this after #1465
