### ISSUE TITLE
[bug] `<rh-table>` --rh-table-background-color not working

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#1454]
### Describe the bug

Setting `--rh-table-background-color` has no effect. the property is actively set in the lighdom stylesheet. if we want it to be customizable, it should be documented and use fallbacks

as well, it does not appear in the cem docs

### Which Component?

rh-table

### Steps to reproduce

1. add an rh table with content 
2. add this css
  ```css
  :root {
  --rh-table-background-color: red;
  }
  ```
3. hover a row

### Expected behaviour

bg is red

### Operating System (OS)

Linux

**Comment by zeroedin** [comment]
`--rh-table-background-color` does not exist `lightdom.css` are you referring to `--rh-table-row-background-color` and `--rh-table-column-background-color` and `--rh-table-row-border` ?

That said, those values should also be set as _private and moved to a failover calls:

`_row-background-color: var(--rh-table-row-background-color,  ...);`

Then both should also be added to the cem docs as stated.
