### ISSUE TITLE
[feat] `<rh-pagination>`: element updates and new pattern

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1457]
### Description

Feedback on current element:
- The current design looks heavy and too large on some pages, like Portal and Catalog.
- There should be an option for stacking the compact pagination with the "Go to page" input like in the screenshot below.
![Screenshot 2024-01-23 at 1 48 33 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/a2239190-c88f-4753-8a9a-878bf0d9bb64)
- There's also a need for the dropdown menu with options for changing the number of results per page. This is available in PatternFly.
<img width="438" alt="Screenshot 2024-01-23 at 1 46 25 PM" src="https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/10f930ec-324e-45ef-9977-a4a706d6740c">

### Suggested solution

I'm proposing adjustments to the light theme colors, size adjustments, a compact variant, and a pagination + item per page selector. ([Figma link](https://www.figma.com/file/BVTQ5Fim2mLfstNGeZN1Qc/Pagination?type=design&node-id=0%3A1&mode=design&t=mTimrsdl2tizInMQ-1))

**Comment by marionnegp** [comment]
@hellogreg @markcaron, should this go in Chansey or Charmander?

**Comment by coreyvickery** [comment]
@markcaron @hellogreg I also would like to get this done in `Charmander`.

@zeroedin Could we also fold in [1393](https://github.com/RedHat-UX/red-hat-design-system/issues/1393) here too?

**Comment by adamjohnson** [comment]
Looks like the color adjustments to the light theme were handled in #1393 (#1552).

I will look into implementing the `open`, `size` (small), and `compact` variants.

Should "Pagination + items per page selector" [use `<pf-dropdown>`](https://patternflyelements.org/components/dropdown/) or [wait for `<rh-dropdown>`](https://github.com/RedHat-UX/red-hat-design-system/issues/425)?

**Comment by coreyvickery** [comment]
@adamjohnson Can we convert `pf-dropdown` (PF5) to `rh-dropdown` quickly? I think the styles are exactly the same.

cc @markcaron @zeroedin

**Comment by adamjohnson** [comment]
I'm going to defer to @markcaron and @zeroedin's experience on this question from Corey:

> Can we convert pf-dropdown (PF5) to rh-dropdown quickly? I think the styles are exactly the same.
