### ISSUE TITLE
[bug] <rh-blockquote>: highlight border color

### ISSUE THREAD

**Issue by eyevana** [RedHat-UX/red-hat-design-system#1480]
### Describe the bug

The border color for the highlighted variant of `rh-blockquote` defaulting to #43adaf.

### Which Component?

rh-blockquote

### Steps to reproduce

https://codesandbox.io/p/sandbox/goofy-torvalds-hvgymq?file=%2Findex.html%3A17%2C50

### Expected behaviour

The highlight should be #ee0000.

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by bennypowers** [comment]
Clefairy fixes this.
