### ISSUE TITLE
[bug] <rh-tabs>: nested tabs uses parent tabs variant

### ISSUE THREAD

**Issue by eyevana** [RedHat-UX/red-hat-design-system#1481]
### Describe the bug

I'm trying to use tabs within tabs in a React app. The parent tabs is using the box="inset" variant, and I want the inner tabs to use the default variant. However, the inner tabs uses the default variant for its first tab, but every other tab uses box="inset".

### Which Component?

rh-tabs

### Steps to reproduce

https://codesandbox.io/p/devbox/elegant-shape-l6jj7t

### Expected behaviour

All tabs in the nested tabs should use the default variant if none other specified.

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by zeroedin** [comment]
Closed by implementation of pfe/aria-tabs-controller
