### ISSUE TITLE
[docs] CDN doc URLs are static and do not reflect current version

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1484]
The URLs shown in the CDN are static and do not reflect current package version.

We need to make them reflect the most recent version available on the CDN (not necessarily aligned with latest RHDS version).

<img width="1049" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/42d59a6b-3af1-4c13-95ba-1958aef3701b">

And for Light DOM:

<img width="1017" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/389c0098-432e-49c7-bd4e-f304fb95c5d4">

**Comment by markcaron** [comment]
Good first issue. If you're picking this up, see me with questions.

**Comment by bennypowers** [comment]
see #1690

**Comment by bennypowers** [comment]
closed by #1690
