### ISSUE TITLE
[docs] Add RHDS version number to docs masthead

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1485]
Once we get the GitHub logo in the masthead, we should consider adding the most recent version available (that's supported by docs) to the masthead.

Perhaps this could go on the far right like:
<img width="1050" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/10e553a4-63e9-4ba1-837f-ebf28da7ca2f">

At a later date, we can convert this to a dropdown when we're needed to support other versions.

Related (GitHub logo in masthead): https://github.com/RedHat-UX/red-hat-design-system/pull/1465

**Comment by coreyvickery** [comment]
@zeroedin Equidistant spacing in between text and icon (`16px`) and then we're good.
