### ISSUE TITLE
A uri de CND não está funcionando, está bloqueada... Ontem estava funcionando normalmente!

### ISSUE THREAD

**Issue by vitorcelio** [RedHat-UX/red-hat-design-system#1491]
### Describe the bug

Erro: Access to script at 'https://www.redhatstatic.com/dx/v1-alpha/@rhds/elements@1.1.0/elements/rh-audio-player/rh-audio-player.js' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Which Component?

rh-audio-player

### Steps to reproduce

...

### Expected behaviour

...

### Element HTML

```HTML
rh-audio-player
```

### Operating System (OS)

Windows

### Browser

Microsoft Edge

### More browser information

...

### Additional Info

...

**Comment by vitorcelio** [comment]
Voltou a funcionar! Trocaram as URIs

**Comment by bennypowers** [comment]
Thanks for the issue. the Red Hat Static for RHDS is not yet ready for production use. As of now, the plan is that sites wishing to use the RHDS CDN paths will have to request permission and be added to an allowlist.
