### ISSUE TITLE
[bug] headings in <rh-card> are incorrectly using RH Text

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1497]
### Describe the bug

The font family of any heading used in `<rh-card>` is changed to Red Hat Text. It should be Red Hat Display.

### Which Component?

rh-card

### Steps to reproduce

Go to any card demo and check the font family in the inspect tool. Try adding any heading tag in any slot.

### Expected behaviour

Headings should use Red Hat Display.

### Operating System (OS)

macOS

### Additional Info

I think it’s because slotted items inherit the font family of `rh-card`’s `#container`, which uses RH Text.
![Screenshot 2024-03-07 at 2 52 19 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/6e80df86-affb-4e03-9afd-c568f20c79d6)

**Comment by zeroedin** [comment]
Just as a follow up to this, we suggested `rh-card::part(header) { font-family: ... }` to fix the issue from lightdom for now.  Should have a discussion on overall consistency across components on font setting and ensure its the same experience across the board.

**Comment by brianferry** [comment]
@marionnegp @zeroedin is this being rolled up into a bigger task or is this available?
