### ISSUE TITLE
[bug] `rh-audio-player`: Keyboard focus not returned to "More options" button on menu close

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#1512]
Currently, when the audio player's "More options" menu is opened and closed via keyboard, focus doesn't return to the menu button. It _did_ do so at the time of launch (verified in the original deploy preview), so something has changed since then.

Not sure if this is affecting any other elements in the system.

Issue occurs in all tested desktop browsers.

To reproduce:

1) Go to the [audio player demo page](https://ux.redhat.com/elements/audio-player/demo/).

2) Tab through the interactive elements until the "More options" menu button has focus.
<img width="228" alt="More options button with focus" src="https://github.com/RedHat-UX/red-hat-design-system/assets/642695/3755272f-02b7-4d75-9509-7645b52c4c11">

3) Open the menu (via space or enter).
<img width="284" alt="More options menu is expanded" src="https://github.com/RedHat-UX/red-hat-design-system/assets/642695/800f5e49-00a4-4d41-a684-a9f55e534736">

4) Close the menu via the escape key. Focus should be returned to the button, but currently is not.
<img width="262" alt="More options button has no visible focus on collapse" src="https://github.com/RedHat-UX/red-hat-design-system/assets/642695/a70bc4bd-6603-4d56-a71a-55983ae55545">

**Comment by bennypowers** [comment]
fixed on https://deploy-preview-1802--red-hat-design-system.netlify.app/elements/audio-player/demo/

open a new issue for cubone if this still persists
