### ISSUE TITLE
[bug] CTA on dark theme

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#1519]
### Describe the bug

https://ux.redhat.com/elements/tabs/demo/color-context/
see the CTA on the database tab on a dark theme. background colour does not seem correct to me.

### Which Component?

rh-cta

### Steps to reproduce

see demo link above
click on database tab
switch to a dark theme
observer cta background colour

### Expected behaviour

bg is transparent

### Screenshots

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/1466420/31083090-4472-4085-9c06-3057bafc96e5)

### Operating System (OS)

Linux

### Browser

Firefox

**Comment by zeroedin** [comment]
This doesn't appear to be an issue on [current docs](https://ux.redhat.com/elements/tabs/demo/color-context/) 

Also to note the focus style will be fixed in https://github.com/RedHat-UX/red-hat-design-system/pull/1538

**Comment by zeroedin** [comment]
Looks like there is a `rh-context-provider` in that panel that was missed during the `rh-context-provider` -> `rh-surface` transition.  I'll can remove it.  I don't think we would want someone combining a dark tab and a light panel thoughts @coreyvickery @marionnegp?

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/a984987b-eb93-45fb-a3b8-5fc9f051202b)

If we allow mixing: 

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/5ea6503b-dcb6-4a4a-9a3d-10166086e7c8)

**Comment by bennypowers** [comment]
Appears to be resolved
