### ISSUE TITLE
[docs] `<rh-tag>` variants are documented confusingly with `unfilled` vs `outline`

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1525]
Variants for `<rh-tag>` are documented confusingly...

The [Variants section under Style](https://ux.redhat.com/elements/tag/style/#variants) has `unfilled`:

<img width="1059" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/400cc8bc-61d5-4894-a066-3db3cfb91f3c">

The [Variants section under Code](https://ux.redhat.com/elements/tag/code/#attributes) has `outline`:

<img width="1058" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/150ba21e-c5da-4e84-bf72-31157c6b9b42">

### Related

The `outline` variant is not `unfilled`. It's actually filled with white—which is misleading.

**Comment by bennypowers** [comment]
Note that the element's `variant` attribute accepts one of two values: `filled` or `outline`. docs should reflect the HTML apis in all cases

**Comment by bennypowers** [comment]
I did a partial job of this on #1853 , but the graphics with overlays need some attention from design

**Comment by coreyvickery** [comment]
Update 9/17: Revised docs are about 50% done.

**Comment by coreyvickery** [comment]
@marionnegp @gradymcgee [Updated docs](https://www.figma.com/proto/4R0KVvfgt5p5efFRhyZQVq/Element---Tag?page-id=2074%3A1263&node-id=2074-1264&node-type=canvas&viewport=133%2C163%2C1&t=mgxhUs5HrV3pXka4-1&scaling=scale-down&content-scaling=fixed) are ready to be coded.

@markcaron If Marionne or Grady can't do it this week, maybe Diwanshi or Ivana?
