### ISSUE TITLE
[docs] Add color guidance on using brand red text over gray backgrounds

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#1568]
Currently at www.redhat.com, there are several instances of using our brand red (#ee0000, aka --rh-color-accent-brand-on-light) against light gray (#f2f2f2, aka --rh-color-gray-10).

One example is at our 404 page, where this 20px, non-bold "Status 404:" is red against a gray background.

![Screenshot of the redhat.com 404 page](https://github.com/RedHat-UX/red-hat-design-system/assets/642695/45454803-41e9-415c-ac09-0621749fb15d)

For smaller text sizes (<24px non-bold or <19px bold), this [does not meet contrast requirements](https://webaim.org/resources/contrastchecker/?fcolor=EE0000&bcolor=F2F2F2). Either the red needs to be against pure white (#ffffff) or the red should be changed to another color.

Can we provide some guidance on this at ux dot, so that designers can be aware of this and avoid the issue in the future?

**Comment by coreyvickery** [comment]
6/18 update.

[Figma proto link](https://www.figma.com/proto/ehnLuOYqK8zZyCfVeMmdzV/Foundations?page-id=621%3A3607&node-id=621-3608&viewport=205%2C105%2C1&t=OfmgJcO9xWvZOaAM-1&scaling=min-zoom&content-scaling=fixed)

- Greg approved
- Marionne and Grady will be coding
