### ISSUE TITLE
[bug] <rh-tooltip> is not appearing on red hat product trial center (ptc)

### ISSUE THREAD

**Issue by brianferry** [RedHat-UX/red-hat-design-system#1579]
### Describe the bug

https://www.redhat.com/en/products/trials

On this URL we have a tooltip next to the authentication button.  

<img width="1158" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/9708152/bcd30ea5-5480-477d-b731-fef56b06f1a3">

(This is the authenticated button, it has different text if you're not logged in).

On Chrome this tooltip is not working on hover.

Upon further research, it appears that the issue is down to the following CSS

`:not(.initialized) #tooltip`

Removing this style fixes the problem.  

It is not especially clear when this problem came up though I saw it as early as last week but I was the only one seeing it at that time.  

### Which Component?

rh-tooltip

### Steps to reproduce

1. Go to https://www.redhat.com/en/products/trials
2. Scroll down to the header for the product trial center
3. Hover over the tooltip next to the view my trials button 

### Expected behaviour

The tooltip should appear as it does on https://ux.redhat.com/elements/tooltip/demo/

### Screenshots

<img width="1158" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/9708152/bcd30ea5-5480-477d-b731-fef56b06f1a3">

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by bennypowers** [comment]
this is a problem in chrome

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/1466420/bc2ac0eb-dec6-4138-a2cd-444e02fcf4d0)
![Screenshot from 2024-05-30 09-24-16](https://github.com/RedHat-UX/red-hat-design-system/assets/1466420/b84e7f8c-f2c5-4e5e-a161-1e2c1a8c6acf)

**Comment by bennypowers** [comment]
I think you found a chrome rendering bug. regardless, we can probably work around this by inverting the sense of those selectors

**Comment by bennypowers** [comment]
https://github.com/RedHat-UX/red-hat-design-system/blame/bf0f15b1fa0f659c677d9b4f043393b50b71e028/elements/rh-tooltip/rh-tooltip.css#L79-L80

this is already fixed: update to 1.4.2
