### ISSUE TITLE
[bug] `<rh-tabs>` per axeDevTools: Interactive controls must not be nested

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1585]
@rmscampos is getting the following issue on the `<rh-tabs>` [demo](https://ux.redhat.com/elements/tabs/demo/):

```Interactive controls must not be nested```

**Screenshot:**
<img width="1619" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/043c4ccd-7ac0-4767-bae9-6818aebf05f5">

**Comment by zeroedin** [comment]
https://github.com/patternfly/patternfly-elements/pull/2699/files#diff-1d0319a031552639d70efc2c90dca7fa5994954f5bef1bb1543962598515f53cL106-R129

We had made this fix upsteam, I think we forgot to bring it downstream.  Will open a PR to get this fixed.
