### ISSUE TITLE
[bug] <rh-tile> using wrong font size for headings

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1591]
### Describe the bug

The tile demo on its docs [Overview page](https://ux.redhat.com/elements/tile/) is showing an `<h2>` with a 28px font size because the font size is coming from `typography.css`. The element should define the heading size.

### Which Component?

rh-tile

### Steps to reproduce

Visit demo on [Tile's Overview page](https://ux.redhat.com/elements/tile/)

### Expected behaviour

Heading for tile should be:
- 20px for link tile at default size
- 18px for link tile at compact size
- 18px for selectable tiles

### Operating System (OS)

macOS

**Comment by markcaron** [comment]
@marionnegp I think quite a bit of the `font-sizes` are off or at least left open to inheriting the `1rem` / `16px` body text from `<rh-tile>`.

The default slot `font-size` is `16px`, which seems like it should be `18px` in the specs.
