### ISSUE TITLE
[docs] `<uxdot-sidenav>` Keyboard focus issues

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#1596]
Keyboard tab focus is skipping past (or cycling through) most (but not always all) collapsed sidenav items at [UX dot's docs DP](https://deploy-preview-1465--red-hat-design-system.netlify.app/).

Tabbing through the page, there are several different focus order issues that can occur.

1. When all sidenav items are collapsed after a reload, tab focus can only go on the sidenav's Home link and then to the main content--and not any of the other sidenav expander buttons. (In other words, it's 100% RTI)
2. If some sidenav items are expanded, tab focus can go to the items within those expanded items, then to one or more (but not all) adjacent sidenav item expander buttons, and then to the main content. (Mix of tab and RTI)
3. If some sidenav items were expanded, but then collapsed, focus can still go to some (but not all) of the expander buttons. (Mix of tab and RTI, but only expecting RTI)

This issue occurs in all browsers.

_Edit: I've realized part of the issue stems from my expectations, which I wasn't clear about. Sidenav is (like secondary nav) a blend of arrow/RTI (top level) and tab (next level) focus--and I expected one or the other throughout. Honestly, I think tab makes more sense than RTI, but I reserve the right to re-think that!_

_Adding to this the tab order bug (where tab can jump from the last secondary list item to an unexpected top level item), and it still is worth addressing/discussing._

[Video of all these things happening!](https://drive.google.com/file/d/1h6jX4ChTqgfpjIrieC5bN2h4tKVM-6oz/view?usp=sharing)

**Comment by hellogreg** [comment]
My initial goal in posting this issue was just consistency (either tabs or roving tabindex). After a day or two to think on it, it's harder for me to make a case at all for RTI. Long term, I think tabbing is the way to go. And I think this may apply to secondary nav, too. (I understand why we explored RTI, but I think tabbing is more predictable for users.)

**Comment by hellogreg** [comment]
@zeroedin How about if I close this and we reopen for discussion elsewhere? You addressed the consistency issue already. And since this may affect other navs, this issue may not be the right place.

**Comment by zeroedin** [comment]
sounds good to me
