### ISSUE TITLE
[docs] Get started - overview: design tweaks

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1598]
- [ ] Fix the white corners in the image when tile is hovered over. Do we want to use tile here?
![Screenshot 2024-06-10 at 12 47 19 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/b6c4d33e-16c7-4f35-b45f-c147978f3075)
- [x] Fix 404s to Designer and Developer pages
- [x] Should have 80px between tiles and Release notes/Feedback row. Spacing is too small right now:
![Screenshot 2024-06-10 at 12 47 19 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/4e7bcae6-d6ef-4530-86e0-60dabe1aeabe)

**Comment by zeroedin** [comment]
Good eye on those white corners!

I'll open a PR.  

@marionnegp Those images are pngs.  Do we have access to SVG for those?  Prefer SVG's for as many of these style files as possible.

**Comment by zeroedin** [comment]
> Do we want to use tile here?

I used tile as it seemed more appropriate as far as a pattern then cards used in a nav.

If we had more overview content on this page I would say these pages could become a subnav instead.
