### ISSUE TITLE
[docs] fix spacing

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1602]
- [ ] Spacing between headings and `<uxdot-example>`, sample element, status table, and status checklist should be `--rh-space-lg`

- [x] Spacing between any content and the footer should be `--rh-space-5xl` for all pages. Currently looks like there's extra space below the Related elements/Feedback rows.

![Screenshot 2024-06-10 at 12 51 41 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/ea49e85a-5940-4771-b337-2cc947e4c005)

- [x] Spacing between two headings should be `--rh-space-2xl`. I'm seeing no space between headings on token pages:
![Screenshot 2024-06-10 at 12 51 28 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/2ece18af-540b-4226-adea-f099f37e263f)

- added a spacing edit to #1598, which is in progress already

- [x] Spacing in the homepage cards is a bit off. Seeing too much between the image and the heading. Margins are also getting added to `<p>`. Feel free to tackle this in a separate issue or PR if this is something that needs to be fixed in `<rh-card>`.
<img width="490" alt="Screenshot 2024-06-11 at 10 40 01 AM" src="https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/a7a6f05d-8e4f-45f5-81b6-0def0d4b98ac">
<img width="491" alt="Screenshot 2024-06-11 at 10 39 55 AM" src="https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/b685b45d-6b20-4111-bfcf-6cb7a44cb36a">

@coreyvickery, any more spacing fixes to add?

**Comment by zeroedin** [comment]
👍  tokens pages have some weird additional html wrapping between the headings.

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/8a38c282-518f-4744-8d36-8a2c2e485fcf)

Will have to account for this maybe on specific page styles since this combo doesn't exist anywhere else.

**Comment by bennypowers** [comment]
see https://github.com/orgs/RedHat-UX/discussions/1606

**Comment by zeroedin** [comment]
> Spacing between any content and the footer should be --rh-space-5xl for all pages. Currently looks like there's extra space below the Related elements/Feedback rows.

This one should be resolved in: https://github.com/RedHat-UX/red-hat-design-system/pull/1600/commits/13835a5ad16184717a0254b4275caed7c28480ef on PR #1600

**Comment by zeroedin** [comment]
> Spacing in the homepage cards is a bit off. 

Marked this one off as completed as we converted from `rh-card` to `rh-tile` in https://github.com/RedHat-UX/red-hat-design-system/pull/1601
