### ISSUE TITLE
[bug] `<rh-accordion>`  lightdom css margin/padding wont apply

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1609]
Because `<rh-accordion>` shadowRoot  `#container` is `display: contents`, setting a margin or padding on this element won't apply when trying to provide spacing between elements for page content flow.  I suggest adding a `display: block` to the `:host` in shadow CSS.

Attached is an image of the accordion and header element with no spacing.  In order to provide spacing here it would be preferable to do a combo selector between a header and a sibling accordion:

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/7f2fed3a-2e73-4fbb-a02d-73ae207fc417)

Somewhat related to @bennypowers [discussion on table accordion](https://github.com/orgs/RedHat-UX/discussions/1606) , or  is at least is what brought me to think about the spacing between the header/accordion on the element code pages.

**Comment by zeroedin** [comment]
Related to #1602

**Comment by bennypowers** [comment]
I believe this was resolved. Please open a *new* issue if that's not the case
