### ISSUE TITLE
docs: typography scale table content

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1612]
Tables are currently empty and needs content or possibly removed.

https://ux.redhat.com/foundations/typography/#scale

Determine what to do about these tables, remove, link to tokens?

**Comment by markcaron** [comment]
I think it's helpful (especially for designers) to have a Typography table like we had. The tokens page may or may not be a bit more overwhelming for some.

Let's make the table run off the tokens.

**Comment by coreyvickery** [comment]
6/18 update.

[Figma proto link](https://www.figma.com/proto/ehnLuOYqK8zZyCfVeMmdzV/Foundations?page-id=615%3A1236&node-id=615-1240&viewport=127%2C149%2C1&t=UmUdfkSHt4RyCk95-1&scaling=scale-down&content-scaling=fixed)

- Stop gap until DPO alignment
- Marionne and Grady will be coding

**Comment by marionnegp** [comment]
I've started a `docs/typography-page-update` branch for this. I'll work on getting the subnav and some blank pages dded abefore we start coding the content.
