### ISSUE TITLE
[bug] RHDS Site Status component has a visual bug on medium breakpoints 

### ISSUE THREAD

**Issue by kelsS** [RedHat-UX/red-hat-design-system#1614]
### Describe the bug

RHDS Status Widget has a hard coded min-width value that is causing the element to show up incorrectly at medium breakpoints

### Which Component?

rh-site-status

### Steps to reproduce

The rh-site-status component in the footer of access.redhat.com is not live yet. The live footer is using the old hard coded status widget.

I am able to reproduce this issue by:

1. Cloning the Primer repo locally
2. Adding the import statement at the end of body in the root `index.html` file
3. Adding the `<rh-site-status>` component to the `footer` within the `ul#status-widget__desktop li`
4. Then change the browser window dimensions to 1165 x 719
5. Observe the wonky text in the rh-site-status component

## Possible fix
I found that changing the `min-wdth` of the `.container` within the shadow root from the hard coded value `150px` to the value `max-content` which resolves the issue. I also think setting the value to max content instead of a specific px value is more robust and responsive.

### Expected behaviour

For the text to not break to two lines at this breakpoint

## With min-width set to 150px
![Screenshot 2024-06-12 at 7 28 47 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/20908392/ace98fb7-554c-4914-bd86-1b256a17cec6)

## With min-width set to max-content
![Screenshot 2024-06-12 at 7 29 26 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/20908392/99eb0d1a-02ba-4343-a910-fb00df03f870)

### Element HTML

```HTML
<rh-site-status></rh-site-status>
```

### Operating System (OS)

macOS

### Browser

Chrome

### More browser information

Chrome 125
Mac OS (Sonoma)

**Comment by kelsS** [comment]
The local dev url is https://prod.foo.redhat.com:1337/services/primer/example/

**Comment by kelsS** [comment]
We are using v1.4.1 of rhds in Primer

**Comment by kelsS** [comment]
If anyone needs help getting Primer setup to reproduce the issue. Please reach out to me. The README that is in main for Primer is slightly outdated and the updated README is being worked on but not live yet.

**Comment by zeroedin** [comment]
@kelsS I believe the issue he is less about the `<rh-site-status>` and more about where it is placed inside of `<rh-footer>`.

In looking into this issue today, I recognized that we never offered a demo of the correct implementation details for this pattern and how it composes with `rh-footer`.  

So right now you are correct there really isn't a good way of doing this in footer currently without overriding a whole lot more then we should have to giving rise to the issues you have outlined above.

Above this comment is a link referencing an issue I opened on `rh-footer` itself as well as an attached PR with that issues [implementation](https://github.com/RedHat-UX/red-hat-design-system/pull/1622).   Given that this PR doesn't resolve your "right now" issue, and If you are unable to wait until the next release of RHDS, let me know and I can come up with a short term workable pattern for you.

**Comment by kelsS** [comment]
Hi @zeroedin! That is helpful info. But alas, I cannot wait for the next release because this is blocking a high priority ticket I must complete by the end of this sprint. I would love to see what work around I can use for now and I will create a jira ticket to update the component to the newest release once it is ready.

**Comment by zeroedin** [comment]
Ok I'll get to work on a temporary work around.

**Comment by zeroedin** [comment]
@kelsS here is a codepen with how I would implement this until we can get a dedicated slot in to handle site status.  This unfortunately hides the actual site status in the accordion on mobile, but most likely the best we can do given current circumstances. 

https://codepen.io/zeroedin/pen/bGyYoGw

 @heyMP any additional thoughts on this?

**Comment by kelsS** [comment]
Hey @zeroedin I do not think I can put the site status in an accordion since that is a major design change :/

**Comment by kelsS** [comment]
@zeroedin is there a way I can override the min width style and set it to max-content temporarily?

**Comment by zeroedin** [comment]
@kelsS curious what does your implementation look like at a mobile width viewport?  It was my understanding if slotted into `slot=links` it would get lifted and shifted into an accordion.

**Comment by zeroedin** [comment]
@kelsS after a bit more thought and playing around you might find this solution more agreeable:

https://codepen.io/zeroedin/pen/rNgYgJq

This one places the site-status in the universal slot then provides a background to match the main footer background.

**Comment by kelsS** [comment]
@zeroedin that works great for now! TY! 😄

**Comment by zeroedin** [comment]
Refernce https://github.com/RedHat-UX/red-hat-design-system/pull/1622
