### ISSUE TITLE
[bug] RHDS site status component icon is missing the white checkmark

### ISSUE THREAD

**Issue by kelsS** [RedHat-UX/red-hat-design-system#1615]
### Describe the bug

When the component loads the icon is only showing a green circle and no checkmark. I noticed when looking in the shadow root that the path in the svg is nested within another path but on the rhds site the paths are siblings not nested and the icon is correct. I have no idea why the paths are getting nested.

### Which Component?

rh-site-status

### Steps to reproduce

The rh-site-status component in the footer of access.redhat.com is not live yet. The live footer is using the old hard coded status widget.

I am able to reproduce this issue by:

1. Cloning the Primer repo locally
2. Adding the import statement at the end of body in the root index.html file
3. Adding the <rh-site-status> component to the footer within the ul#status-widget__desktop li
4. Go to the project local url: https://prod.foo.redhat.com:1337/services/primer/example/ 
5. Scroll to the footer
6. Observe that the icon is only a green circle instead of a green circle with the checkmark.

Here is the svg that is getting loaded into Primer
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="17" viewBox="0 0 16 17" fill="none">
  <!--?lit$837365295$-->
  <path d="M8 16.5C12.4183 16.5 16 12.9183 16 8.5C16 4.08172 12.4183 0.5 8 0.5C3.58172 0.5 0 4.08172 0 8.5C0 12.9183 3.58172 16.5 8 16.5Z" fill="#63993D">
     <path d="M6.89999 12.1C6.69999 12.1 6.49999 12 6.39999 11.9L3.49999 9.00001C3.19999 8.70001 3.19999 8.30001 3.49999 8.00001C3.79999 7.70001 4.19999 7.70001 4.49999 8.00001L6.89999 10.4L11.5 5.80001C11.8 5.50001 12.2 5.50001 12.5 5.80001C12.8 6.10001 12.8 6.50001 12.5 6.80001L7.39999 11.9C7.19999 12 6.99999 12.1 6.89999 12.1Z" fill="white"></path>
   </path>
</svg>
```

Here is the svg getting loaded in the rhds demo
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="17" viewBox="0 0 16 17" fill="none"><!--?lit$774017727$-->
    <path d="M8 16.5C12.4183 16.5 16 12.9183 16 8.5C16 4.08172 12.4183 0.5 8 0.5C3.58172 0.5 0 4.08172 0 8.5C0 12.9183 3.58172 16.5 8 16.5Z" fill="#63993D"></path>
    <path d="M6.89999 12.1C6.69999 12.1 6.49999 12 6.39999 11.9L3.49999 9.00001C3.19999 8.70001 3.19999 8.30001 3.49999 8.00001C3.79999 7.70001 4.19999 7.70001 4.49999 8.00001L6.89999 10.4L11.5 5.80001C11.8 5.50001 12.2 5.50001 12.5 5.80001C12.8 6.10001 12.8 6.50001 12.5 6.80001L7.39999 11.9C7.19999 12 6.99999 12.1 6.89999 12.1Z" fill="white"></path>
</svg>
```

For some reason the one being loaded on Primer has the path nested inside of the other one instead of two separate paths at the same level.

### Expected behaviour

The green circle loads with the white checkmark 

## Loading the component in Primer locally
![Screenshot 2024-06-12 at 7 59 53 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/20908392/3f202c59-d19c-400c-b6d8-8b6784a6df9c)

## Loading the component in the rhds demo
![Screenshot 2024-06-12 at 8 00 10 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/20908392/65cab503-d8eb-43bb-aa2d-160c7abbdd07)

### Element HTML

```HTML
<rh-site-status></rh-site-status>
```

### Operating System (OS)

macOS

### Browser

Chrome

### More browser information

Chrome 125
Mac OS (Sonoma)
RHDS v1.4.1

**Comment by kelsS** [comment]
If anyone needs help getting Primer setup to reproduce the issue. Please reach out to me. The README that is in main for Primer is slightly outdated and the updated README is being worked on but not live yet.

**Comment by zeroedin** [comment]
Based on a [diff check](https://www.diffchecker.com/Cw6VaTQx/) it appears there is a `</path>` close tag out of wack given the code snippets above:

https://www.diffchecker.com/Cw6VaTQx/

Given we use XML base tag closures in the code:

https://github.com/RedHat-UX/red-hat-design-system/blob/8eebce683d0cd6a9c79aa28779f2bf2ef54f3aa0/elements/rh-site-status/rh-site-status.ts#L71-L82

I wonder if something in Primer could be parsing that weird given the discrepancy in output.

I will attempt to install the Primer project locally and take a look.

**Comment by kelsS** [comment]
@zeroedin I am just now starting to really work on the Primer repo deeply so I am not fully familiar with how everything is parsed and works. However, I will dig through the Primer code to see if I see anything interfering with the svg parsing and get back to you!.
