### ISSUE TITLE
[bug]: `rh-footer` does not have a slot that currently supports `rh-site-status` 

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1620]
If you try and add `rh-site-status` to footer there is no simple way of doing so without overriding footer's CSS pretty dramatically. An optional additional slot in `rh-footer` would be preferable to easily compose `rh-site-status` inside of footer.

References #1614

**Comment by zeroedin** [comment]
```
<slot name="main">
  <div class="main-primary" part="main-primary">
    <slot name="main-primary">
      <div class="links" part="links">
        ${this.#renderLinksTemplate(this.#compact)}
      </div>
    </slot>
  </div>
  <div class="main-secondary" part="main-secondary">
    <slot name="main-secondary"></slot>
  </div>
</slot>
```

So we have `slot="main-primary"` and `slot="main-seocndary"`.  What I was thinking is adding `slot="main-footer"` or `slot="main-tertiary"` for naming consistency.

Graphically the layout being:
```
[ ------- main-primary  2/3 ------- ] [ main-secondary 1/3 ]
[ --------------  main-footer/teriary  3/3  -------------- ]
```

**Comment by markcaron** [comment]
@zeroedin I can dig the `main-tertiary` slot.

**Comment by zeroedin** [comment]
A temporary way to implement `rh-site-status` until a fix for this issue is published.

https://codepen.io/zeroedin/pen/bGyYoGw

**Comment by zeroedin** [comment]
@bennypowers had concerns about increasing the footprint of the API for footer as it is already fairly large which I understand completely.  

That said, currently we have some workarounds such as the codepen linked above.  @markcaron  Do we want to close this issue/PR and review at a later date if issues arise with said work arounds?

**Comment by bennypowers** [comment]
suggestion:
site-status needs javascript anyways, so let's just *print it in the shadow root* whenever some attribute like `<rh-footer status-domain="....">` is present on the host element
