### ISSUE TITLE
[bug] Incorrect text styling in `<rh-accordion-header> `

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1637]
### Describe the bug

It looks like the text in the accordion header is pulling font styles for buttons. 

![Screenshot 2024-06-18 at 9 21 14 AM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/f196e59c-b960-49e4-a5de-4b10d5a18cf3)

### Which Component?

rh-accordion

### Steps to reproduce

View an accordion on ux.redhat.com, like the ones on the [accordion's Code subpage](https://ux.redhat.com/elements/accordion/code/).

### Expected behaviour

The font size should be 18px (`--rh-font-size-body-text-lg`). Weight should be medium (`--rh-font-weight-body-text-medium`).

### Operating System (OS)

macOS

**Comment by bennypowers** [comment]
Closed in #1715
