### ISSUE TITLE
[feat] Create `<rh-icon>` element

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1657]
With [RH Icons updated](https://github.com/RedHat-UX/red-hat-icons/pull/5), we need to get `<rh-icon>` out the door as soon as possible.

I'm assuming the underlying code will be very much like [PF Icon](https://patternflyelements.org/components/icon/) if not identical, but using [RH Icon SVGs](https://red-hat-icons.netlify.app/).

**For example:**

`<rh-icon icon="acorn" icon-set="standard">`

### Sets

1. Standard (Default)
2. UI
3. Micron
4. Social

**Comment by marionnegp** [comment]
@markcaron @bennypowers, according to the [Brand site's info about icons](https://www.redhat.com/en/about/brand/standards/icons/standard-icons), icons shouldn't be any bigger than 100px. Our largest icon size token is 128px. Should we remove that icon size and have our largest icon size token be `96px`?

**Comment by marionnegp** [comment]
Updated icon set sizes from Brand:
- Standard icons = 24px - 100px (preferably 36px+)
- UI icons = 14px - 24px
- Microns = 8px - 12px

**Comment by marionnegp** [comment]
@coreyvickery @markcaron, could you take a look at the [docs for `<rh-icon>`](https://www.figma.com/proto/NrC6KxEdVcxSiFSl8r2ZLO/Element---Icon?page-id=0%3A1&node-id=1-2&viewport=704%2C336%2C0.25&t=i20kpY0MN9jGZMoJ-1&scaling=scale-down&content-scaling=fixed)? I added a couple comments that the code on the Accessibility subpage could change after development is done.
