### ISSUE TITLE
[bug] `<rh-card>` docs: guidelines page

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1662]
### Describe the bug

All of the  card variants look the same under the Guidelines subpage of the Card element docs.
![Screenshot 2024-06-25 at 12 15 56 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/3a6f96dc-0713-455c-a22d-9380fd0a4db5)

### Which Component?

rh-card

### Steps to reproduce

Visit the [Variants section](https://ux.redhat.com/elements/card/guidelines/#variants).

### Expected behaviour

Variants should look more like the variant demos: https://ux.redhat.com/elements/card/demo/variants/#. We might also want to add some lightdom CSS to make those card headings' font size 24px (`--rh-font-size-heading-sm`)..

### Operating System (OS)

macOS

**Comment by bennypowers** [comment]
#1188 will close this
