### ISSUE TITLE
[docs][bug] `<rh-tag>New</rh-tag>` looks bad in Design/code Status tables

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1667]
This might actually be an `<rh-tag>` bug, but the `New` tags on the [Design/code Status page](https://ux.redhat.com/design-code-status/) are awkwardly bulbous-looking. Seems like the `flexbox` property in the shadow CSS might be affecting how it displays in the table.

<img width="685" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/1890950/52e22ecb-bd90-43db-88fd-b3c769642729">

**Comment by zeroedin** [comment]
Closed in https://github.com/RedHat-UX/red-hat-design-system/pull/1669
