### ISSUE TITLE
[bug] `<rh-accordion-header>` using `heading-tag` attribute breaks header layout

### ISSUE THREAD

**Issue by rlahoda** [RedHat-UX/red-hat-design-system#1675]
### Describe the bug

When using `rh-accordion-header` the arrow is supposed to be at the far right of the container. However, if the `heading-tag` attribute is used, this breaks. 

This is what the heading should look like:
![Screenshot 2024-06-26 at 14-46-38 https __prod foo redhat com 1337](https://github.com/RedHat-UX/red-hat-design-system/assets/18124644/bda2aeb0-42a0-4116-8902-53371bbf79be)

This is what the heading looks like when the attribute is used:
![Screenshot 2024-06-26 at 14-46-27 https __prod foo redhat com 1337](https://github.com/RedHat-UX/red-hat-design-system/assets/18124644/1c9896e3-5079-4aa6-9e97-1468a217ab1b)

The code being used:
```
 <rh-accordion-header heading-tag="h2" expanded="true">
      <h2>Products</h2>
 </rh-accordion-header>
```

The code as it shows up in the inspector:
<img width="1204" alt="image" src="https://github.com/RedHat-UX/red-hat-design-system/assets/18124644/66abe0b6-9f46-4904-b4ca-56aeb23073bd">

### Steps to reproduce

1. Go to the rh-accordion demo
2. Inspect one of the demo accordions
3. Go to the `rh-accordion-header` inside one
4. Add `heading-tag="h2"` as an attribute
5. The arrow will move from the far right of the container to right next to the text

### Expected behaviour

The arrow shouldn't move

### Operating System (OS)

macOS

**Comment by bennypowers** [comment]
Should be addressed by #1715
