### ISSUE TITLE
[bug] `<rh-stat>` broken css selector in chrome

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1676]
### Describe the bug

View https://codepen.io/zeroedin/pen/zYQbJRr in Chrome version 126.0.6478.116 and 126.0.6478.127 (only versions tested so far) 

```
:not(.hasCta) #cta, :not(.hasIcon) #icon, :not(.hasStatistic) #statistic, :not(.hasTitle) #title {
    display: none;
}
```

The above selector does not function correctly in chrome and will ignore the `:not()` it appears and applies the `display: none` do to `#statistic`

Same selector appears to work in Firefox and Safari

```
div:not(.hasCta) #cta, div:not(.hasIcon) #icon, div:not(.hasStatistic) #statistic, div:not(.hasTitle) #title {
    display: none;
}
```
or 
```
:not(.hasCta) > #cta, :not(.hasIcon) > #icon, :not(.hasStatistic) > #statistic, :not(.hasTitle) > #title {
    display: none;
}
```

both work, the div obviously applies the div with not class, and  `>` applies the same with the direct parent being called for the id.

### Screenshots

![image](https://github.com/RedHat-UX/red-hat-design-system/assets/13666/7ffbad24-6049-451d-804b-d8d9270906ee)

### Steps to reproduce

https://codepen.io/zeroedin/pen/zYQbJRr

### Expected behaviour

The slotted stat to display

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by bennypowers** [comment]
Please reopen for cubone if it is still relevant
