### ISSUE TITLE
[bug] `rh-button` Devs need to be able to set the role attribute on rh-button

### ISSUE THREAD

**Issue by kelsS** [RedHat-UX/red-hat-design-system#1703]
## Description of the issue

Devs need to be able to set the role attribute on pf-button. For example, I am using pf-button as a tab control and I need to set the `role=tab` directly on pf-button in order to follow the proper design pattern for the carousel slider I am working on. 

Please see the following link for more info about the carousel design pattern
- https://www.w3.org/WAI/ARIA/apg/patterns/carousel/ 

### Impacted component(s)

- `rh-button` 
- https://github.com/RedHat-UX/red-hat-design-system/tree/main/elements/rh-button  

### Steps to reproduce

1. Open a Codepen in Chrome
2. Import rh-button into a pen
3. Try to add `role="tab"` to the rh-button
4. Inspect the devtools and observe that the role does not get added

### Expected behavior

The role attribute is added to the button in the shadow root with whatever the user needs the role to be, in my case "tab".

This is a sev-2 issue at least because this is causing a very inaccessible experience for [cp-slider](https://gitlab.cee.redhat.com/customer-platform/cp-elements/-/tree/2.0/elements/cp-slider?ref_type=heads) 

## Related Issue
- https://github.com/patternfly/patternfly-elements/issues/2805 

### Steps to reproduce

Please see description of the issue.

### Expected behaviour

Please see description of the issue.

### Element HTML

```HTML
<rh-button>
  button text
</rh-button>
```

### Operating System (OS)

Windows

### Browser

Chrome

**Comment by bennypowers** [comment]
This change in pfe could help here

https://github.com/patternfly/patternfly-elements/pull/2707

**Comment by kelsS** [comment]
@bennypowers I think I am just going to close this issue. I think the ultimate fix for the problem is to get a carousel slider component added into rhds which uses its own tabs buttons rather than having to add custom roles to rh-button.

**Comment by kelsS** [comment]
Also the change to pf-button solves the issue I am dealing with temporarily so I am unblocked.
