### ISSUE TITLE
[bug] fix generator script to properly stub out element docs

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1725]
Fix generator script to properly stub out element docs

I'm thinking this might require some tweaks upstream in @patternfly/elements 

/cc @alypilkons

**Comment by bennypowers** [comment]
https://github.com/patternfly/patternfly-elements/commit/5604adbfe6bbe5648f1bf8367b2ddf489583a9ff

**Comment by zeroedin** [comment]
Fixed upstream and brought in 2.0 release
