### ISSUE TITLE
[docs] Update the `Planned` status tag color

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1736]
### Description

It was suggested in #1734 by @zhawkins to update the tag color of `Planned` to purple, since the gray can be easily overlooked. Not that it needs to be purple (was just a suggestion), but wondering if it's worth looking into a different status color.

### Screenshots

![image](https://github.com/user-attachments/assets/13f6c144-4586-4d2e-b469-254c17bcf676)

**Comment by bennypowers** [comment]
[8d233e5](https://github.com/RedHat-UX/red-hat-design-system/commit/8d233e52690cbcdb173eab9dbaddbd22d6242f91) closes this
