### ISSUE TITLE
[docs] Link Card variants to their demos or pattern examples

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#1741]
### Description

On the [Card Guidelines "Variants" section](https://ux.redhat.com/elements/card/guidelines/#variants), we should link each card/tile to their respective demo or [pattern example](https://ux.redhat.com/patterns/card/examples/#icon-card).

### Screenshots

![image](https://github.com/user-attachments/assets/a99dc44e-a056-4785-9d1c-d5e531a7b191)

![image](https://github.com/user-attachments/assets/f3b5a647-2b8b-4897-92d9-0f3913acae1e)

**Comment by bennypowers** [comment]
cc @paceaux who recently mentioned this problem
