### ISSUE TITLE
[docs]: Token page duplicate ID's

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1742]
🐛 Little bug in the tokens pages.  Looks like we have a couple of places header id's duplicates:  [Icon's](https://ux.redhat.com/tokens/icon/) have two headers named "Icon" which will translate to a header id of id="icon" the 2nd header on that page should be "Color" I believe was maybe the intent.  The same thing happens on [Border](https://ux.redhat.com/tokens/border/) as well.

**Comment by bennypowers** [comment]
[a98a060](https://github.com/RedHat-UX/red-hat-design-system/commit/a98a06064d1cc73688f61acfe567b7b0fb249053) closes this
