### ISSUE TITLE
`<rh-cta>`: remove public cta getter

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1750]
Remove public cta getter

https://github.com/RedHat-UX/red-hat-design-system/blob/d983ce43c1b6d82510105fda42589116133165b1/elements/rh-cta/rh-cta.ts#L150-L164

Deprecated 2 months ago

Note: We will likely hold on to this one for a bit as it is a relatively new deprecation that hasn't been released yet.

**Comment by bennypowers** [comment]
IIRC we checked with the relevant parties and ensured that this isn't in use on pages likely to bring in 2.0. Let's do this for charmander, put it on my tab ;)
