### ISSUE TITLE
[docs] Add color palette to the Color page

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1757]
### Description

Our ["Color" page](https://ux.redhat.com/foundations/color/) doesn't actually show our color palette, and we'll need a way to display our colors in a less technical way than our "Tokens" page. 

Guidelines:
- Showing the crayon color token name (e.g., `gray-95` or `blue-50`) is better than showing only the hex code.
- Consider adding this to either the "Color: Overview" subpage or a new subpage.

Examples:
- [Brand's "Color" page](https://www.redhat.com/en/about/brand/standards/color)
- [PF6's "Color families" section](https://www.redhat.com/en/about/brand/standards/color)

**Comment by markcaron** [comment]
@gradymcgee I'd work on a mockup of what this type of "table" or display of colors could look like, and we can tap one of the devs to assist in automatically populating that table with the value from the tokens (so you don't have to code it manually).

**Comment by bennypowers** [comment]
I whipped up a PR for this at https://github.com/RedHat-UX/red-hat-design-system/pull/1866. Would it be faster to design in-browser on that PR?
