### ISSUE TITLE
[docs] Add info about promo variant of `<rh-card>`

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1818]
### Description

Need to add some info about the promo variant of `<rh-card>` on the Style and Guideline subpages. Currently the only promo info we have on ux.redhat.com appears under demos.

### Links

[Figma file](https://www.figma.com/design/sWD636GlCTJOTQrJb82cV0/Element---Card---Promo?node-id=1-3&t=aitoWXdT2qbB2X8M-1)

**Comment by marionnegp** [comment]
@markcaron @hellogreg, this can be kicked to Cubone if you want to focus on some of the docs bugs cropping up. I can make it a fast follow after Clefairy's release.

**Comment by bennypowers** [comment]
let's kick this. anyways we should do some deep design work on tokens -> elements -> theming -> patterns

**Comment by coreyvickery** [comment]
> Since the docs for promo variant are mixed in with card's, I'm only showing the sections that would be added to the page. @coreyvickery, would you be able to review [this mockup](https://www.figma.com/design/sWD636GlCTJOTQrJb82cV0/Element---Card---Promo?node-id=1-3&t=aitoWXdT2qbB2X8M-1) of some new images and sections for the promo variant?

@marionnegp Made some subtle edits and minor language changes.

**Comment by marionnegp** [comment]
Thanks, @coreyvickery! @adamjohnson, if you still have time to make these docs updates, the [Figma file](https://www.figma.com/design/sWD636GlCTJOTQrJb82cV0/Element---Card---Promo?node-id=1-3&t=aitoWXdT2qbB2X8M-1) is good to go. If not, I can work on it this week.

**Comment by adamjohnson** [comment]
I'll get these translated to code tomorrow. Thanks!
