### ISSUE TITLE
[feat] `<rh-tooltip>`: change the border-radius 

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1840]
### Description

`<rh-tooltip>` in our Figma library currently has slightly rounded corners, and it would be good to update the code for `<rh-tooltip>` to use `--rh-border-radius-default`. 

### Suggested solution

To dos:
- [x] update border-radius value for `<rh-tooltip>` in repo
- [x] change corner radius value for tooltip component in Figma from `4px` to `3px`
- [ ] check docs for outdated information and update

**Comment by marionnegp** [comment]
@coreyvickery, wanted to alert you to this small change. @markcaron @hellogreg, would you prefer to map this to Clefairy or Cubone?

**Comment by zeroedin** [comment]
> @coreyvickery, wanted to alert you to this small change. @markcaron @hellogreg, would you prefer to map this to Clefairy or Cubone?

 Because this is just a style change IMHO can just be a patch.  See https://github.com/RedHat-UX/red-hat-design-system/pull/1841
 
 I also updated the logical properties for positioning as well as removed some deprecated undocumented CSS custom properties in that PR.

**Comment by coreyvickery** [comment]
@zeroedin Good stuff!

**Comment by bennypowers** [comment]
cc @dustinmazon who kindly drew our attention to this issue
