### ISSUE TITLE
[fix] `<rh-tag>` color updates

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system#1843]
### Description

This looks like a lot, but these are hopefully quick updates to the existing `<rh-tag>` component.

[Figma file](https://www.figma.com/design/j7Rjo2W6PLloxOSXQOpll0/Red-Hat-Design-System-library?m=auto&node-id=66-869&t=i9ZSqa4sY7sIePqr-1)

---

# Details
<img width="178" alt="Screenshot 2024-09-08 at 4 26 32 PM" src="https://github.com/user-attachments/assets/68727d3d-4b96-489c-93e8-61789104169a">

- There are 2 themes: `Light` and `Dark`

<img width="279" alt="Screenshot 2024-09-08 at 4 29 17 PM" src="https://github.com/user-attachments/assets/cd074a0d-cdf9-4e4a-b458-22534da2ff55">

- There are 3 styles: `Filled`, `Outlined`, and `Desaturated`

<img width="185" alt="Screenshot 2024-09-08 at 4 30 57 PM" src="https://github.com/user-attachments/assets/81263008-b6f3-4934-9ba2-fd9aad16eced">

- There are 2 sizes: `Default` and `Compact`

<img width="606" alt="Screenshot 2024-09-08 at 4 41 01 PM" src="https://github.com/user-attachments/assets/1554e065-620d-4766-a6ea-58254bdd4251">

- There are 9 colors: `Red`, `Red orange`, `Orange`, `Yellow`, `Green`, `Teal`, `Blue`, `Purple`, `Gray`

<img width="256" alt="Screenshot 2024-09-08 at 4 49 33 PM" src="https://github.com/user-attachments/assets/724c64cd-ce1b-4e1b-9a3f-1d4d642a827e">

- Every style, size, and color may include a decorative icon (sizes below)

<img width="372" alt="Screenshot 2024-09-08 at 4 46 13 PM" src="https://github.com/user-attachments/assets/b7278e3f-4b00-465e-b672-9efafcac41b1">

- Every style, size, and color may have non-linked or linked text

---

# Global values

### Border

| Border radius | Border width | Border width - hover |
| - | - | - |
| `--rh-border-radius-pill` | `--rh-border-width-sm` (1px) | `--rh-border-width-md` (2px) |

### Typography - `Default` size

| Font family | Font weight | Font size | Line height | Text decoration - linked | Border radius | Border width - default | Border width - hover |
| - | - | - | - | - | - | - | - |
| `--rh-font-family-body-text` (Red Hat Text) | `--rh-font-weight-body-text-regular` (Regular) | `--rh-font-size-body-text-sm` (14px) | `--rh-line-height-body-text` (1.5) | Underlined | `--rh-border-radius-pill` | `--rh-border-width-sm` (1px) | `--rh-border-width-md` (2px) |

### Typography - `Compact` size
> The only difference is a slightly smaller font size.

| Font size |
| - |
| `--rh-font-size-body-text-xs` (12px) |

### Decorative icon size

| Decorative icon size |
| - |
| `--rh-size-icon-01` (16px) |

### Padding

| Tag size | Left and right | Top and bottom | In between decorative icon and text |
| - | - | - | - |
| Default | `--rh-space-md` (8px) | `--rh-space-xs` (4px) | `--rh-space-xs` (4px) |
| Compact | `--rh-space-md` (8px) | 0 | `--rh-space-xs` (4px) |

---

# Color values

### Colors - `Filled` style
> Light theme `Filled` style tags adhere to the following system.
>
> For example, for the `Red` tag, the fill is `red-10`, the border is `red-30`, the decorative icon is `red-50`, and the text is `red-70`.

<img width="786" alt="Frame 1 - light" src="https://github.com/user-attachments/assets/24762f5c-6776-4f3a-a6b2-59d1ad193245">

| Tag color | Fill | Border | Decorative icon | Text |
| - | - | - | - | - |
| (color) | `(color)-10` | `(color)-30` | `(color)-50` | `(color)-70` |

### Colors - `Outlined` style
> Light theme `Outlined` style tags adhere to the following system.
>
> For example, for the `Red` tag, the fill is `white`, the border is `gray-30`, the decorative icon is `red-50`, and the text is `red-60`.

<img width="786" alt="Frame 1 - outlined - light" src="https://github.com/user-attachments/assets/45994b3a-4dd3-414e-b9e3-6bb3a2eabd2c">

| Tag color | Fill | Border | Decorative icon | Text |
| - | - | - | - | - |
| (color) | `white` | `gray-30` | `(color)-50` | `(color)-60` |

### Colors - `Desaturated` style
> All light theme `Desaturated` style tags are the same.
>
> For example, for all tag sizes and colors, there is no fill and the border, decorative icon, and text are all `gray-95`.

<img width="786" alt="Frame 1 - desat - light" src="https://github.com/user-attachments/assets/fcca821c-a037-43fa-a801-c5d73e4c27e9">

| Tag color | Fill | Border | Decorative icon | Text |
| - | - | - | - | - |
| (color) | None | `gray-95` | `gray-95` | `gray-95` |

### Colors - `Filled` style
> Dark theme `Filled` style tags adhere to the following system.
>
> For example, for the `Red` tag, the fill is `red-70`, the border is `red-50`, the decorative icon is `red-30`, and the text is `red-10`.

<img width="786" alt="Frame 1" src="https://github.com/user-attachments/assets/bf38b190-0f36-4b52-ad21-946f76831683">

| Tag color | Fill | Border | Decorative icon | Text |
| - | - | - | - | - |
| (color) | `(color)-70` | `(color)-50` | `(color)-30` | `(color)-10` |

### Colors - `Outlined` style
> Dark theme `Outlined` style tags adhere to the following system.
>
> For example, for the `Red` tag, the fill is `gray-95`, the border is `gray-50`, the decorative icon is `red-20`, and the text is `red-30`.

<img width="786" alt="Frame 1 - outlined - dark" src="https://github.com/user-attachments/assets/ea955d5d-2790-4b14-9af6-51aeed8bf912">

| Tag color | Fill | Border | Decorative icon | Text |
| - | - | - | - | - |
| (color) | `gray-95` | `gray-50` | `(color)-20` | `(color)-30` |

### Colors - `Desaturated` style
> All dark theme `Desaturated` style tags are the same.
>
> For example, for all tag sizes and colors, there is no fill and the border, decorative icon, and text are all `white`.

<img width="786" alt="Frame 1 - desat - dark" src="https://github.com/user-attachments/assets/2ee552c1-61d6-4f59-833e-2570a63e4539">

| Tag color | Fill | Border | Decorative icon | Text |
| - | - | - | - | - |
| (color) | None | `white` | `white` | `white` |

### Acceptance Criteria

- [X] Design done
- [ ] Development done

### Design file

https://www.figma.com/design/j7Rjo2W6PLloxOSXQOpll0/Red-Hat-Design-System-library?m=auto&node-id=66-869&t=i9ZSqa4sY7sIePqr-1

**Comment by bennypowers** [comment]
This will be a nice follow-on to #1792

**Comment by bennypowers** [comment]
are we deprecating the `cyan` colour? that's a breaking change

**Comment by coreyvickery** [comment]
@bennypowers Yes, the Brand team does not use it anymore either.
