### ISSUE TITLE
[bug][docs] `<rh-accordion>` accent demos

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1846]
### Describe the bug

In the full screen demos for `<rh-accordion>`, an additional tag with two icons get added for each purposely placed tag:
 
![Screenshot 2024-09-09 at 2 42 35 PM](https://github.com/user-attachments/assets/a08c277d-f308-4d77-b697-3cb735568c76)

Also, the "Accents Bottom" demo doesn't show the tags below the header.
![Screenshot 2024-09-09 at 2 49 09 PM](https://github.com/user-attachments/assets/0a7ee09a-69ba-44fc-8006-d80954e6a2bd)

### Steps to reproduce

Go to the accordion's ["Accents" demo](https://ux.redhat.com/elements/accordion/demo/accents/) or ["Accents bottom" demo](https://ux.redhat.com/elements/accordion/demo/accents-bottom/).

### Expected behaviour

The tags should look similar to what's in the image for the [accent slot docs](https://ux.redhat.com/elements/accordion/demo/accents/).

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by marionnegp** [comment]
@markcaron @hellogreg, I've added this under Clefairy, but feel free to move it around if it's not a high priority.

**Comment by bennypowers** [comment]
Make sure icon gets loaded on the demo page and that the hydration shim loads before any component definitions

**Comment by bennypowers** [comment]
#1853 should fix this. see [DP](https://deploy-preview-1853--red-hat-design-system.netlify.app/elements/accordion/demo/accents-bottom/)
