### ISSUE TITLE
[docs][bug] incorrect image sizes

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1847]
### Description

Some images contained in `<uxdot-example>` are showing up at 2x the size in the `width-adjustment` attribute.

### Screenshots

![Screenshot 2024-09-09 at 3 23 42 PM](https://github.com/user-attachments/assets/e13e0f83-8401-4806-8433-1d43943b7105)

### Steps to reproduce

See examples on the [Tooltip - Style subpage](https://ux.redhat.com/elements/tooltip/style/), [Accordion - Overview](https://ux.redhat.com/elements/accordion/#overview), and [Avatar - Overview](https://ux.redhat.com/elements/accordion/#overview)

### Expected behaviour

The image sizes should match what's in the `width-adjustment` attribute.

### Operating System (OS)

macOS

**Comment by marionnegp** [comment]
@markcaron @hellogreg, I added this to the Clefairy milestone too, but this can be reprioritized!

**Comment by marionnegp** [comment]
Looking at ux dot in the  DP for #1792, `<uxdot-example>` doesn't seem to be contributing any styling. Here's what [tooltip's Style subpage](https://deploy-preview-1792--red-hat-design-system.netlify.app/elements/tooltip/style/) looks like in there.
![Screenshot 2024-09-10 at 11 50 08 AM](https://github.com/user-attachments/assets/bfeebc24-7e3a-430a-af75-4a4d9bef9188)

**Comment by bennypowers** [comment]
Maybe is just missing element definition for uxdot example on that page
