### ISSUE TITLE
[docs][bug] patterns/card page has several display errors

### ISSUE THREAD

**Issue by paceaux** [RedHat-UX/red-hat-design-system#1848]
### Description

On ux.redhat.com/patterns/card, there are several display errors. 

1. The `<uxdot-pattern>` element is displaying inline and this is overlapping the content that follows, including the footer
2. The `<p>` following `#explicit-card-theming` overlaps a code container

### Screenshots

![image](https://github.com/user-attachments/assets/548b0c8a-f672-4f5f-afb3-472e4e225ba8)

![image](https://github.com/user-attachments/assets/c603cbc7-4646-430a-80ad-12a940d5dd75)

### Steps to reproduce

1. go to the page ux.redhat.com/patterns/card
2. Scroll down the page to "explicit card themeing"

### Expected behaviour

Hard to say what I'd expect to see, but I'm guessing `<uxdot-pattern>` would be `display: block` and not overlap other content. It would be more clear what code example went with which card. 

### Operating System (OS)

macOS

### Browser

Chrome, Safari, Firefox

**Comment by bennypowers** [comment]
Try it on the clefairy or theming props deploy previews

**Comment by paceaux** [comment]
@bennypowers I don't know the URLs for those previews. Can you share those?

**Comment by paceaux** [comment]
ok, looking at some of the preview environments, this issue appears resolved. , e.g. https://deploy-preview-1792--red-hat-design-system.netlify.app/

**Comment by bennypowers** [comment]
fixed on clefairy
