### ISSUE TITLE
[bug] `<rh-tile>` font weight

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#1863]
### Describe the bug

Compact tiles are showing a heavier font weight than 400, which is the correct weight. May be due to`font-weight: var(--rh-font-weight-heading-medium,500);` being applied to `#outer` when it should be applied to something else in the shadowroot.

### Steps to reproduce

Check the [compact tile demo](https://ux.redhat.com/elements/tile/demos/#demo-compact).

### Expected behaviour

Should have a font-weight of 400.

### Operating System (OS)

macOS

**Comment by bennypowers** [comment]
Closed by 8ee8afea - https://deploy-preview-1802--red-hat-design-system.netlify.app/elements/tile/demo/compact/
