### ISSUE TITLE
[bug] `<rh-context-picker>` focus lags selection

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1867]
Keyboard navigate a context-picker in a card pattern: https://ux.redhat.com/patterns/card/

Focus appears sometimes to lag as well as sometimes an arrow key needs pressed twice.  

Also weirdness occurs on mouse click with focus and selection.

![image](https://github.com/user-attachments/assets/050562e4-4535-4198-b44d-18176b8ab781)

**Comment by bennypowers** [comment]
Is this still a problem on https://deploy-preview-1802--red-hat-design-system.netlify.app/patterns/card/? I was unable to reproduce
