### ISSUE TITLE
`<rh-tabs>` : focus and hover states

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#1886]
> Hover and focus states aren’t showing for any of the color context demo options. (I can see the focus ring though.)

https://deploy-preview-1802--red-hat-design-system.netlify.app/elements/tabs/demo/

Originally posted by @marionnegp in https://github.com/RedHat-UX/red-hat-design-system/issues/1852

**Comment by coreyvickery** [comment]
@bennypowers If you need color guidance, see the [Interaction states](https://ux.redhat.com/elements/tabs/style/#interaction-states) section. Otherwise, doesn't seem like a design issue.
