### ISSUE TITLE
[docs] elaborate on theming for developers

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#1892]
Elaborate on the stub content in the file: put that stuff in the second half of the page, because it's more "under the hood" stuff

if the first section explain the "how to use" stuff:

- themable containers like surface, card, tile, accordion, etc
- `color-palette` attribute as the key to the whole system (which will not change when style queries land)
- using `<rh-surface role="main">` for whole-page theming
- theming individual sections with surface

**Comment by zeroedin** [comment]
Link to current DP: https://deploy-preview-1802--red-hat-design-system.netlify.app/theming/developers/
