### ISSUE TITLE
[feat] `<rh-navigation-primary>` expanded menu

### ISSUE THREAD

**Issue by littledezine** [RedHat-UX/red-hat-design-system#1899]
### Description

Please enhance the primary navigation component in the Figma design library for Red Hat dot com for desktop, tablet, and mobile sizes.

### Suggested solution

The updated primary navigation component should represent an expanded view of red.com in its current state for all main menu items in both logged-out and logged-in states. Refer to the attached screenshots for reference.

### Screenshots

![CleanShot 2024-09-19 at 13 43 56@2x](https://github.com/user-attachments/assets/19489aea-382b-4550-9c18-5fadbcbb4533)
![CleanShot 2024-09-19 at 13 44 12@2x](https://github.com/user-attachments/assets/00abe527-095b-47a0-99e1-1029bbb174b4)
![CleanShot 2024-09-19 at 13 43 44@2x](https://github.com/user-attachments/assets/6ea6fe72-01db-45ce-9b9c-e5b8c8bc28a0)
![CleanShot 2024-09-19 at 13 45 37@2x](https://github.com/user-attachments/assets/8e855733-2d7f-457d-a200-05bec8af0cd1)
![CleanShot 2024-09-19 at 13 43 33@2x](https://github.com/user-attachments/assets/3fa95659-c37f-410f-
![CleanShot 2024-09-19 at 13 46 18@2x](https://github.com/user-attachments/assets/6997063f-98aa-4b16-99f7-50048b352b7a)
![CleanShot 2024-09-19 at 13 45 15@2x](https://github.com/user-attachments/assets/2ecd2846-49f4-44ef-8bd5-aca569f6849d)
![CleanShot 2024-09-19 at 13 45 37@2x](https://github.com/user-attachments/assets/d97abeec-14b9-4112-8a31-73ce8cac2fe8)
![CleanShot 2024-09-19 at 13 46 06@2x](https://github.com/user-attachments/assets/42ae7d4a-99f9-4501-9fc9-a38229c778b6)
b573-1643997862c1)

**Comment by coreyvickery** [comment]
This was added to the `Cross-domain navigation` subsystem.
