### ISSUE TITLE
[docs] `uxdot-repo-status-list` missing border

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#1921]
Repo Status List should have a border

Current:
![image](https://github.com/user-attachments/assets/92df286d-89a9-4a22-add1-7d8dfe4a4e40)

Correct:
![Screenshot 2024-09-25 at 10 14 40 AM](https://github.com/user-attachments/assets/16fa95fb-ec44-4aaa-8fa4-81ae340d1d4e)

**Comment by bennypowers** [comment]
is this still the case?

https://deploy-preview-1802--red-hat-design-system.netlify.app/elements/accordion/#status
