### ISSUE TITLE
[fix] `<rh-alert>` color updates

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system#1926]
### Describe the bug

Updates to the existing <rh-alert> component.

[Figma file](https://www.figma.com/design/j7Rjo2W6PLloxOSXQOpll0/Red-Hat-Design-System-library?m=auto&node-id=11-564)

---

# Details

### Inline
<img width="777" alt="Screenshot 2024-09-25 at 10 58 32 AM" src="https://github.com/user-attachments/assets/3c27458c-359d-4cda-885c-081f3f86889f">

### Toast
<img width="387" alt="Screenshot 2024-09-25 at 11 04 00 AM" src="https://github.com/user-attachments/assets/7583f2b1-a6bd-40c5-a761-69fbd4bad98a">

### Inline
<img width="767" alt="Screenshot 2024-09-25 at 10 58 36 AM" src="https://github.com/user-attachments/assets/e7eba346-7af9-4f3b-85a5-753cd5c219b4">

### Toast
<img width="388" alt="Screenshot 2024-09-25 at 11 04 04 AM" src="https://github.com/user-attachments/assets/771b6656-7e52-4927-8ba8-2a6b83991225">

### Inline
<img width="777" alt="Screenshot 2024-09-25 at 10 58 39 AM" src="https://github.com/user-attachments/assets/29530142-b430-4909-ace4-495cb4bec978">

### Toast
<img width="392" alt="Screenshot 2024-09-25 at 11 04 06 AM" src="https://github.com/user-attachments/assets/22d0190e-5604-45c4-9c28-c7786b71ab09">

### Inline
<img width="774" alt="Screenshot 2024-09-25 at 10 58 42 AM" src="https://github.com/user-attachments/assets/7522c616-f249-441a-80a0-e23bdabded1e">

### Toast
<img width="389" alt="Screenshot 2024-09-25 at 11 04 09 AM" src="https://github.com/user-attachments/assets/56e0f6a4-59ae-45ac-b341-30addbc5cf7b">

### Inline
<img width="771" alt="Screenshot 2024-09-25 at 10 58 45 AM" src="https://github.com/user-attachments/assets/22fafc64-9eec-435a-82a0-059425a8b094">

### Toast
<img width="389" alt="Screenshot 2024-09-25 at 11 04 12 AM" src="https://github.com/user-attachments/assets/b9318341-561c-40cb-8fab-b7b70c23cef5">

### Inline
<img width="769" alt="Screenshot 2024-09-25 at 10 58 48 AM" src="https://github.com/user-attachments/assets/723e67c0-f595-4040-8bb6-21ae53ad39d2">

### Toast
<img width="388" alt="Screenshot 2024-09-25 at 11 04 16 AM" src="https://github.com/user-attachments/assets/71653d0b-ecc4-4556-9601-ec183c21e40d">

---

# Global values

### Border

| Alert variant | Border width | Border position |
| - | - | - |
| `Inline` | `--rh-border-width-md` (2px) | Top only |
| `Inline` | `--rh-border-width-md` (2px) | All sides |
| `Toast` | `--rh-border-width-md` (2px) | Top only |

### Typography - title text

| Font family | Font weight | Font size | Line height |
| - | - | - | - |
| `--rh-font-family-body-text` (Red Hat Text) | `--rh-font-weight-body-text-medium` (Medium) | `--rh-font-size-body-text-sm` (14px) | `--rh-line-height-body-text` (1.5) |

### Typography - body text

| Font family | Font weight | Font size | Line height |
| - | - | - | - |
| `--rh-font-family-body-text` (Red Hat Text) | `--rh-font-weight-body-text-regular` (Regular) | `--rh-font-size-body-text-sm` (14px) | `--rh-line-height-body-text` (1.5) |

---

# Color values

| Status | Background | Border and icon | Title and body text |
| - | - | - | - |
| `Neutral` | `gray-10` | `gray-60` | `gray-95` |
| `Info` | `purple-10` | `purple-50` | `gray-95` |
| `Success` | `green-10` | `green-60` | `gray-95` |
| `Warning` | `yellow-10` | `yellow-40` | `gray-95` |
| `Caution` | `orange-10` | `orange-50` | `gray-95` |
| `Danger` | `red-orange-10` | `red-orange-60` | `gray-95` |

# Icon values

Referencing [this page](https://red-hat-icons.netlify.app/) for names.

| Status | Icon name |
| - | - |
| `Neutral` | `minus-circle-fill` |
| `Info` | `information-fill` |
| `Success` | `check-circle-fill` |
| `Warning` | `warning-fill` |
| `Caution` | `error-fill` |
| `Danger` | `ban-fill` |
| `Close` | `close` |

# Drop shadow values

| Alert variant | Value |
| - | - |
| Inline | None |
| Toast | `--rh-box-shadow-xl` |

# Spacing values

<img width="387" alt="Screenshot 2024-09-25 at 11 19 48 AM" src="https://github.com/user-attachments/assets/ac6a6028-8e49-43aa-ae19-a1aa599383d3">

### Steps to reproduce

1. Go to the [Demos](https://ux.redhat.com/elements/alert/demos/) page
2. Look at the colors and styles

### Expected behaviour

Styles are expected to match what's in Figma.

### Operating System (OS)

iOS, macOS, Linux, Windows

**Comment by bennypowers** [comment]
@coreyvickery please clarify: does this mean rh-alert should *not* use the DPO status tokens?

**Comment by coreyvickery** [comment]
@bennypowers Ideally, yes.

**Comment by coreyvickery** [comment]
@bennypowers To clarify, yes, they should.
