### ISSUE TITLE
[docs] Graphics for theming overview page

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#1931]
### Description

The [theming overview page](https://deploy-preview-1802--red-hat-design-system.netlify.app/theming/) is still using placeholders, and could use some bespoke svg.

### Links

https://deploy-preview-1802--red-hat-design-system.netlify.app/theming/

### Screenshots

![image](https://github.com/user-attachments/assets/cb460ac8-f1c1-43fe-a80f-31b96fc2f7e1)

### Additional context

More prose would be nice as well, but if that would delay closing this issue, I'd happily settle for just the graphics.

**Comment by coreyvickery** [comment]
Page with updated graphics [here](https://www.figma.com/proto/3liewFtztT3rP4MKCznjVI/Theming?page-id=1%3A88&node-id=1-89&node-type=canvas&viewport=94%2C132%2C1&t=2ITtBYBVgGpBIwcY-1&scaling=scale-down&content-scaling=fixed).
