### ISSUE TITLE
[docs][bug] "Demos" page in `<rh-subnav>` displayed twice

### ISSUE THREAD

**Issue by adamjohnson** [RedHat-UX/red-hat-design-system#1978]
### Description

When visiting any uxdot element, the link to the "Demos" page shows up twice.

### Screenshots

![Uxdot site with the Demos page displaying twice in the subnav of each element](https://github.com/user-attachments/assets/a50f6e2e-9620-4957-b7f6-905d6ce8bfbd)

### Steps to reproduce

1. Go to any element on the uxdot site, for example [CTA](https://ux.redhat.com/elements/call-to-action/).
2. Look at the items in the `<rh-subnav>`.
3. The "Demos" link is displayed twice.

### Expected behaviour

The "Demos" link should only be displayed once.

### Operating System (OS)

macOS

### Browser

Chrome, Safari, Safari iOS, Microsoft Edge, Firefox

**Comment by bennypowers** [comment]
This no longer appears to be an issue
