### ISSUE TITLE
[docs][bug] Each accordion panel with content expanded on page load on {Element} > Code pages

### ISSUE THREAD

**Issue by adamjohnson** [RedHat-UX/red-hat-design-system#1981]
### Description

If you visit a Code page of any element and scroll down to any of the `<rh-accordion>`'s on those pages, each accordion panel is expanded on page load.

### Screenshots

![Screenshot of expanded accordion panels on the Alert Code subpage](https://github.com/user-attachments/assets/60e5f5ea-a323-4fe7-bd25-9991530ec848)

### Steps to reproduce

1. Visit any Element on uxdot.
2. Once you're on the Overview page, click on "Code" in the subnav. Eg: [Alert](https://ux.redhat.com/elements/alert/) > [Code](https://ux.redhat.com/elements/alert/code/#usage).
3. Scoll down to view the accordion containing docs for slots, attributes, methods, events...
4. Observe how any accordion panel that has content is expanded.

### Expected behaviour

Accordion panels should be collapsed on the Code page on initial load. 

### Operating System (OS)

macOS

### Browser

Safari, Microsoft Edge

### Additional browser or assistive technology info

Interestingly, `<uxdot-copy-permalink>` is not working on Code pages either.

**Comment by bennypowers** [comment]
the idea here was to expand *only* those panels which have API content, in order that <kbd>ctrl</kbd>-<kbd>f</kbd> works. This aids discoverability, so that users won't be confused about which APIs are available on elements.
