### ISSUE TITLE
[docs][bug] Incorrect active page when visiting most subpages under "Tokens"

### ISSUE THREAD

**Issue by adamjohnson** [RedHat-UX/red-hat-design-system#1982]
### Description

When visiting any page under "Tokens" that's not [Overview](https://ux.redhat.com/tokens/) or [Global Color](https://ux.redhat.com/tokens/color/), the `active` attribute on `<uxdot-sidenav-dropdown-menu-item>` is incorrect (always points to Global Color or Overview pages, even if you are not on one of those pages).

### Screenshots

![Annotated screenshot of the box shadow page showing how the Global Color page has the active attribute](https://github.com/user-attachments/assets/c82ce153-09ee-4e2d-a338-4ecb742c6afb)

### Steps to reproduce

1. On uxdot, visit the [Overview page](https://ux.redhat.com/tokens/) under "Tokens".
2. Note the `active` attribute in the left nav is correct here.
3. Repeat steps 1-2 for the [Global Color page](https://ux.redhat.com/tokens/color/).
4. Up to this point, `active` is working as expected.
5. Now, click on any page in that section that's not one of the two above (eg: [Length](https://ux.redhat.com/tokens/length/)).
6. Notice how the `active` attribute remains on the Global Color item in the left nav.

### Expected behaviour

The `active` attribute should highlight the page currently being visited. 

### Operating System (OS)

macOS

### Browser

Safari, Microsoft Edge

**Comment by bennypowers** [comment]
This no longer appears to be an issue
