### ISSUE TITLE
[bug] `<rh-tabs>` don't display active border on initial load

### ISSUE THREAD

**Issue by adamjohnson** [RedHat-UX/red-hat-design-system#1983]
## Describe the bug

When using an `<rh-tabs>` component, the red border delineating the current tab does not appear on page load in all browsers except Safari.

## Screenshots

![Screenshot of tabs without the red border on the active tab](https://github.com/user-attachments/assets/35ea9d5f-8acc-4c5e-bf9e-ca570b76dc2f)

## Steps to reproduce

1. Visit the [`<rh-tabs>` demo](https://ux.redhat.com/elements/tabs/demo/) in any browser except Safari.
2. Observe that the first tab is showing ("Users").
3. Observe the missing red bottom border under the "Users" `<rh-tab>`.

## Expected behavior

Upon loading the `<rh-tabs>` demo, users should see the red border under the currently active tab.

## Operating System (OS)

macOS

## Browser

Chrome, Microsoft Edge, Firefox

## Additional browser or assistive technology info

Curiously, the red border is visible in Safari.

**Comment by bennypowers** [comment]
This no longer appears to be the case
