### ISSUE TITLE
[docs] Update Color foundations page

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system#1991]
### Description

Requesting minor text and image updates.

[Figma prototype](https://www.figma.com/proto/YhTYnvNpyg4Hgl0WaFDzeI/Color-page-updates?page-id=0%3A1&node-id=1-2&node-type=canvas&viewport=112%2C134%2C1&t=uTOAAzb6JH6oaZxl-1&scaling=scale-down&content-scaling=fixed)

### Links

https://ux.redhat.com/foundations/color/

**Comment by marionnegp** [comment]
There were some additional changes to the content of the Color page that are being made in #2020.
