### ISSUE TITLE
[feat] Add `<rh-tag>` to `<rh-tile>`

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system#2006]
### Description

Request from Dan for home page work.

Need a slot in `<rh-tile>` to add `<rh-tag>`.

### Suggested solution

See above.

### Screenshots

https://www.figma.com/proto/cB8q15K9rR3UgqQRM4CZzV/redhat.com-home-page---Sub-hero-section?page-id=1237%3A8801&node-id=1373-2368&node-type=section&viewport=-2130%2C-103%2C0.13&t=FNJRHzrQb4NWCMwJ-1&scaling=min-zoom&content-scaling=fixed

**Comment by zeroedin** [comment]
Done with a pattern: https://codepen.io/zeroedin/pen/LYwzwYx

**Comment by coreyvickery** [comment]
@zeroedin Looks good to me! Who else needs to approve?

**Comment by zeroedin** [comment]
> @zeroedin Looks good to me! Who else needs to approve?

I'll try and get a PR up to add it to the patterns demos for tile.  At that point we can go through standard review process.
