### ISSUE TITLE
[bug] `<rh-accordion>` header text font weight is too heavy

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#2066]
### Describe the bug

`<rh-acccordions>` used on redhat.com are too bold. It looks ok in our UX dot demos, but I think something may be up with our font weights.

### Screenshots

<img width="1412" alt="Screenshot 2024-11-25 at 3 17 24 PM" src="https://github.com/user-attachments/assets/843cc64c-6184-4073-9e8a-dfa783cafd7d">

### Steps to reproduce

View accordions close to the bottom of the [Red Hat Learning Subscription page](https://www.redhat.com/en/services/training/learning-subscription#what-is-early-access-content).

### Expected behaviour

It should be a medium font weight.

### Operating System (OS)

macOS

**Comment by bennypowers** [comment]
![Screenshot From 2024-11-26 16-21-16](https://github.com/user-attachments/assets/de9c9aae-742b-4f73-af9d-9f65a18d3b72)
![Screenshot From 2024-11-26 16-21-02](https://github.com/user-attachments/assets/a2b79194-064b-4431-9498-a3c7c46b23b4)

Looks like RHDC is using the variable font, whereas the demo is not

so this is probably an issue of conflicting page css on rhdc

**Comment by marionnegp** [comment]
Ok, I'll close this because it's not an RHDS issue.
