### ISSUE TITLE
`<rh-accordion>` header text weight

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#2083]
The font-weight of the accordion panel headers looks different in Safari and Firefox than it does in Chrome.

Chrome:
![image](https://github.com/user-attachments/assets/f8a778b2-d924-4ef2-a0c2-735bb2ebfdbe)

Firefox:
![image](https://github.com/user-attachments/assets/74fed895-d6e2-4e6d-9187-3fdbff016dc4)

Safari:
![image](https://github.com/user-attachments/assets/fc4b964e-2c4a-4422-ba8b-7b43ce4d4a2d)

Manually changing Chrome's font-weight to 500 and 700 has no visual change.

https://github.com/RedHat-UX/red-hat-design-system/blob/8ec2cc48ce5268cc9f7ae40af6eca3cc806b3252/elements/rh-accordion/rh-accordion-header.css#L128-L130

https://github.com/RedHat-UX/red-hat-design-system/blob/8ec2cc48ce5268cc9f7ae40af6eca3cc806b3252/elements/rh-accordion/rh-accordion-header.css#L62-L71

This has to do with the font stack we are loading and Chrome's difference in how it renders weights that aren't loaded for the stack.  Whereas I believe Safari and seemingly Firefox too will synthesize it if it is missing.. at least I remember seeing that somewhere was the case for Safari although a quick search didn't return proof in that respect.

https://github.com/RedHat-UX/red-hat-design-system/blob/8ec2cc48ce5268cc9f7ae40af6eca3cc806b3252/docs/styles/fonts.css#L25-L39

We do not load a 700 weight for RedHatText in our [fonts.css](https://github.com/RedHat-UX/red-hat-design-system/blob/8ec2cc48ce5268cc9f7ae40af6eca3cc806b3252/docs/styles/fonts.css) file.  We do however load a 700 weight for RedHatDisplay.  

Are we sure we want to be using RedHatText for this header? 

https://github.com/RedHat-UX/red-hat-design-system/blob/8ec2cc48ce5268cc9f7ae40af6eca3cc806b3252/docs/styles/fonts.css#L17-L23

If so, we'll need to modify the font stack to accommodate the 700 weight for body text.  Also, that said [tokens for body text](https://github.com/RedHat-UX/red-hat-design-system/blob/8ec2cc48ce5268cc9f7ae40af6eca3cc806b3252/docs/styles/fonts.css) only go to 500 so likely this isn't the font family we want here.

**Comment by marionnegp** [comment]
The font weight for the accordion header should be `500` or medium. (`700` is too bold and isn't supposed to be used anywhere by body text, afaik.)

I think we use `Red Hat Text` for the header purely because that's what PF does.

**Comment by zeroedin** [comment]
@marionnegp awesome thanks, I'll get a PR up with the fix.

**Comment by zeroedin** [comment]
Was closed by #2084
