### ISSUE TITLE
[feat] Pagination Component

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#234]
Create a Pagination component for both desktop and mobile.

### Latest Design

![Image](https://user-images.githubusercontent.com/1890950/185936278-a7ca5cb9-701c-4df4-ad94-4fe74632e5c8.png)

### Design Doc

[Latest XD mockup](https://xd.adobe.com/view/75d471e8-9396-4721-8e3c-cf9aa0688d57-2087/)

### Other Resources
- [Old spec](https://xd.adobe.com/view/14878292-ce78-470c-b214-2eb41e11cada-41d4/)
- [Previous issue on PFE](https://github.com/patternfly/patternfly-elements/issues/200)

**Comment by bennypowers** [comment]
This was on the board so I picked it up.

- Please add a styles view to the XD @coreyvickery 
- There's a lot to discuss WRT behaviour and APIs.
  - e.g. Are SERP/data modes mutually exclusive? Do they represent different users (i.e. "page" vs "app"?)

**Comment by ronniemcbride** [comment]
@bennypowers  https://xd.adobe.com/view/75d471e8-9396-4721-8e3c-cf9aa0688d57-2087/

This is the link that I provided I the old Trello board the style view should be included.

**Comment by coreyvickery** [comment]
@bennypowers Marionne and I have a little more work to do for this component after meeting with other design leads today. We can have updated designs for you by early next week.

**Comment by markcaron** [comment]
CC: @ronniemcbride

**Comment by bennypowers** [comment]
Hey so I put in some hours developing this MVP: #279 . Thanks for the feedback @ronniemcbride and @coreyvickery , i'll wait for the design to stabilize before diving back into the CSS. I think there's still plenty of work to do on the javascript side of things.

That being said, I wasn't able to suss out the UX differences b/w SERP and data modes just by looking at the XD. If that part is stable @coreyvickery (or anyone else) can you elaborate here?

**Comment by coreyvickery** [comment]
@bennypowers Ronnie and Marionne will be finalizing this in my absence.

**Comment by marionnegp** [comment]
@ronniemcbride, here are the notes from the design leads sync.

- Remove double truncation version because it’s redundant when there are double chevron buttons linking to the first and last page.
- Minimize the number of button slots but keep the ability for people to skip to a particular page.
- Active state feels heavy. Decided to go with blue top border and white background.

**Comment by bennypowers** [comment]
@RedHat-UX/designers wanted to clarify: I'm still waiting on designer confirmation before diving back in to #279

**Comment by ronniemcbride** [comment]
@bennypowers es correct.  I will post the updates today by EOD.

**Comment by ronniemcbride** [comment]
@bennypowers  [here is the link](https://xd.adobe.com/view/75d471e8-9396-4721-8e3c-cf9aa0688d57-2087/) for the updated  XD  for this component.  Let me know if you have questions.

**Comment by bennypowers** [comment]
Thanks @ronniemcbride I found some colour values there which don't have corresponding tokens. Listing them here so we're all on the same page that these are unique to pagination:
- #B9BBBE - active page border
- #D2D2D2 - inactive pager icon colour
- #6A6E73 - active pager icon colour (and link hover block-start border)
- #2261C5 - focused link border colour

**Comment by bennypowers** [comment]
How does truncation work? Is there ever more than one ellipsis in a truncated paginator?

What is the difference between serp-style and data-style pagination? Is that something the page author needs to know about (i.e. opt in to) or is it something the component should derive based on the content provided?

**Comment by ronniemcbride** [comment]
> * 6A6E73

I'm using colors defined in the design kit. The last two, I'm not sure how that got there. Please use the following.  

#B8BBBE - active page border
#D2D2D2 - inactive pager icon colour
#0066CC - active pager icon colour (and link hover block-start border)
#0066CC - focused link border colour
![Benny’s Question](https://user-images.githubusercontent.com/73180910/172229719-cef2ef17-bb8f-41d1-b428-16c3cb9661a7.png)

 As for your truncation question.
 
 Truncation When the number of pages exceeds 5, Pagination ellipsis can be used to indicate there are remaining pages.
 
 << <- 1 2 3  ... 6 -> >>
 
 << <- 1 ... 4 5 6 -> >>
 
 Double Pagination Ellipsis is used when the current page is more than three pages from the first or last page if we use 7 slots. I can see this being needed, but we are only using only 5 number slots in this case. So I would say no. Maybe @markcaron  @coreyvickery  can weigh in on this.  
 
About your last question: 
I don't believe there is any difference beyond their display style. the component functionality should work based on the content provided. @markcaron Thoughts?

**Comment by bennypowers** [comment]
Thanks, `#B9BBBE` and `#D2D2D2` I still don't have values for in the tokens repo, so if @coreyvickery is amenable we'll add them there, otherwise i'll just hard-code them into pagination.

I have the code for double `…` working but I can remove it, waiting also on @coreyvickery 's take.

For Data/Serp: if the difference is the type of content provided, then how should the component  decide which type of content it has? in other words how does it know it's displaying SERP content as opposed to Data content?

**Comment by bennypowers** [comment]
Thanks Corey

But in a, what happens when you get to page 4?

`<<` `<` _**`1`**_ `2` `3` `...` `20` `>` `>>`
`<<` `<` `1` _**`2`**_ `3` `...` `20` `>` `>>`
`<<` `<` `1` `2` _**`3`**_ `...` `20` `>` `>>`
`<<` `<` `1` `2` `3` `...` `20` `>` `>>`
What happens now? I'm on page 4 but which other pages do I show?
- I only want one ellipsis, so I'll put it before the `20`
- But if I do that, I can't show the current page (4) because I also want to show the `1`

**Comment by coreyvickery** [comment]
@bennypowers Do we need to revert to 7 slots? These options look weird if we stick with 5 (assuming there are 20 pages and you want to go to page 4).

`<<` `<` `[4]` `5` `6` `...` `20` `>` `>>`

`<<` `<` `1` `...` `[4]` `...` `20` `>` `>>`

7 slots looks a little better and also works if there are lots of pages.

`<<` `<` `1` `...` `[4]` `5` `6` `...` `20` `>` `>>`

`<<` `<` `1` `...` `249` `[250]` `251` `...` `500` `>` `>>`

**Comment by markcaron** [comment]
Moving forward in dev with the [current mockup](https://xd.adobe.com/view/75d471e8-9396-4721-8e3c-cf9aa0688d57-2087/), since the need for having "bookends" showing page 1 and the last page seems to be necessary for the user. This is what we have currently in use as well.

Once we get this component built, it'll be easier to test new concepts on real users—testing the removal of either bookend as the user pages through, the removal of the redundant `>>`, etc.

_And most importantly,_ we can continue to iterate on this once a component is in the hands of developers.

Concurrently, while in dev, @ronniemcbride will work on creating a mockup showing the dark theme using our current design tokens—which the component will reference.
