### ISSUE TITLE
[feat] <rh-tile> Component

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#235]
### Latest Design
<img width="418" alt="Screenshot 2023-09-22 at 10 59 56 AM" src="https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/9ba9d3fd-8299-4773-801c-efa9741c3389">

<img width="402" alt="Screenshot 2023-09-22 at 11 00 05 AM" src="https://github.com/RedHat-UX/red-hat-design-system/assets/95588923/0ff57d9c-ceff-43c9-854a-293b41036a08">

### Design Doc

[Latest XD mockup](https://xd.adobe.com/view/925ed24c-3ddf-4111-bacf-2a42e5249f7a-c70d/)

### Description

Create a Link Tile component.

### Old Example

[View the link tiles](https://origin-www-cms.redhat.com/en/demo-fts-patterns) at the bottom of this page as an example.

**Comment by coreyvickery** [comment]
@KrystalMoore16 Can you attach any designs you have or may have explored for this?

**Comment by KrystalMoore16** [comment]
Sure, @coreyvickery. I'll add a todo for myself to get that together.

Check out the link tiles on this site when you have a chance: https://hummingbot.io/en/community/
We may be able to pull some inspiration.

**Comment by KrystalMoore16** [comment]
Hey @coreyvickery, we should have a conversation about this soon. I want to talk through some of our variations to get your perspective. Here are some initial images:

**Default**
<img width="658" alt="image" src="https://user-images.githubusercontent.com/14824271/170385661-9d9910a8-b150-4c68-b0e7-42dc98fbe887.png">

**Hover (last tile)**
<img width="648" alt="image" src="https://user-images.githubusercontent.com/14824271/170385688-45a0af72-18d1-439b-9f80-12833ccd3aa1.png">

**Comment by KrystalMoore16** [comment]
Here's another example to review:
https://console.redhat.com/openshift/overview

**Comment by marionnegp** [comment]
- Here's an [XD file](https://xd.adobe.com/view/245762a7-2368-48b8-9090-079916cbd7c1-7104/) that has some design drafts of a link tile. We might need a compact version for Customer Portal or other info-heavy sites (see fourth screen).
- [Research on what's called a tile vs a card](https://xd.adobe.com/view/09fabbd5-1c2c-4d9a-b910-ed23fd84ba66-5ca9/)

**Comment by marionnegp** [comment]
PF repo issue about revisiting their `tile` component: [https://github.com/patternfly/patternfly-design/issues/1191](https://github.com/patternfly/patternfly-design/issues/1191)

Since theirs is still in beta, there are opportunities for aligning functionality and design of the PF tile and RHDS link tile.

We've also discussed creating a selectable variant of tile, which would be used in forms like a radio button or checkbox.

**Comment by marionnegp** [comment]
For a selectable tile variant, this is an example of one that Ashley Crago from the Customer Portal is working on: 

![Image](https://user-images.githubusercontent.com/95588923/191318613-8887d52a-7e8f-4996-b646-cbe25c5d418b.png)

**Comment by marionnegp** [comment]
Do we want to add saturated versions of tile? These might be needed for pages like the Customer Portal homepage.

- [Color options](https://xd.adobe.com/view/245762a7-2368-48b8-9090-079916cbd7c1-7104/screen/9f222e74-0185-4c47-a7d4-4b4e1b70ea8f/specs/)
- [Mockups using saturated tiles](https://xd.adobe.com/view/245762a7-2368-48b8-9090-079916cbd7c1-7104/screen/5b539fa6-a81b-43e3-ac8d-e769da94b31d/specs/)

**Comment by marionnegp** [comment]
- [ ] Add guidance to docs about what the tile layout should do on mobile with multiple tiles. (Try keeping 2 cards side by side on mobile up to a certain breakpoint. In FTS, they currently go to one column.)

**Comment by marionnegp** [comment]
Updated [XD link](https://xd.adobe.com/view/245762a7-2368-48b8-9090-079916cbd7c1-7104/) with mockups for screen sizes smaller than 768px. 

I think MVP for tile can include basic link tile and a compact link tile.

**Comment by markcaron** [comment]
@marionnegp, We can make a dev ticket now to get development under way while we wait for the the last approval on the black text variant.

CC: @KrystalMoore16

**Comment by marionnegp** [comment]
Currently exploring the accessibility requirements for a tile variant with a black, instead of a blue, heading. This would be used for pages like [Catalog's search results page](https://catalog.redhat.com/software/search?target_platforms=Red%20Hat%20Enterprise%20Linux), where the blue heading may visually compete with logos and other elements. The assumption is that users would know that these tiles can be interacted with already.

Here's a [mockup of a Catalog SERP section](https://xd.adobe.com/view/69eb2d37-5a78-43a3-b25f-011fe6fbd6fc-3cb8/) with the regular tile and a potential black heading variant side-by-side.
![Image](https://user-images.githubusercontent.com/95588923/230442369-b6b21761-150a-4b51-800b-3bfb44ddfeb2.png)

**Comment by marionnegp** [comment]
Regarding the question about whether we need an underline in addition to the blue heading and the focus/hover states: [Technique G183](https://www.w3.org/WAI/WCAG22/Techniques/general/G183)[WCAG 1.4.1] says that having a color contrast of 3:1 with surrounding text and having hover states for the heading is enough to satisfy [WCAG's use of color requirement](https://www.w3.org/WAI/WCAG22/Understanding/use-of-color).

I chatted with @nikkimk and @hellogreg about adding a black heading variant, and they pointed me to [WCAG's 3.2.4:
Consistent Identification](https://www.w3.org/WAI/WCAG22/Understanding/consistent-identification.html) requirement, which says that components that have the same functionality should be identified consistently. We would want to pick either the blue or the black heading, and I think the blue heading helps differentiate tiles from cards better.

I'm working to see if there might be other ways we can make tiles with logos feel less busy.

**Comment by markcaron** [comment]
RHDS Office Hours discussion today around RH Tile:

1. @marionnegp to update spec/mockup to include reserved space in lower right for arrow, black heading option for use on search result -type layouts, and other types/variants like checkbox, radio and disabled as well as logo only usage.
2. All variants/types are going to be part of `<rh-tile>` and `<rh-tile-group>`, because they're more similar (especially visually) than they are different.
3. `<rh-tile-group>` is a required parent element to handle relationship between tiles, but will not be opinionated on layout in light DOM.
4. RH Tile Group would also handle `aria-role="radiogroup"` for radios.
5. Type property on `<rh-tile-group>` with default as `link`, but will accept `radio` or `checkbox`, along with a radio controller.
7. Variant  on `<rh-tile-group>` with full size as default, and `mini` (just a logo or stat—hiding all other slotted children, but the first), and `compact`
8. Link variant will always have an arrow, except for `mini` variant.
9. For handling icons, `icon="[name]"` and `slot="icon"` will be available on `<rh-tile>`, with slot overriding attribute (see RH Tag and PFE Label).
10. Slots: `logo`, `icon`, `title`, `header`, body (unnamed / default), `footer` (see also RH Card)

**Comment by marionnegp** [comment]
The [latest iteration](https://xd.adobe.com/view/925ed24c-3ddf-4111-bacf-2a42e5249f7a-c70d/) of tile includes a selectable/form tile and a default link tile with an arrow to indicate interactivity.

**Comment by marionnegp** [comment]
This week, I replaced arrow in the disabled link tile with a crossed out circle. The disabled selectable tiles stayed the same.

**Comment by marionnegp** [comment]
Made the following [updates](https://xd.adobe.com/view/925ed24c-3ddf-4111-bacf-2a42e5249f7a-c70d/) to `tile`:

- Kept the arrow for all link tiles and added the option to have either a black or blue headline.
- Added the option for a full-width image.
- Changed the documentation to allow tile to exist on its own or in a group. Radio button tiles are the only ones that can’t be used alone. If tiles are in a group, they’ll all be the same type of tile.
- Added a dark theme version of selectable tile.

**Comment by nikkimk** [comment]
Note to self: See also #898

**Comment by bennypowers** [comment]
Can we close #898 in favour of this issue, following the holistic tracking approach we adopted for Bulbasaur?

**Comment by markcaron** [comment]
Closed #898 so we can track here.
