### ISSUE TITLE
[bug] Inactive tabs in sample component

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#241]
The sample components on https://ux.redhat.com/components/tabs/ are using #151515 for inactive tab text. Text color for inactive tabs should be #6A6E73 for wind and earth variants.

**Comment by bennypowers** [comment]
@marionnegp is this also a problem in patternfly elements, or only specifically here on the RHDS site?

**Comment by marionnegp** [comment]
[Tabs on the PFE site](https://patternflyelements.org/components/tabs/) have the same problem. However, there are pfe-tabs on redhat.com that are using the right color.

![home-pfe-tab](https://user-images.githubusercontent.com/95588923/166236099-196b703d-18e8-4e25-9304-8c532a338e30.jpg)

**Comment by bennypowers** [comment]
Ok that's helpful

So either
1. `<pfe-tabs>` has css bug (will have to consult pf designs), OR
2. we should override some colours here on the site 
    - and make sure to take note, because we'll need to fix that in `<rh-tabs>` eventually,

**Comment by bennypowers** [comment]
I'd like to fix this when we do tabs 1:1 and migrate pfe-tabs to rh-tabs

**Comment by zeroedin** [comment]
Closing as `pfe-tabs` are deprecated with `pf-tabs` and `rh-tabs` existing.
