### ISSUE TITLE
[feat] create Footnote component

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#252]
## Latest design ##

![Image](https://user-images.githubusercontent.com/95588923/202570615-eade222e-7415-42c4-bc06-96852fd931ba.png)
XD: https://xd.adobe.com/view/3dce6dad-b11c-46ce-a527-382fa1b90e54-689d/

Create a new Footnote component.

## Acceptance criteria ##
This pattern came up while working on the [new resource templates](https://www.redhat.com/en/resources/simplifying-network-automation-overview).

- the footnote will be a numeral and use an anchor link to connect to the full footnote near the footer
- used the default superscript formatting in XD (roughly 12pt)
- in the full footnote section, there's a link to return to where you were
- animate slow scroll is suggested to let the user know what's going on

## Design concept ##
<img width="921" alt="image" src="https://user-images.githubusercontent.com/1890950/166519722-e00a0e8b-7dd4-41a9-bdd9-622a616a0232.png">

## Resources ##
- [Markup considerations](https://css-tricks.com/footnote-characters)
- [Nice popover interaction example](https://marco.org/2017/05/15/mp3-isnt-dead)
- [Internal doc](https://docs.google.com/document/d/1-V0NJzk76GDZA4PDw_nZu4rFCBJNpfiPXfjjMG4BW_A/edit#)

**Comment by coreyvickery** [comment]
@markcaron I love the popover example, we even have a component for that too!

**Comment by bennypowers** [comment]
this looks a lot like popover + a + sup
can this be a pattern instead of an element?

**Comment by marionnegp** [comment]
Added dark theme, interaction states, and a mobile mockup to the [XD link](https://xd.adobe.com/view/3dce6dad-b11c-46ce-a527-382fa1b90e54-689d/)

**Comment by wesleymiles** [comment]
@marionnegp do you think this would work for an asterisks? or maybe we use footnote numbers in place of asterisks after this launches?

**Comment by marionnegp** [comment]
@wesleymiles, if there isn't another asterisk or footnote on the page, I can see it working. However, if there's more than one footnote, I'd definitely use numbers.

**Comment by marionnegp** [comment]
This has been added to the DS Kit file.
