### ISSUE TITLE
[bug][docs] Adjust font-size and line-height on design demos to meet RHDS standards

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#260]
In our `main.css` for design demos, we are currently using `1.05em` font-size and `1.6` line-height, which do not match our RHDS standards of `1em` (or `16px`) for font-size and `1.5` for line-height. This was inherited from https://patternflyelements.org/

We should base everything off our standards—making an even starting point.

https://github.com/RedHat-UX/red-hat-design-system/blob/1e2851b95eead2399c1beb5bb89c68d9da163ffc/docs/main.css#L11-L12

**Comment by markcaron** [comment]
CC @bennypowers @coreyvickery

**Comment by bennypowers** [comment]
👉 NB this file isn't loaded on the ux-dot site, it's for element demo pages to load (if they want)

Even in PFE it's only used in 3 places:
```
tools/pfe-tools/demo/index.njk
15:  <link rel="stylesheet" href="/docs/main.css">

docs/_includes/_head.njk
23:  <link rel="stylesheet" href="/main.css">

docs/_includes/layout-demo.njk
65:    <link rel="stylesheet" href="/main.css"/>
```
