### ISSUE TITLE
[feat] States for close button

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#275]
### Description

We might need to have a standalone close button created. There isn't one listed on the PFE site, and there are a couple different close buttons used in components on redhat.com.

### Suggested solution

The close button in our [alert component](https://ux.redhat.com/components/alert/#interaction-states) does have states that can be used.

### Example API

```HTML

- https://www.patternfly.org/v4/components/button
- https://ux.redhat.com/components/alert/#interaction-states

```

**Comment by bennypowers** [comment]
Can we make due with just a `<rh-icon-button icon="close">` or some such?

**Comment by marionnegp** [comment]
I think so. Would we be able to change up states/behaviors for <rh-icon-button> based on what the icon is?

**Comment by bennypowers** [comment]
we could expose css custom properties to change fill colour, etc

**Comment by marionnegp** [comment]
Closing this because `rh-button` includes a close variant that does have interaction states now.
