### ISSUE TITLE
[feat]: <rh-stat> ready for development

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#281]
### Tag Name

rh-stat

### Purpose

The Stat component is used for displaying statistics in an eye-catching block form.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/1890950/168862456-eb0275f3-ebe9-4929-aa69-8d3a891a0b1a.png">

Stat can also be used inside other components, like `<rh-card>`.

<img width="325" alt="image" src="https://user-images.githubusercontent.com/1890950/168862556-d6f7dbe2-d74b-42d4-9760-ba007e180620.png">

[More specifications](https://xd.adobe.com/view/067ac1e2-5343-4dd7-adf4-ef3e18a91387-5329/)

### Where will it be used?

RH Stat will be used on marketing pages, customer portal pages, dashboards and other areas where displaying eye-catching statistics is important.

### End user

A customer or potential customer who would be interested in seeing statistics around a certain feature or product.

### Intended end use

A customer or potential customer would be presented with a nice visual representation of a statistic.

### Properties

[See specifications](https://xd.adobe.com/view/067ac1e2-5343-4dd7-adf4-ef3e18a91387-5329/)

RH Stat needs a few slots:

1. Statistic (text, number)
2. Title (optional)
3. Caption / short description / body text
4. Icon (optional, above statistic always)

Options:

- Position of title can be above or below the statistic.
- Sizes: default and large
- Theme: on light and on dark
- Text is centered (always)

May need to discuss inclusion of CTA due to spacing requirement below the stat.

**Examples:**

<img width="554" alt="image" src="https://user-images.githubusercontent.com/1890950/168869531-76b23a58-7d8b-4bff-8598-32c91b9ed2da.png">

<img width="430" alt="image" src="https://user-images.githubusercontent.com/1890950/168867302-fbd1aa0b-6a26-4665-8d4c-ab3737527030.png">

### Page Builder

- [ ] My component **will** be part of a page-builder experience
- [X] I'm not sure

### Accessibility Features

- [X] **Color**: Color should not be the primary visual means of communicating information ([1.4.1](https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html))
- [X] **Content or microcopy** Text in any language should be clear, meaningful, structured, etc.
- [X] **Text Contrast**: Small text should have a contrast ratio of at least 4.5:1 ([1.4.3](https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html))
- [X] **Text Contrast**: Large text should have a contrast ratio of at least 3:1 ([1.4.3](https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html))
- [X] **Resizable Text**: Text should have the ability to be **resized** up to 200% without losing content or functionality (for example, horizontal scrolling) ([1.4.4](https://www.w3.org/WAI/WCAG22/Understanding/resize-text.html))
- [X] **Alt Text**: Non-text elements should have concise **text descriptions** (a.k.a. **alt text**) ([1.1.1](https://www.w3.org/WAI/WCAG22/Understanding/non-text-content.html))
- [X] **Keyboard**: Descriptions of how interactive elements behave when a key is pressed should be included ([2.1.1](https://www.w3.org/WAI/WCAG22/Understanding/keyboard.html)) (for example, the Esc key closes a navigation menu)
- [X] **Focus Appearance**: Colors between **focused states** should have a contrast ratio of at least 3.1 ([2.4.11](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html))
- [X] **Focus Appearance**: Borders should have a thickness of at least 2px ([2.4.11](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html))
- [X] **Focus Order**: It should be logical how a user moves focus from one element to another ([2.4.3](https://www.w3.org/WAI/WCAG22/Understanding/focus-order.html))
- [X] **Motion Animation**: Controls should be available to disable an animation triggered by an interaction ([2.3.3](https://www.w3.org/WAI/WCAG22/Understanding/animation-from-interactions.html))
- [X] **Mobile**: Interactive elements should be reachable for touching, scrolling, or dismissing

### MVP Requirements

- [X] Correct styles and neccessary sizes, orientations, variants, spacers, and themes
- [X] Responsive sizes and page layout examples placed on screenshots
- [X] Functionality guidance and static animation frames or prototypes with motion
- [X] Interaction and Selected states
- [X] Alignment options, character counts, and necessary translations
- [X] Clear and structured content, acceptable text contrast, and logical keyboard events

### Appearance

- [ ] Foundations are represented as tokens or variables (border, color, font, opacity, spacing, shadow, etc.) [Consult with the assigned developer to ensure you are both working with the correct styles and values]
- [ ] Foundations are applied to elements (backgrounds, buttons, fields, icons, links, etc.)
- [X] Size (Standard, Compact, Mini, etc.)
- [ ] Orientations (horizontal or vertical)
- [ ] Position in relation to trigger (top, right, bottom, left, etc.)
- [ ] Hierarchy and decoration variants (Primary and Secondary CTAs, Earth and Wind variant Tabs, etc.)
- [X] Decorations (borders, logos, UI icons, etc.)
- [X] Desktop and mobile scale spacers (visit the [Spacing](https://ux.redhat.com/foundations/spacing/) and [Typography](https://ux.redhat.com/foundations/typography/) pages for examples)
- [X] Themes (light, dark, high-contrast, custom color, etc.)
- [ ] Edge cases or limitations (accessibility, brand extensions, horizontal scrolling, missing images, etc.) [It is not required to include all of these specs, but keep them in mind]
- [ ] Fallback (if a browser does not support the original design) [Consult with the assigned developer first to determine if this is necessary to design]

### Page Layout

- [ ] Location on page (navigation, hero, band, card, footer, etc.)
- [ ] Grid (fixed width inside the grid, full-width or outside of the grid)
- [ ] Position on page (inline, overlay, toast)
- [ ] Stacking (space in between each instance if your component is meant to be repeatable)
- [X] Responsive screen sizes (desktop, tablet, mobile, etc.)
- [ ] Content degradation (becomes hidden, reduces in size, truncates due to length, etc.)
- [ ] Scrolling behavior (fixed, sticky, content scrolls inside; visit [this page](https://www.geeksforgeeks.org/what-is-the-difference-between-positionsticky-and-positionfixed-in-css/) for examples)

### Behavior

- [ ] Functionality (collapse, expand, navigate, play, submit, etc.)
- [ ] Animation or motion (hover, jump, slide, stack, toggle, etc.)
- [ ] Overflow (when content exceeds a defined boundary; visit the [Tabs](https://ux.redhat.com/components/tabs/) page for examples)
- [ ] Other effects (blur, cover, shuffle, etc.)

### States

- [ ] Interaction (default, focus, hover, active, disabled, dragged, etc.)
- [ ] Selected (if a user needs to distinguish between active or inactive content)
- [ ] Steps (if a user needs to move through steps toward the completion of a task)
- [ ] Error (if a user needs to complete a task or fix an issue before proceeding)
- [ ] Severity (if a range of status options need to be communicated to a user)
- [ ] Boolean (if on or off are the only actions available to a user, literally or semantically)
- [ ] Skeleton loading (if a component might load slower for a user than expected)
- [ ] Empty (if data cannot be displayed without user input; visit [this page](https://www.patternfly.org/v4/components/empty-state) for examples)
- [ ] Fallback (if JavaScript is disabled or it fails to load) [Consult with the assigned developer first to determine if this is necessary to design]

### Content

- [X] Alignment options (left, center, or both)
- [ ] Character counts (minimum and maximum)
- [ ] Links (which links are inline, external, redirects, etc.)
- [ ] Translations (German, Japanese, Hebrew, etc.)
- [X] Edge cases or limitations (overflow, truncate, wrap, etc.) [It is not required to include all of these specs, but keep them in mind]

**Comment by marionnegp** [comment]
@brianferry, the [XD link](https://xd.adobe.com/view/067ac1e2-5343-4dd7-adf4-ef3e18a91387-5329/) now also shows two screens at the end with examples of the stats in context. They look the same as the screenshots under the Purpose section, but spacing has been updated. You're also able to check sizing, colors, etc. by clicking the </> icon on the right.

**Comment by marionnegp** [comment]
@brianferry, icons used with <rh-stat> should be #151515 for light theme and #fff for dark theme.

**Comment by brianferry** [comment]
@marionnegp - Do we have an expectation that we will be implementing an icon library in rhds or are we primarily expecting users to put in pfe-icons? I don't think it would matter too much to the styling of the app but just double checking before I include pfe-icons in my demo files.

**Comment by brianferry** [comment]
Also, should we include a loading state for this component in case the data that is being pulled for the statistic is not ready yet?

**Comment by marionnegp** [comment]
@markcaron, what do you think about implementing an icon library in rhds?

@brianferry, for the loading state, are you talking about a live stat component needing to pull a number from a data source?

**Comment by brianferry** [comment]
Yeah, basically if the user was going to pull the stats for something based on data coming back from an API rather than static content I could see them also wanting the ability to put the stat component as `loading` until they have their data back.  This can also be something we add later on if we'd like to though if it's not a current use case.

**Comment by marionnegp** [comment]
It doesn't look any stats are using an API, but it's a good thought. `<rh-spinner>` might be good for something like this, since the stat should load fairly quickly. Can we add this later?

**Comment by brianferry** [comment]
Yup, no problem, just wanted to throw that out there in case it should be a consideration.  Thanks @marionnegp

**Comment by brianferry** [comment]
@bennypowers @heyMP @zeroedin 

Been taking a look at this and wanted to get some feedback from something I was thinking about.  So the way it's outlined it looks like the main things that we would like the user to be able to do is input the own text / icons into the `rh-stat` component with the four outlined sections:

`rh-stat-title`
`rh-stat-description`
`rh-stat-statistic`
`rh-stat-icon`

Given that we are likely not expecting the user to be putting their own HTML into the element I am thinking it makes more sense to make the expected markup something like this so they will just need to add the text and the elements will handle their own styling. 

```html
<rh-stat>
  <rh-stat-icon></rh-stat-icon>
  <rh-stat-title></rh-stat-title>
  <rh-stat-statistic></rh-stat-statistic>
  <rh-stat-description></rh-stat-description>
</rh-stat>
```

Though we could also go with slots and do something like this which would be more flexible 

```html
<rh-stat>
  <span slot='icon'></span>
  <span slot='title'></span>
  <span slot='statistic'></span>
  <span slot='description'></span>
</rh-stat>
```

Wanted to get some feedback on this and see which we think is better for our use-case here.

**Comment by heyMP** [comment]
I think we are leaning toward using slots and fallback slot content as much as possible over creating new components for everything.  So in the case of icon, we could have a slot for icon AND having an icon `@property` or `@state`.

```
render() {
  return html`
    ...
    <slot name="icon">
    </slot>
    ...
  `
}
```

**Comment by brianferry** [comment]
@marionnegp - Just double checking, from the UX documents it looks like we will either have the title or the icon present in a rh-stat component but not both at the same time, is that correct?

**Comment by marionnegp** [comment]
Hm, I hadn't considered that variation. I think we can offer it just in case and use the same 16px margin below the icon. 

CC: @coreyvickery

**Comment by bennypowers** [comment]
@brianferry def slots > mandatory custom children, in this case.

you can use `hasSlotted` and `classMap` or `?hidden` to hide one or the other, say if `title` is meant to take precedence over `icon`

**Comment by brianferry** [comment]
@bennypowers yeah that's what I was thinking, if we have an order of precedence it won't be hard to implement that order of operations.  We can see how it looks both ways and see what we think

**Comment by marionnegp** [comment]
@brianferry, I wanted to follow up on the icons. We'll be moving icons into an RHDS library, so icons in the demo will have to be updated then.

**Comment by brianferry** [comment]
Update on this ticket, got approval for the rh-stat component and the PR has been merged.  The branch is out there along with the docs page I had set up for the demo (docs page is not live on ux.redhat.com, just in our files) so that is available whenever anyone would like to take a look at those. Not sure if this should be moved to done at this point and create another issue for the docs or not
