### ISSUE TITLE
[feat] Spinner component

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#282]
### Description

RHDS needs an updated spinner that can be used when other progress components don't apply or when the loading time is short.

**Variations:**

- default
- medium
- small
- default with text label
- medium with text label
- small with text label

### Acceptance Criteria

- [x] Design done
- [ ] Development done

### Image
<img width="637" alt="Screen Shot 2022-05-18 at 11 08 49 AM" src="https://user-images.githubusercontent.com/95588923/169075196-c711935a-e6c6-4b4b-9638-e790fe989bf6.png">

### Link to design doc

[https://xd.adobe.com/view/4c7f069d-7c25-4422-9b72-c8e1cf380d47-192c/](https://xd.adobe.com/view/4c7f069d-7c25-4422-9b72-c8e1cf380d47-192c/)

### Other resources

Here's some info from the [Trello task](https://trello.com/c/e9WgwuOo/49-new-component-pfe-spinner):

- CSS in UXDD Red Hat theme to make PFE-Progress-Indicator ui-accent blue has been implemented/released.
- [PatternFly 4 - Spinner](https://www.patternfly.org/2020.04/documentation/react/components/spinner/)
- [Progress Indicator - PatternFly Elements](https://patternflyelements.com/components/progress-indicator/)
- Here's an example of [pfe-progress-indicator on Product Trials](https://heymp-product-trial-main.surge.sh/?processing=true)
- Research into why PFE's progress indicator was [renamed to spinner](https://docs.google.com/document/d/1NDIAp0esASIanP9FP-iVlThqxkBxNujAXdgR9ZBd5xY/edit?usp=sharing) for RHDS

**Comment by marionnegp** [comment]
@coreyvickery  @ronniemcbride, what should be considered the default size?

**Comment by coreyvickery** [comment]
@marionnegp I would say the `Large` size should be the default.

**Comment by marionnegp** [comment]
@coreyvickery, what do you think about this dark theme version?

![Screen Shot 2022-05-23 at 12 31 59 PM](https://user-images.githubusercontent.com/95588923/169866085-d30dac69-d8fe-4d5c-af36-f5b6d39a5586.png)

XD link: https://xd.adobe.com/view/4c7f069d-7c25-4422-9b72-c8e1cf380d47-192c/screen/62ca627e-a852-4402-b945-5766eff397a1/specs/

**Comment by marionnegp** [comment]
Updated the dark theme spinner by changing the background color to #3C3F42: https://xd.adobe.com/view/4c7f069d-7c25-4422-9b72-c8e1cf380d47-192c/screen/62ca627e-a852-4402-b945-5766eff397a1/specs/
