### ISSUE TITLE
[feat]: <pfe-modal> to <rh-dialog> ready to migrate

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#283]
### Tag Name

rh-dialog

### RHDS Only

- [ ] The component will be **RHDS only**, delete the PFE component once published

### Name changes
When migrating `<pfe-modal>`, we should consider changing the name to `<rh-dialog>` to be more inline with [W3C](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) and community standards.

In RHDS, perhaps we should combine the terms like, "Modal Dialog" similar to [WAI Best Practices example](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html). Implementation should be `<rh-dialog>` to be closer to the HTML element.

Within PFE, we'd keep `<pfe-modal>` to match [PF4's docs](https://www.patternfly.org/v4/components/modal).

### Additional Info

We need to also bring in design updates from the old [PFE issue for modal](https://github.com/patternfly/patternfly-elements/issues/811).

**Comment by markcaron** [comment]
https://github.com/patternfly/patternfly-elements/issues/811

**Comment by coreyvickery** [comment]
@markcaron Please make sure these changes get incorporated during my absence.

**Comment by bennypowers** [comment]
@ronniemcbride @marionnegp can you link the XD with styles view for this?

**Comment by marionnegp** [comment]
@bennypowers, here are the [specs for `<rh-dialog>`](https://xd.adobe.com/view/e925215c-e21c-4f4d-9af1-44d2fbcb7194-bc76/).

**Comment by bennypowers** [comment]
#288 ready for review
