### ISSUE TITLE
[bug] [docs] Sample component on Accordion page is broken

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#300]
### Describe the bug

The sample accordion component is showing the text but none of the accordion styling. I don't see this happening on other accordions, like the one on the [Red Hat Advanced Cluster Management for Kubernetes](https://www.redhat.com/en/technologies/management/advanced-cluster-management) page.

### Which Component?

pfe-accordion

### Steps to reproduce

View https://ux.redhat.com/components/accordion/ on Chrome, Firefox, or Safari.

### Expected behaviour

This text should be in accordions

### Screenshots

![Screen Shot 2022-01-19 at 11 05 42 AM](https://user-images.githubusercontent.com/95588923/169842793-4ef0b3aa-d28d-4187-9832-e674d62ca7bc.png)

### Element HTML

```HTML
<pfe-accordion>
</pfe-accordion>
```

### Operating System (OS)

macOS

### Browser

Chrome, Safari, Safari iOS, Firefox

### More browser information

- Chrome 101.0.4951.64
- Firefox 91.9.0esr
- Safari 15.4
- Safari iOS 15.4

**Comment by bennypowers** [comment]
It's worse than that, all the pfe- and rh- elements on all pages are not loading 🙈 

My bad! PR up: #325
