### ISSUE TITLE
[feat]: <rh-accordion> ready to migrate

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#303]
### Tag Name

rh-accordion

### RHDS Only

- [ ] The component will be **RHDS only**, delete the PFE component once published

### Additional Info

XD link: https://xd.adobe.com/view/0cefed4d-4b3c-4e19-85b9-5bbbe09868ca-59bc/

- caret icon is lighter and points down when accordion is collapsed
- updated font sizes
- new variant: small size

CC: @coreyvickery

**Comment by marionnegp** [comment]
**Notes from Trello:**

- Changes to the Accordion component were made so it looks better when used on other web properties, like Customer Portal.

**Comment by bennypowers** [comment]
Blocked on https://github.com/patternfly/patternfly-elements/issues/2047

**Comment by paigenotfound404** [comment]
Renamed to rh-accordion, was mis labeled pfe-
