### ISSUE TITLE
[docs] New Component section - Design Tokens

### ISSUE THREAD

**Issue by methomps** [RedHat-UX/red-hat-design-system#315]

**Comment by methomps** [comment]
BLOCKED: Documentation needs written

**Comment by coreyvickery** [comment]
Current PR.

https://github.com/RedHat-UX/red-hat-design-system/pull/633

**Comment by markcaron** [comment]
New plan with this issue: https://github.com/RedHat-UX/red-hat-design-tokens/issues/54

**Comment by paigenotfound404** [comment]
Closed and being tracked in #633 and https://github.com/RedHat-UX/red-hat-design-tokens/issues/54
