### ISSUE TITLE
[feat] <rh-blockquote>

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#319]
### Description

RHDS needs a blockquote component

### Acceptance Criteria

- [X] Design done
- [ ] Development done

### Image

![image](https://user-images.githubusercontent.com/1890950/170098545-0c3e835a-0eae-460a-a286-06e05b26d52b.png)

### Link to design doc

https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/f5c8e80c-83cb-4ae9-8e92-5991c39e738b/

**Comment by markcaron** [comment]
Ready for development: #318

**Comment by methomps** [comment]
@coreyvickery can we move this to status "Done" on the designer board? I see @Nouveau has an issue for the development phase.

**Comment by coreyvickery** [comment]
@methomps Yes. I might have some more variations for Em to work on, but design is done.
