### ISSUE TITLE
[docs] New Component page - Showcase

### ISSUE THREAD

**Issue by methomps** [RedHat-UX/red-hat-design-system#321]
(page showing examples of components in use on different websites)

https://docs.google.com/document/d/1hlcV7yPL3Mvv6F6IGpxDriMkTVJqzEJnw-3grO2mMEs/edit#bookmark=id.pyng3vvk37cv

**Comment by markcaron** [comment]
Closing for now. If we determine we need a page to showcase use of our components, we'll make a new issue.
