### ISSUE TITLE
[feat] <rh-cta>

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#333]
### Description

`<pfe-cta>` should be migrated to RHDS. when `<rh-cta>` is ready, `<pfe-cta>` will no longer be updated.

### Acceptance Criteria

- [ ] Design done
- [ ] Development done

### Other resources

See #238, design should cover those edge cases

**Comment by methomps** [comment]
Referencing similar issue reported in patternfly-elements repo: https://github.com/patternfly/patternfly-elements/issues/679

**Comment by heyMP** [comment]
PR #349

**Comment by bennypowers** [comment]
@RedHat-UX/designers on [ux-dot](https://ux.redhat.com/components/call-to-action/#primary-and-primary-video), for the primary variant, hover state, the background colour is `#d40000`. This colour does not currently appear in our [design tokens](https://red-hat-design-tokens.netlify.app/#color). Should I take the closest available? spin out a custom variable? Add it to the tokens?

**Comment by marionnegp** [comment]
My vote would be to use `--rh-color-brand-red-dark` since its brand red hover is one of its use cases anyway.

**Comment by bennypowers** [comment]
@RedHat-UX/developers and @RedHat-UX/designers and also @dcaryll and @markcaron I'm thinking about "priority" and "variant". In light of how the UX-dot docs lay things out, and considering that `<pfe-cta>` will be deprecated, I'd like to make some changes for the first release of `<rh-cta>`:

`<pfe-cta>` has both `priority="'primary'|'secondary'"` and `variant="wind"` attributes, which at least on an HTML level can be combined arbitrarily, leading to combinations which were not specified in the design:

```html
<!-- LEGAL: default priority, default variant -->
<pfe-cta></pfe-cta>
<!-- LEGAL: primary priority, default variant -->
<pfe-cta priority="primary"></pfe-cta>
<!-- LEGAL: secondary priority, default variant -->
<pfe-cta priority="secondary"></pfe-cta>
<!-- ILLEGAL: default priority, wind variant -->
<pfe-cta variant="wind"></pfe-cta>
<!-- ILLEGAL: primary priority, wind variant -->
<pfe-cta priority="primary" variant="wind"></pfe-cta>
<!-- LEGAL: secondary priority, wind variant -->
<!--      equivalent to brick variant on ux-dot -->
<pfe-cta priority="secondary" variant="wind"></pfe-cta>
```

The ux-dot docs phrasing simplifies this somewhat, providing four (x2) variants, in order of importance (ascending):
1. default
2. brick
3. secondary
4. primary

with each of those having a parallel video variant (which, let's say is covered by the `icon` attribute, which could take any icon name)

for the sake of simplicity, and to align with the docs, I'd like to remove the priority attribute and replace it with a single, optional `variant` attr, which could have the values `'primary'|'secondary'|'wind'`. I gather that shouldn't be too controversial...

Another idea I had might be a little more :hot_pepper:: I propose inverting the default importance, such that without a `variant` attribute, we'd see a red rectangle, and if `variant="tertiary"`, we'd have the blue-text-with-arrow variant

![variants](https://ux.redhat.com/assets/cta/cta-sample.svg)

So in this image, left to right would be 

```html
<rh-cta><a>Primary</a></rh-cta>
<rh-cta variant="secondary"><a>Secondary</a></rh-cta>
<rh-cta variant="brick"><a>Brick</a></rh-cta>
<rh-cta variant="tertiary"><a>Default</a></rh-cta>
```

I believe that would align better with the docs on ux-dot, and at least in my mind, defaulting to primary makes more sense, but you tell me: does that track with how pfe-cta is used across various properties today?

**Comment by dcaryll** [comment]
The reason we didn't default to primary was because we wanted it to be clear that using more than one primary CTA should be very intentional. So in the CMS, when someone chooses a CTA without specifying which type they want, it won't default to the primary CTA because they should be used more sparingly. 

There was a lot of conversation back when we first chose the names of these, with a big consideration being a separation of style from naming. @markcaron would have a lot more history/context.

**Comment by bennypowers** [comment]
@dcaryll I wonder if that could be handled at in patternkit then. does patternkit allow those kinds of validations?

**Comment by dcaryll** [comment]
@bennypowers yes, definitely. I guess you could make the same case when using raw elements (that the default isn't a primary CTA), but I also don't know how much the code needs to help enforce the UX recommendations.

**Comment by bennypowers** [comment]
> My vote would be to use `--rh-color-brand-red-dark` since its brand red hover is one of its use cases anyway.

@marionnegp does it make sense then to use `--rh-color-brand-red-darker`, `#8f0000` for the active state?

**Comment by bennypowers** [comment]
pfe-cta v1 fires a `pfe-cta:select` event, which is basically a wrapper over the regular `click` event, but with some of it's properties compiled in a data property. I'd like to remove this feature in rh-cta, saving kb over the wire and complexity in our sources. users who need the data found in the pfe-cta:select event can still get it with a few lines of javascript:

```js
for (const cta of $$('rh-cta')) {
  cta.addEventListener('click', function(originalEvent) {
    const { href, text, title } = cta.cta;
    const color = cta.colorPalette;
    const type = cta.variant;
    const data = { href, text, title, color, type };
    doSomethingWith(data); // corresponds to pfeCtaSelectEvent.dataa
  });
}
```

Checking in with @kylebuch8 does that make sense to you?
