### ISSUE TITLE
[FTS/WebRH] Dynamic form | Update form styles to match design system

### ISSUE THREAD

**Issue by methomps** [RedHat-UX/red-hat-design-system#354]
Form in the design kit includes the correct styles.
https://xd.adobe.com/view/d20a1c17-375c-4c7f-6827-5fe2f8c2d92f-a43b/screen/018afc6f-a0fc-4064-b0b4-632b4191cc2f

System FEDs would be the team who can make visual styling updates to dynamic form, so the next step was to evaluate what's wrong on production versus what's in the kit, and pass those changes back to our system FEDs

https://www.redhat.com/en/rhpt-trial-request-review-form (example of DYFOv2 form)

**Comment by methomps** [comment]
Copying over this comment/question from @marionnegp from our Trello card:
Is this task about the FTS pattern I showed you last week: https://xd.adobe.com/view/af55b030-ce17-4a90-8587-3f0891d20ead-fa06/ ? This one uses the D9 form from the main kit.

**Comment by markcaron** [comment]
@marionnegp this will need an update, especially since we're in Figma now. Should we close? Or is this still relevant?

**Comment by bennypowers** [comment]
we'll reopen with up to date info at a later milestone
