### ISSUE TITLE
[feat] Create `<rh-site-status>` element

### ISSUE THREAD

**Issue by methomps** [RedHat-UX/red-hat-design-system#356]
### Description

New "status indicator" component that would be injected into the new unified footer for sites looking to report out on site outage.

The current implementation of the indicator shows the operational status across all of status.redhat.com and is not site specific. Notes from early conversations around this as it relates to the unified footer: https://docs.google.com/document/d/1vZ2taPSsG2MnpujdwpXxZvhH7ssnQgfAPVrzTPfaH4A/edit#bookmark=id.vq7rdtmnvsdg

Redhat.com is not currently included on status.redhat.com for reasons:
Per Danielle Smith "However, the complexity around determining what should be displayed on this page is not an XS LoE for our dev and infra teams.  Based on the comments in this thread, and what we learned this morning, it does not make sense to build out the comms and support processes to add it to the status-dot page at this time." 

### Acceptance Criteria

- [X] Design done
- [ ] Development done

### Link to design doc

https://www.figma.com/file/IoKYfBlrcx2kXIGdC22Gjq/Footer---status-indicators?type=design&node-id=0%3A1&mode=dev

### Other resources

some thoughts on development:
- if we make the various status texts configurable via slots (with english fallback), then 18n becomes the consumer's responsibility (e.g. the cms)
- this being a red hat element, not a pfelement, we can rely on convention and have something like

`<rh-site-status site-ids="613,770">
  <span slot="ok">All systems operational</span>
</rh-site-status>`

**Comment by coreyvickery** [comment]
Updated issue with Figma link.

**Comment by coreyvickery** [comment]
@markcaron @hellogreg Can you please check with Kelsey if this is still a priority? Otherwise, proposing to move it to the `Chansey` release.

**Comment by kelsS** [comment]
@coreyvickery I would say it is still a priority. @kylebuch8 what do you think?

**Comment by bennypowers** [comment]
Considering the US holiday calendar, we must delay this important feature to Chansey.

**Comment by markcaron** [comment]
Free to use @zeroedin's CodePen: https://codepen.io/zeroedin/pen/QWoNbzL

**Comment by markcaron** [comment]
@heyMP @zeroedin where are we on this? Are there any blockers?

**Comment by markcaron** [comment]
`Closes` in PRs aren't closing issues for some reason.
