### ISSUE TITLE
[feat] Switch component

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#365]
### Description

Create a switch component like https://www.patternfly.org/v4/documentation/core/components/switch

We need to support:
- With a label
- Without a label
- Disabled state

### Acceptance Criteria

- [x] Design done
- [ ] Development done

### Image
![Form - Switch - light theme](https://user-images.githubusercontent.com/45767595/171976062-4e2d4d96-333b-41ef-bc47-e1ee88699a28.png)

### Link to design doc

https://xd.adobe.com/view/d20a1c17-375c-4c7f-6827-5fe2f8c2d92f-a43b/screen/4074c4b7-04ae-441e-80fd-21210d7680d2

### Other resources

- Switch in [PatternFly 4](https://www.patternfly.org/2020.04/documentation/core/components/switch)
- Old Github issue in the PFE repo: [#736](https://github.com/patternfly/patternfly-elements/issues/736)
- Closed WIP PR for switch component in PFE repo: [#767](https://github.com/patternfly/patternfly-elements/pull/767)

**Comment by marionnegp** [comment]
I think we'll need to add states and maybe a dark theme version for this before it goes to dev. @coreyvickery, do you want to do that, or would you prefer @ronniemcbride or me to do it?

**Comment by coreyvickery** [comment]
Dark theme below, I will have Liz Wood update the dev link ASAP.

![Form - Switch - dark theme](https://user-images.githubusercontent.com/45767595/171976094-85592e85-b757-4166-9ea0-359d51926b76.png)

**Comment by coreyvickery** [comment]
@marionnegp Dark theme below, I will have Liz Wood update the dev link ASAP.

![Form - Switch - dark theme](https://user-images.githubusercontent.com/45767595/171976134-4e65dffb-1ad8-434e-8636-2359c68a5d77.png)

**Comment by marionnegp** [comment]
@coreyvickery, white and #73BCF7 don't pass a color contrast check. What do you think about some of the tweaks in [this XD link](https://xd.adobe.com/view/d0680c4b-ac31-483f-95ae-a8d511dd9898-853b/)?

**Comment by marionnegp** [comment]
Yeah, that was the section I was looking at. The black on blue wasn't really my fave either. 

It doesn't look like #FFF on #2B9AF3 passes the contrast check, even with large text. I see the drop shadow behind the circle, but is that enough to create contrast?

**Comment by bennypowers** [comment]
The implementation here can be mostly CSS

and let's also make sure to open an issue in the [1:1 milestone](https://github.com/patternfly/patternfly-elements/milestone/5)

**Comment by marionnegp** [comment]
@coreyvickery  @ronniemcbride, what do you think about [outlining the switch](https://xd.adobe.com/view/d0680c4b-ac31-483f-95ae-a8d511dd9898-853b/screen/5053d65c-5fee-4b5b-bf49-9597f5e10b75) instead of adding a dark theme blue?

**Comment by ronniemcbride** [comment]
@marionnegp I favor the outlined version over the solid version. The other way is more consistent with the light theme, but the outlined version reads better.

**Comment by coreyvickery** [comment]
@marionnegp I made some updates in the kit for Switch.

<img width="884" alt="Screen Shot 2022-08-23 at 3 26 40 PM" src="https://user-images.githubusercontent.com/45767595/186277065-014a2797-7516-43bc-a694-36813a877db8.png">

**Comment by coreyvickery** [comment]
@marionnegp I left some comments in your light theme XD link.

**Comment by coreyvickery** [comment]
@marionnegp I left some comments in your XD link.

**Comment by coreyvickery** [comment]
@marionnegp I included a couple more states in the kit and I also updated the dark theme components to match your proposed specs. This is just about done I would say, we just need to finalize the interaction states and some other accessibility specs.

<img width="884" alt="Screen Shot 2022-08-23 at 3 26 40 PM" src="https://user-images.githubusercontent.com/45767595/186279146-dbe5568e-72da-4c21-a04e-4e1bbfe9e84e.png">

<img width="884" alt="Screen Shot 2022-08-23 at 3 46 32 PM" src="https://user-images.githubusercontent.com/45767595/186279227-793bf556-75d6-4b44-8655-2736e8c3f2e1.png">

**Comment by marionnegp** [comment]
@coreyvickery, talked to Mark about the dark theme, and he thinks we should make both themes either outlined or filled. 

The switch background will need to have a contrast ratio of 4.5:1 against the page/section background. The toggle and checkmark icon need to have a contrast ratio of 3:1 against the switch background.

**Comment by coreyvickery** [comment]
@marionnegp Okay, I made some changes.

## Light theme

No changes.

## Dark theme

<img width="882" alt="Screen Shot 2022-08-26 at 7 47 03 AM" src="https://user-images.githubusercontent.com/45767595/186931612-9f57f41c-931e-4be8-8854-6d2a563c7bdc.png">

### On
- Switch surface on primary background: `#2b9af3` (6.1 against `#151515`)
- Switch surface on secondary background: `#2b9af3` (5.21 against `#212427`)
- Toggle: `#ffffff` (2.99 against `#2b9af3`)
- Label text on primary background: `#ffffff` (18.26 against `#151515`)
- Label text on secondary background: `#ffffff` (15.59 against `#212427`)

### Off
- Switch surface on primary background: `#8a8d90` (5.47 contrast ratio against `#151515`)
- Switch surface on secondary background: `#8a8d90` (4.67 contrast ratio against `#212427`)
- Toggle: `#ffffff` (3.33 contrast ratio against `#8a8d90`)
- Label text on primary background: `#d2d2d2` (12.07 against `#151515`)
- Label text on secondary background: `#d2d2d2` (10.31 against `#212427`)

@markcaron Looks like the `On` toggle fails by ONLY .01 when using the `blue-250` token for the dark theme Switch surface. `blue-200` is too dark and `blue-400` is too bright. Can we proceed with `blue-250` knowing `2.99:1` is essentially `3:1`?

(P.S. I don't know why the order is `200`, `250`, and then `400`, I will create an issue to change `250` to `300`.)

**Comment by coreyvickery** [comment]
@marionnegp Where did we leave off with this?

**Comment by marionnegp** [comment]
I think I got the contrast ratios switched, so it should actually be:

- The toggle and checkmark icon need to have a contrast ratio of 4.5:1 against the switch bg
- The switch bg needs a contrast ratio of 3:1 against the page/section bg

I'm still working on finding a blue that works for dark theme.

**Comment by coreyvickery** [comment]
@marionnegp Not sure that's possible.

### blue-400 (#0066cc) as a background
`#ffffff` > `#0066cc` = 5.56
`#0066cc` > `#151515` = 3.28 (primary BG)
`#0066cc` > `#212427` = 2.8 (secondary BG)
`#0066cc` > `#3c3f42` = 1.9 (tertiary BG)

Takeaway: Check/toggle passes, but the background doesn't pass on two gray background colors.

- - -

### blue-300 (#2b9af3) as a background
`#ffffff` > `#2b9af3` = 2.99
`#0066cc` > `#151515` = 6.1 (primary BG)
`#0066cc` > `#212427` = 5.21 (secondary BG)
`#0066cc` > `#3c3f42` = 3.54 (tertiary BG)

Takeaway: Check/toggle doesn't pass, but the background passes on all three gray background colors.

- - -

If we can't pursue an outlined version of this component for dark theme, it seems there are some compromises we have to accept.

cc @markcaron

**Comment by marionnegp** [comment]
@coreyvickery, I looked through some toggle/switch components from other design systems, and the ones that had a dark theme version used a dark color for the [toggle circle](https://xd.adobe.com/view/ca84929e-6ad8-4362-8fc7-27c39be745c9-9fd7/screen/5c38cb58-0664-4a9a-89df-41f1a5d09638).

I also tried an [outlined version of the light theme](https://xd.adobe.com/view/ca84929e-6ad8-4362-8fc7-27c39be745c9-9fd7/screen/6e2fe688-6dfc-4c5b-899c-d1a1450fe631), but I don't think the state changes are as clear.

**Comment by marionnegp** [comment]
Made updates to the design leads' feedback in Dec 2022: [XD link](https://xd.adobe.com/view/ca84929e-6ad8-4362-8fc7-27c39be745c9-9fd7/). @coreyvickery @markcaron, do you think this is ready for dev?

Feedback:

- [ ] The BG for the off state is #8a8d90 which passes 3:1 but not 4.5:1 with white
- [ ] Message text can be hard to read in dark theme
- [ ] Will need disabled color mocked up

**Comment by coreyvickery** [comment]
@marionnegp @markcaron Seems ready to go to me.

**Comment by marionnegp** [comment]
@coreyvickery @markcaron, I created a new ready for dev issue for `rh-switch`! #770

**Comment by marionnegp** [comment]
@coreyvickery, I've updated `rh-switch` in the XD kit but haven't published updates yet. I left out the `disabled with check mark` variant because I noticed there isn't one in PF or PFE.
