### ISSUE TITLE
[feat]: <rh-avatar> ready to migrate

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#368]
### Tag Name

rh-avatar

### RHDS Only

- [ ] The component will be **RHDS only**, delete the PFE component once published

### Additional Info

Will likely need additional discussion around the [RHDS spec](https://ux.redhat.com/components/avatar/) (and its inclusion of name and title) vs. the [PFE spec](https://patternflyelements.org/components/avatar/).

**Comment by markcaron** [comment]
@RedHat-UX/designers we'll need to make sense of the spec differences between RHDS and PFE. Do we want to include text/attributions on the right?

<img width="307" alt="image" src="https://user-images.githubusercontent.com/1890950/172186806-152fbd42-450a-49e6-a4ae-d75f33387c9e.png">

IMO, I feel like `avatar` is simply the image itself. The title/attributions seem to be extraneous. But, is this something we'd want to offer as a slot option in RHDS only?

**Comment by KrystalMoore16** [comment]
I can see this either being a variation, or a separate parent component that consumes an avatar and adds the attributions to the right, @markcaron. I agree that an avatar is simply the image itself, so we may want to lean towards the latter.

There's certainly a need for avatar + text/attributions on the Customer Portal.

**Comment by coreyvickery** [comment]
@markcaron What Krystal said makes sense to me.

**Comment by coreyvickery** [comment]
@Nouveau Might want to take into account the above when migrating. Let us know if you have any further questions.
