### ISSUE TITLE
[feat]: <rh-badge> ready to migrate

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#369]
### Current Designs

![Image](https://user-images.githubusercontent.com/95588923/187244163-5d9fbf0e-9b67-4f90-b638-b3c0ef58671e.png)

### Design Doc

[Latest XD mockup](https://xd.adobe.com/view/b9ff51f7-08cd-4e68-b290-a64601198600-ecac/)

### Tag Name

rh-badge

### RHDS Only

- [ ] The component will be **RHDS only**, delete the PFE component once published

### Additional Info

Doesn't currently exist in RHDS design specs, but exists in [PFE](https://patternflyelements.org/components/badge/) and [PF4](https://www.patternfly.org/v4/components/badge).

**Comment by markcaron** [comment]
@RedHat-UX/designers should we go ahead and implement PFE's design options as RHDS? Should be easy to tweak down the road if needed.

**Comment by marionnegp** [comment]
That seems fine to me. The dark red bg for critical badges (#A30000)  and the red bg for important badges (#C9190B) don't use our tokens, so I think we should adjust those first. Maybe #5f0000 for critical and #be0000 for important?

**Comment by coreyvickery** [comment]
@KrystalMoore16 Can you help push this forward if another team needs to give input?

**Comment by KrystalMoore16** [comment]
@coreyvickery, can you bring this to the leads sync? We don't need to come up with colors on the call, but let's talk about how we can collaborate on this and then create AI's for our teams to review. We'll want Michael's input too since PF only offers two colors like I mentioned.

**Comment by marionnegp** [comment]
I sent an email to the design leads about [our current badges](https://xd.adobe.com/view/ef85193d-ff26-468b-9154-11b8e5185449-bad6/). Waiting to hear back about the following questions:

- Do we want to pare down the number of colors and badge types?
- Do we want more or different colors?
- Are there any other changes you think should be made?

**Comment by marionnegp** [comment]
Feedback from design leads:

- [ ] make PFE badge look like PF's
- [ ] keep the yellow, green, and two red badges
- [ ] use design tokens for colors (We told them that this will allow us to easily change hex codes if we need to.)

**Comment by marionnegp** [comment]
Ready for dev (issue #504)
