### ISSUE TITLE
[feat]: <rh-button> ready to migrate

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#370]
### Tag Name

rh-button

### RHDS Only

- [ ] The component will be **RHDS only**, delete the PFE component once published

### Additional Info

**PFE**
[PFE spec](https://patternflyelements.org/components/button/) changing to [PF4 spec](https://www.patternfly.org/v4/components/button)
<img width="657" alt="image" src="https://user-images.githubusercontent.com/1890950/172190766-b51b05c1-e095-47e8-a62a-d92a56b60f02.png">

**RHDS**
[RHDS spec](https://ux.redhat.com/components/button/)
<img width="658" alt="image" src="https://user-images.githubusercontent.com/1890950/172190702-22527c90-2c77-4324-a43d-fefb251b04c6.png">

### Considerations

- [Stateful buttons](https://xd.adobe.com/view/abcb0030-a679-4c79-b620-d1c419c94849-fe98/)

**Comment by bennypowers** [comment]
Blocked on https://github.com/patternfly/patternfly-elements/pull/2042
