### ISSUE TITLE
[feat] `<rh-auth>` ready for development

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#373]
### Description

For PFE 2.0 to utilize the authentication state we need a component that will broker the login/logout process.  One exists in Product Trials currently.  Mike is exploring what it would look like to move that functionality into an “rh-auth” web component.

Example: https://heymp-product-trial-main.surge.sh/

Demo (click the login link in the nav): https://gitlab.corp.redhat.com/uxdd/rh-product-trial/-/blob/main/demo/index.html#L56-60

### Acceptance Criteria

- [ ] Design done
- [ ] Development done

**Comment by markcaron** [comment]
@heyMP where are we on this? Should we close this?
