### ISSUE TITLE
[feat] <jumplinks>

### ISSUE THREAD

**Issue by eohammond** [RedHat-UX/red-hat-design-system#376]
### Description

This might be more of a conversation than a request but I wanted to get it on the radar. 

From [user research on Jumplinks](https://docs.google.com/presentation/d/1jBS06VMT1vVM1loM0Xs_IlEDHZ0KXnQUU-kq34RuHG8/edit#slide=id.gd2099cdca2_0_34) a participant who was using a mobile device told us that her expectation of using jumplinks was to:

1. Open the jumplinks panel
2. Select a link from the panel
3. The panel automatically closes after she selects a link.

You can experience this on the [Partner hub](https://www.redhat.com/en/partners) in mobile view. Admittedly, only one user was using a mobile device in the study—the others didn't see any issue on desktop. But Corey, Wes, Hadley and I looked at the functionality and agree with that user. If you open the panel on mobile and the link you select takes you to your destination but the panel doesn't close it a) takes up a lot of space on the small display and b) hides the header of the content that you selected. It does not feel like expected behavior.

Separately, we have a different implementation of jumplinks, labeled "Table of contents" on [this resource page](https://www.redhat.com/en/resources/self-managed-openshift-sizing-subscription-guide#section-2) In mobile it automatically closes once a user has selected a link.  

### Suggested solution

On mobile, automatically close the jumplinks panel after the user selects a link. The [resources section](https://www.redhat.com/en/resources/self-managed-openshift-sizing-subscription-guide#section-3) example mentioned above does this well. 

### Additional context

We never quite nailed the anchor position of horizontal jumplinks so we're choosing to hide those from mobile. We think it would be useful to have the option to hide all jumplinks from mobile displays in case they're not as helpful there. For instance maybe we only have a few jumplinks and the panel takes up more space on mobile than is useful, or maybe we hide it in case jumplinks are on a page with secondary navigation to conserve screen space. 

This is a lot of info so feel free to send questions or add to the next System UX discovery if you'd like to discuss.

**Comment by coreyvickery** [comment]
@marionnegp Let's discuss this on 7/8.

**Comment by markcaron** [comment]
[#539](https://github.com/RedHat-UX/red-hat-design-system/issues/539)
