### ISSUE TITLE
Component Status Tables

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#397]
Component status tables are missing on component pages e.g. https://ux.redhat.com/components/accordion/

**Comment by heyMP** [comment]
PR: #396

**Comment by bennypowers** [comment]
Discussion at standup:
- let's revert the frontmatter approach
- let's hide the empty "Component status" headers for now
- let's re-design the feature:
  - let's only advertise our products

To that last point, we'd remove things like "this is available in drupal", since RHDS has many consumers, not just drupal, but we'd add things like "this has passed a11y review", "this is available as a design kit", etc

**Comment by marionnegp** [comment]
The `Link with icon` status table is showing up on the `Link` page, but it shouldn't be since they're separate components.
