### ISSUE TITLE
[feat]: <rh-tag> Ready to migrate

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#398]
### Tag Name

rh-tag

### RHDS Only

- [ ] The component will be **RHDS only**, extends from PFE component 

### Additional Info

pfe-label demo: https://patternflyelements.org/components/label/

**Comment by coreyvickery** [comment]
@markcaron This is being used more, especially on the redhat.com home page, can we bump it up in priority?

**Comment by paigenotfound404** [comment]
Waiting on #622

**Comment by zeroedin** [comment]
Design spec link: https://xd.adobe.com/view/d20a1c17-375c-4c7f-6827-5fe2f8c2d92f-a43b/screen/6a1953ee-4519-43d3-b02e-13453611c015/specs/

**Comment by zeroedin** [comment]
Renamed `rh-tag`
