### ISSUE TITLE
Objective: To drastically automate the documentation development process by templatizing a starter XD doc

### ISSUE THREAD

**Issue by ronniemcbride** [RedHat-UX/red-hat-design-system#411]
Objective: To drastically automate the documentation development process by templatizing a starter XD doc

**Feature request**
Create an XD template system that contains all the various section patterns that can be:
turned on and off.
Stacked and repositioned while maintaining spacing

**Next steps**
Audit the current ux.redhat.com site
Meet with the design system team members to work out XD approach and implementation
Create a how-to-use document and  added to the team process documentation

**UX Designer Deliverable:**
Final  XD template & usage documentation

_Originally posted by @ronniemcbride in https://github.com/RedHat-UX/red-hat-design-system/discussions/352_

**Comment by bennypowers** [comment]
Thanks for opening this Ronnie

I'm anxious to ship `design-tokens` for consumption in XD, could this be a place to do that? e.g. rolling tokens into the templates? Yes, ideally this would be automated (occur every time tokens makes a release) and decoupled (tokens can update independent of templates and vice-versa), but so far in my cursory investigation into the xd ecosystem, there's no straightforward way to accomplish that

**Comment by bennypowers** [comment]
Sounds good!

From a development perspective, it would be fairly straightforward to replicate the demo page at red-hat-design-tokens.netlify.app anywhere in ux-dot. Likewise, it would be easy to pull in individual sections of that page anywhere.

The _content_ for those sections is [defined within the tokens source](https://github.com/RedHat-UX/red-hat-design-tokens/blob/edb0b6c33c408b6b1aadc1b9400299d9159937b8/tokens/border.yml#L2-L7) as markdown strings, so we can replicate that anywhere.
