### ISSUE TITLE
[docs] update Navigation Components page

### ISSUE THREAD

**Issue by methomps** [RedHat-UX/red-hat-design-system#412]
Update our Navigation components page on ux.redhat.com: https://ux.redhat.com/components/navigation/
To include updated screenshots (absent of the 9 box site-switcher as one example)

**Comment by coreyvickery** [comment]
Final documentation page to be coded.

https://xd.adobe.com/view/a62d95e4-adc2-4774-8ca6-943d7258ead5-f37e/

**Comment by coreyvickery** [comment]
Closing because this work was done a long time ago.
