### ISSUE TITLE
[docs] Component XD UX Guidelines Template

### ISSUE THREAD

**Issue by methomps** [RedHat-UX/red-hat-design-system#413]
### Discussed in https://github.com/orgs/RedHat-UX/discussions/352

<div type='discussions-op-text'>

<sup>Originally posted by **ronniemcbride** June  2, 2022</sup>
Objective: To drastically automate the documentation development process by templatizing a starter XD doc

**Feature request**
Create an XD template system that contains all the various section patterns that can be:
turned on and off.
Stacked and repositioned while maintaining spacing

**Next steps**
Audit the current ux.redhat.com site
Meet with the design system team members to work out XD approach and implementation
Create a how-to-use document and  added to the team process documentation

**UX Designer Deliverable:**
Final  XD template & usage documentation
</div>

**Comment by coreyvickery** [comment]
@marionnegp Do you think we still need this after working with the new template I made?

**Comment by marionnegp** [comment]
@coreyvickery, nope, I think your template closes this issue.

**Comment by coreyvickery** [comment]
@ronniemcbride Thanks for making this issue and your work on this template, closing.
