### ISSUE TITLE
[docs]: New component page structure and adding code documentation (IA updates)

### ISSUE THREAD

**Issue by ronniemcbride** [RedHat-UX/red-hat-design-system#414]
> Discussed in https://github.com/orgs/RedHat-UX/discussions/351

## Objective

Advance and update the information architecture of ux.redhat.com for designer and developer guidance and development needs.

## Subtasks
- [x] https://github.com/RedHat-UX/red-hat-design-system/issues/606
- [x] https://github.com/RedHat-UX/red-hat-design-system/issues/610

## Request & Considerations

- Add support for code snippets and API documentation
- Add an accessibility section (dedicated page and in the context of each  component's page)
- Reorganize the content architecture and make it more audience-focused (designer, developer, and implementer) 
- Separate component pages into five tabbed sections of focus (`Overview`, `Styles`, `Guidelines`, `Code`, `Accessibility`) by doing so, designers, developers, and implementors should be clear about what information is essential to them
- Each tab should be a  template doc (for example, updates should be independent updates to that section without having to update the entire component page)
- We need the ability to implement page states, page states will allow us to link to a particular tab

### For instance:

elements/rh-footer/docs/overview.njk
elements/ rh-footer/docs/styles.njk
elements/rh-footer/docs/guidelines.njk
elements/ rh-footer/docs/code.njk
elements/rh-footer/docs/ accessibility.njk

**Comment by bennypowers** [comment]
Can we make a clear distinction in our new IA between "components" (i.e. web components) and "patterns"? We need to document the design for patterns that we don't and will not implement as web components. To group them all together under "components" (as we do now) is confusing. Some components also have associated patterns ("here's the footer web component, here's the footer pattern") - I think it's OK and even preferable to document those separately

**Comment by markcaron** [comment]
IMO, we should wait on the accessibility tab, and release this feature in addition to a future accessibility section (in the left hand nav) in Phase 3. This way we can focus on making these sections more properly thought out (i.e. not rushed) along with @hellogreg's and @kelsS's help.

**Comment by coreyvickery** [comment]
@marionnegp Making sure you see the above. Let's keep the existing accessibility stuff in the `Guidelines` tab for now. Thoughts on that?

**Comment by markcaron** [comment]
Going to use a new component, `rh-subnav`, to handle the tabs issue instead. See issue #703

**Comment by markcaron** [comment]
Done.
