### ISSUE TITLE
`/elements/elements`

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#418]
With our package export maps, we can import with specifiers like:
```js
import '@rhds/elements/rh-footer/rh-global-footer.js';
```
but for CSS, we still have to:
```html
<link rel="stylesheet" href="https://unpkg.com/@rhds/elements/elements/rh-footer/rh-footer-lightdom.css" />
```

If we remove the export maps and copy everything in `/elements/*` to `/`, we wouldn't need to `/elements/elements` for assets.

BUT that would also break things like dev server and demo imports when running locally.

We could *keep* the export maps, and ship duplicates of all the files, but that's not ideal either

**Comment by bennypowers** [comment]
let's try that in the next release. It probably requires us to maintain the list for each-and-every file, though, and I believe it will depend entirely on the CDN/importing tool to support it.

**Comment by markcaron** [comment]
@bennypowers what's the status on this?
