### ISSUE TITLE
[feat] <rh-clipboard-copy> component

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#423]
### Description

This is an icon that allows users to copy URLs (particularly anchor links), text, or other content. This currently exist in [PFE](https://patternflyelements.org/components/clipboard/) but not RHDS.

PatternFly also has a [clipboard copy component](https://www.patternfly.org/v4/components/clipboard-copy/) that allows users to copy text from read-only and editable text boxes. This might be helpful for code sections on ux.redhat.com as well.

### Acceptance Criteria

- [ ] Design done
- [ ] Development done

**Comment by bennypowers** [comment]
what about https://www.patternfly.org/v4/components/clipboard-copy?

**Comment by marionnegp** [comment]
Yeah, I can see that one being helpful for ux.redhat.com as well. I'll add it to the description at the top.

**Comment by marionnegp** [comment]
@RedHat-UX/developers @RedHat-UX/designers, the `rh-code-block` mockups show [stateful and tooltip options](https://xd.adobe.com/view/bd44b261-98ee-4551-8a90-92685f9bf5a1-e817/) for a clipboard copy button. Do we want both options, or does anyone prefer one over the other?

Other considerations:

- PFE uses a tooltip for its clipboard copy component.
- We have a [stateful clipboard copy button](https://xd.adobe.com/view/d20a1c17-375c-4c7f-6827-5fe2f8c2d92f-a43b/screen/3b793334-4bd3-4208-9366-bba9b8deca8c) in our DS Kit, but afaik it hasn't been developed yet.

**Comment by bennypowers** [comment]
I suspect there would be usability/a11y implications either way. WDYT @nikkimk ?

**Comment by nikkimk** [comment]
So the biggest issue is that the design is using button label or tooltip as a status message. Does the button behave differently when the text says "Copy" versus "Copied"?

It would be better to have the `copied` status `role="status"` next to the button or in a toast.

**Comment by marionnegp** [comment]
I believe that the text changes to "Copied" after it's clicked to verify that something's been copied.

**Comment by nikkimk** [comment]
So that's problematic. Because what happens to the button once its text changes? Is it disabled or does it still copy? "Copied" doesn't tell us what the button _does_; it tells us what the button _did_, which should be text that is not in the button.

**Comment by kelsS** [comment]
Hey ya'll here is a copy component I worked on a while back. I used an alert to tell the user the copy was successful. @nikkimk not sure if this helps but wanted to add it just in case. https://codepen.io/kelsS/pen/jOaqYLP

**Comment by nikkimk** [comment]
@kelsS If users were **_either_** sighted **_or_** using a screen that would be a great solution. But users can be **_both_** sighted **_and_** use a screenreader so when they click the button, what is being read to them does not match what they see on screen. (There's also a moment when the text changes that the visible focus disappears.)

However, if we _**do not**_ change the button/tooltip text, _**do**_ change the icon as visual confirmation, _**and**_ use your visually hidden alert as audio confirmation, we'd be giving visual and audio confirmation while not altering the button or hiding its focus state.

**Comment by kelsS** [comment]
> @kelsS If users were **_either_** sighted **_or_** using a screen that would be a great solution. But users can be **_both_** sighted **_and_** use a screenreader so when they click the button, what is being read to them does not match what they see on screen. (There's also a moment when the text changes that the visible focus disappears.)
> 
> However, if we _**do not**_ change the button/tooltip text, _**do**_ change the icon as visual confirmation, _**and**_ use your visually hidden alert as audio confirmation, we'd be giving visual and audio confirmation while not altering the button or hiding its focus state.

Sorry! this is an older component from when I was working with a design team that would not let me show the longer text content that the SR user is hearing. I will update it to align the visual and auditory experience and adjust so the focus never disappears.

**Comment by kelsS** [comment]
@nikkimk I updated the component to address those issues.
