### ISSUE TITLE
[docs] component status table design tweaks

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#424]
Not overly picky, but the x mark is not quite the center of each cell.  It's not a deal-breaker. I don't want to hold this up. we can adjust later if need be. Also, I think we can make the date the same color as the row line(#D2D2D2). I don't think it needs to be at the forefront with the other content but that is my opinion.

_Originally posted by @ronniemcbride in https://github.com/RedHat-UX/red-hat-design-system/pull/396#pullrequestreview-1031639741_

Also, instead of `x` we can use an icon from the icon collection:

> @coreyvickery @marionnegp Did we decide to go with X marks instead of Check marks? Also, we might be considering changing the marks used in the future. It is possible we might change it to a circle with a check-in from our icon set. @bennypowers swapping the mark for an RH-icon replacement should be considered. Will that be an issue later?

**Comment by bennypowers** [comment]
repoStatus shortcode

**Comment by eyevana** [comment]
@bennypowers the [repo status table](https://ux.redhat.com/elements/accordion/#when-to-use,) is using the `&check;` HTML entity. Would it be preferable to use pf-icon `check` instead?  I also just realized I need to add the copy/permalink functionality to the heading in that shortcode. I can tackle that here as well.

**Comment by bennypowers** [comment]
You could just read the SVG in from the icons package
