### ISSUE TITLE
[bug] tslib not included in dependencies

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#449]
### Describe the bug

We are using 'tslib' to polyfill private class fields and decorators but it's not listed in our production dependencies.  

@zhawkins was also running into an issue where an outdated version of tslib was being used instead and it was manifesting itself not as an error but rather as some private functions mysteriously vanishing.  Just recording it here in case we run into that again.

## Things to concider

We might not want to have tslib as a dependency of RHDS. I assume tslib is a critical piece of a typescript project and we wouldn't want to prevent a team from upgrading their project because we are using a specific version of tslib in RHDS.  An alternative could be to rollup the private function and decorator polyfills in RHDS somewhere.

### Which Component?

tools

### Steps to reproduce

1. Clone this repo locally https://github.com/heyMP/rollup-rhds-demo
2. Remove the `tslib` dependency
3. npm install
4. npm run build
5. Verify that it complains about 'tslib' being missing

### Expected behaviour

The user should not have to specify tslib in their dependencies

### Screenshots

<img width="1680" alt="Screen Shot 2022-08-02 at 10 09 20 AM" src="https://user-images.githubusercontent.com/3428964/182395220-46893042-85b8-4188-88ee-6f0bc9d20c97.png">

### Operating System (OS)

macOS

**Comment by bennypowers** [comment]
huh was sure I added it, oh well this was an oversight, good catch.

for now let's just add tslib as a dep, and we'll worry about fancy footwork if it becomes an issue.
