### ISSUE TITLE
[feat] Vendor bundled npm package

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#454]
The indefatiguable @zhawkins requests our efforts to produce a "vendor-bundled" rhds package for use in RHDC et al. The central requirement is that every package entrypoint (e.g. `elements/rh-footer/rh-footer.js`) contain *only* relative (or fully qualified) import specifiers.

To that end, I propose that we write a CI/CD script which, on each release, creates such a package tarball and publishes it to `@rhds/bundled`. This package's version must *exactly mirror* that of `@rhds/elements`.

we could also remove `rhds.min.js` from the main package, since it would be better placed at the main export of `@rhds/bundled`

**Comment by markcaron** [comment]
Potentially blocked and waiting on the CDN work.

**Comment by bennypowers** [comment]
can we close now that CDN is under its own power?
