### ISSUE TITLE
[bug] <rh-secondary-nav> logotype font-family not working due to typo

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#473]
As seen on the [demo page](https://ux.redhat.com/components/secondary-nav/demo/) (and in the code) the font stack for the logotype in the Secondary Nav has a typo, which causes the logotype to use the wrong font in the stack:

https://github.com/RedHat-UX/red-hat-design-system/blob/dddfba1de9daa9936e9993cf8fb7f5ab07b32af4/elements/rh-secondary-nav/rh-secondary-nav-lightdom.css#L61

- Instead of `"RedHatDisplay"` it should be `"Red Hat Display"` (with spaces)
- Use `1.5em` line-height instead of `1.6875em`

**Current:**
<img width="768" alt="image" src="https://user-images.githubusercontent.com/1890950/184886927-b4df4f5b-82ee-4b8b-a6ed-445b01a0e833.png">

**Expected:**
<img width="807" alt="image" src="https://user-images.githubusercontent.com/1890950/184887401-8845d237-acf5-48cd-bb21-d2e03770912c.png">

**Original mockup:**
https://xd.adobe.com/view/cc81c902-f053-4350-b443-0e4dc4ad0ab7-99d2/screen/07708659-5741-4654-87d8-1b18085ec341/

**Comment by bennypowers** [comment]
we need to fix this in tokens, as well

**Comment by zeroedin** [comment]
Secondary nav was referencing the font stacks provided by the [red-hat-design-tokens](https://github.com/RedHat-UX/red-hat-design-tokens) project.

I created an issue: https://github.com/RedHat-UX/red-hat-design-tokens/issues/17 and am referencing that here as well.

For the main text in the secondary-nav I was using the following stack:

https://github.com/RedHat-UX/red-hat-design-system/blob/dddfba1de9daa9936e9993cf8fb7f5ab07b32af4/elements/rh-secondary-nav/rh-secondary-nav-lightdom.css#L10

`Red Hat Text`, and `RedHatText` are listed for that stack.  Not sure that is appropriate, but again should fix that in the tokens repo so we have a single source of truth.

I also believe I originally cribbed these stacks from footer:

https://github.com/RedHat-UX/red-hat-design-system/blob/dddfba1de9daa9936e9993cf8fb7f5ab07b32af4/elements/rh-footer/rh-footer-block.css#L31

@markcaron we should go back and make sure that all new components are using the correct stacks.

**Comment by markcaron** [comment]
@zeroedin sounds good. Let's fix it at the source.

On a related note, and maybe a dumb question: is it possible to add ALL the fonts in the stack to the CSS var?

**Comment by zeroedin** [comment]
You mean this?:

`--rh-font-family-body-text: 'Red Hat Text', 'RedHatText', 'Overpass', Overpass, Arial, sans-serif;`

If so yes.

**Comment by markcaron** [comment]
@zeroedin yes! IMO, I think that gives us greater control over how the stack is passed through the system.

**Comment by zeroedin** [comment]
@markcaron that's the intention, just need to fix the source of truth and we should be good :)

**Comment by bennypowers** [comment]
This is fixed in tokens. #500 should fix this issue, too
