### ISSUE TITLE
[bug][docs] headings font-family on demos not working due to typo in base.css

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#475]
As seen on the [demo page](https://ux.redhat.com/components/secondary-nav/demo/) (and in the code) the font stack for the headings (`<h2>`) have a typo, which causes them to use the wrong font in the stack:

**Where in the CSS:**
https://github.com/RedHat-UX/red-hat-design-system/blob/dddfba1de9daa9936e9993cf8fb7f5ab07b32af4/docs/scss/_base/_base.scss#L55

Should be `"Red Hat Display"` instead of `"RedHatDisplay"`.

Similarly, on line 43, there's another font-stack issue with the `body` font:
https://github.com/RedHat-UX/red-hat-design-system/blob/dddfba1de9daa9936e9993cf8fb7f5ab07b32af4/docs/scss/_base/_base.scss#L43

This should be `"Red Hat Text"` not `"RedHatText"`.

The reason the body font is showing in `Red Hat Text` is because the `demo.css` overrides it with the proper font-stack. But, we should update `base.css` to fix this issue so it doesn't create others down the road.

**Screenshot of font-stack issue:**
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/1890950/184933766-2e77c1fb-2fc6-4318-a864-26804c03df74.png">

**Expected look:**
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/1890950/184933921-12cae6a3-0270-4cfd-9c10-7e7c4763b279.png">

**Comment by zeroedin** [comment]
https://github.com/RedHat-UX/red-hat-design-tokens/issues/17

**Comment by markcaron** [comment]
Resolved in https://github.com/RedHat-UX/red-hat-design-tokens/issues/17
