### ISSUE TITLE
Cookie user that hides mobile notice

### ISSUE THREAD

**Issue by dcaryll** [RedHat-UX/red-hat-design-system#48]
We have a banner that displays only on mobile. When a user clicks on it, it should hide the notification and should not show within the same visit.

**Comment by dcaryll** [comment]
@coreyvickery @castastrophe let's talk about this one and see if it's something we still need. It was built, but didn't function all the way.

**Comment by coreyvickery** [comment]
@dcaryll Is this the same warning that images may appear smaller on mobile?
