### ISSUE TITLE
Review Automation

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#484]
- [ ] Add all new issues to the main project board
- [ ] required action that fails if not at least one user in the designers' group and one reviewer in the developers group (who aren't the pr author) have approved

**Comment by markcaron** [comment]
CC @paigenotfound404 @methomps

**Comment by bennypowers** [comment]
https://github.com/orgs/RedHat-UX/projects/1/workflows/12217937
