### ISSUE TITLE
[bug] footer: secondary start slot not being used but still showing gap

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#488]
The distance between the spacer and the secondary content slot should be 32px.  The problem is that grid gap will show for the nested slots (`secondary-start`, `secondary-end`) even if they have no slotted content.

<img width="762" alt="pasted image 0" src="https://user-images.githubusercontent.com/3428964/186293725-9605a383-9954-4346-b457-e4c104adbbf4.png">

## What I did

- I'm conditionally hiding the regions if they have no slotted content in them using our SlotController. (note: this might become obsolete if/when `:has()` selector lands)

## Code review

- [x] https://github.com/RedHat-UX/red-hat-design-system/pull/491/commits/47b2ac632c76925f7746d378bfca77653c8b0162

## Testing Instructions

1. Visit https://deploy-preview-491--red-hat-design-system.netlify.app/components/footer/demo/
2. On mobile, verify that there is a 32px space between the spacer and secondary content region (see screenshot below)
3. On desktop, verify that there is a 24px space between the primary and secondary links region (see screenshot below)

## Screenshots

Mobile
![Screen Shot 2022-08-24 at 10 09 51 AM](https://user-images.githubusercontent.com/3428964/186447216-29b14c78-6b94-4bd1-8892-96caad9c70e5.png)

Desktop
![Screen Shot 2022-08-24 at 10 13 27 AM](https://user-images.githubusercontent.com/3428964/186447549-1098e334-d62a-4d6e-9e3e-5af85402d65a.png)

## Current mitigations

```css
// Hide unused global footer slot.
rh-global-footer::part(secondary-start) {
    display: none;
}
```

**Comment by brianferry** [comment]
I can confirm from looking at those links I am seeing the 32px gap on mobile and the 24px gap on desktop.  👍
