### ISSUE TITLE
[bug] footer: reduce the spacing beneath the primary footer nav / language switcher to match the xd

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#499]
![Screen Shot 2022-08-17 at 11 48 37 AM](https://user-images.githubusercontent.com/3428964/186689155-3dcbcd9c-e615-4192-83b7-ee73e8401261.png)

The issue is that `rh-footer-block` is meant to have free-form HTML content.  When that content contains margin then it messes with the spacing.  A possible solution is to target the last child of the last `rh-footer-block` item in the sidebar and set it's bottom margin/padding to 0.

## What I Did

- <rh-footer-block> content removes top/bottom margin for :first-child / :last-child respectively
- Corrected the margin between the sidebar content and the global-footer on Tablet, landscape breakpoint (64px)

## Code Review

- [x] https://github.com/RedHat-UX/red-hat-design-system/commit/496faa91de5f650f9022d5e71a49f921873166fe

## Testing Instructions

- Visit https://deploy-preview-491--red-hat-design-system.netlify.app/components/footer/demo/
- [x] Ensure that the "Select a Language" block is `32px` away from the global footer and `64px` above a 992px breakpoint

## Screenshots

![Screen Shot 2022-08-26 at 1 51 33 PM](https://user-images.githubusercontent.com/3428964/186964928-d03703a2-5fd3-4684-8c31-7af4f201ecaf.png)

![Screen Shot 2022-08-26 at 1 55 24 PM](https://user-images.githubusercontent.com/3428964/186964852-a54d7599-dddc-4404-abd5-56d3073da764.png)

**Comment by wesleymiles** [comment]
Looks good. Confirmed the "Select a Language" block is 32px away from the global footer, and 64px above at 992px.
