### ISSUE TITLE
[bug] Statistic demo page is showing on ux.redhat.com

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#501]
### Describe the bug

The stat demo page (statistic.md) was published on ux.redhat.com at https://ux.redhat.com/components/statistic/. Should be hidden/removed from sidebar nav.

### Which Component?

rh-stat

### Steps to reproduce

Go to https://ux.redhat.com/components/statistic/

### Expected behaviour

There shouldn't be a published Statistic page yet.

### Operating System (OS)

macOS

**Comment by marionnegp** [comment]
@brianferry, the file extension used to be .mdx and is now showing as .md for the stat demo page. I didn't want to change it back in case it messes with the recent work you've done on the component.

**Comment by bennypowers** [comment]
`.mdx` means markdown-with-jsx, which we dont need.

If the intention in naming it .mdx was to prevent it from being published, then it should just be deleted. You can always copy the code back from a previous commit.

**Comment by marionnegp** [comment]
I don't know if that was the intention behind using .mdx, but statistic.md is conflicting with a statistic.njk doc I'm working on in another branch too. I'd be ok with deleting it or moving it somewhere else as long as it doesn't mess with anything you or @brianferry have in progress!

**Comment by brianferry** [comment]
@marionnegp You're good to delete!
