### ISSUE TITLE
[bug] rh-alert font issue on buttons

### ISSUE THREAD

**Issue by dcaryll** [RedHat-UX/red-hat-design-system#516]
### Describe the bug

The buttons in the alert pattern are showing the wrong font-family. 

@zeroedin mentioned this is likely an issue with not using design tokens. 

### Which Component?

rh-alert

### Steps to reproduce

1. Go to https://ux.redhat.com/components/alert/demo/
2. View the buttons (Dismiss/Confirm)
3. Inspect > font-family is Arial

### Expected behaviour

The font family should follow the design spec from https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/84de1e95-5aca-4782-8eba-5a98804f93a6/specs/

### Screenshots

![Screen Shot 2022-09-08 at 1 48 31 PM](https://user-images.githubusercontent.com/1249747/189191287-23857260-787f-4ff8-9c00-0807ef00734d.png)

### Element HTML

```HTML
<button slot="actions" data-action="dismiss">Dismiss</button>
```

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by zeroedin** [comment]
After inspection it does use design tokens, just doesn't explicitly set a font-family value.

**Comment by brianferry** [comment]
Yup, and in addition to this we will need to set the cursor styles for anything slotted in the actions which we can also do in the css.

**Comment by brianferry** [comment]
Set up a demo with the fixed fonts and cursor pointer @dcaryll https://deploy-preview-517--red-hat-design-system.netlify.app/components/alert/demo/

**Comment by dcaryll** [comment]
Thank you @brianferry! @coreyvickery or @marionnegp would one of you mind doing a design review of this pattern again?

**Comment by marionnegp** [comment]
@brianferry, I can take a look.
