### ISSUE TITLE
[bug] footer: side gap should have three different breakpoint values

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#526]
The side gap between the content and the viewport should be as follows:

Mobile first breakpoints:

- Default
  - Spacer token: var(--rh-space-lg, 16px) 
- Tablet small
  - Breakpoint token: var(--rh-breakpoint-sm, 768px)
  - Spacer token: var(--rh-space-2xl, 32px)
- Desktop medium
  - Breakpoint token: ???
  - Spacer token: var(--rh-space-4xl, 64px)

## Screenshots
  
![Screenshot 2023-03-20 at 9 02 19 PM](https://user-images.githubusercontent.com/3428964/226497672-47f52c8f-f19f-4bff-8155-0b607aebbf35.png)

![Screenshot 2023-03-20 at 9 02 07 PM](https://user-images.githubusercontent.com/3428964/226497696-fae5f220-a1eb-4d2b-8706-bc71c739b236.png)

![Screenshot 2023-03-23 at 9 08 54 PM](https://user-images.githubusercontent.com/3428964/227398750-7fb48bd3-d6f7-4eed-b6a6-5546133cf376.png)

## Resources

- [Footer design spec](https://xd.adobe.com/view/835616bd-1374-483d-ab10-6ae92e0e343c-d605/screen/c12d502d-3f4e-4d78-9850-25146679bb9f/)

**Comment by eyevana** [comment]
@heyMP what's the expectation here? Couldn't tell from reading the title. I see this variable set on `rh-global-footer`: `--_section-side-gap:  var(--rh-footer-section-side-gap, var(--rh-space-2xl, 32px));
`
