### ISSUE TITLE
[bug] rh-footer remove Summit logo

### ISSUE THREAD

**Issue by paigenotfound404** [RedHat-UX/red-hat-design-system#534]
### Describe the bug

Update rh-footer demo to remove Summit logo from tertiary slot and add Red Hat Summit to rh-global-footer slot="global

### Which Component?

rh-footer

### Steps to reproduce

1. Go to https://catalog.redhat.com/
2. Scroll to bottom
3. See "Have Feedback?" button overlap Summit logo

### Expected behaviour

No Summit logo so there's no overlap

### Screenshots

![Screen Shot 2022-09-20 at 2 45 36 PM](https://user-images.githubusercontent.com/108767420/191339362-8aabea32-e6d0-4a19-bcf3-264884e4c1e6.png)

## Testing Instructions
1. Visit https://deploy-preview-491--red-hat-design-system.netlify.app/components/footer/demo/
  - [x] Verify that the summit logo is not present in the demo

2. Visit https://deploy-preview-491--red-hat-design-system.netlify.app/components/footer/demo/global-footer/
  - [x] Verify that the summit logo is not present in the demo

3. Visit https://github.com/RedHat-UX/red-hat-design-system/blob/deff192fb9948669a73f546267571d92ee09d639/elements/rh-footer/README.md
  - [x] Verify that the summit logo is not referenced in the documentation

**Comment by dcaryll** [comment]
Example of overlap with Drift on redhat.com

<img width="1281" alt="Screen Shot 2022-09-08 at 11 35 18 AM" src="https://user-images.githubusercontent.com/1249747/191339678-83a46d32-545c-4455-90b5-d3f0766a959c.png">

**Comment by bennypowers** [comment]
Could we address this by perhaps slotting FABs and such into footer? are they meant to be sticky, staying at the bottom of the viewport regardless of vertical scroll position? :thinking:

**Comment by dcaryll** [comment]
Right, they're meant to be sticky (using 3rd party tools that we don't have control over). We've decided that removing the logo makes sense from a content perspective.

**Comment by bennypowers** [comment]
if that's the case, am I correct in assuming that the change we need to make here is only in documentation?

or would we prefer to redesign footer to make room for FABs?

**Comment by dcaryll** [comment]
Correct! Only an update to the documentation/visuals on our demos. We want to leave the slot, but don't yet have a good idea of what may go in that slot on sites that don't have a conflict.
