### ISSUE TITLE
[feat]: <rh-card> ready to migrate

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#538]
### Tag Name

pfe-card

### RHDS Only

- [ ] The component will be **RHDS only**, delete the PFE component once published

### Additional Info

Migrate/build/extend `<rh-card>` from `<pfe-card>`.

This is "as is", so we should focus on building this out quickly with improvements to the API only. Later we should tackle additional features or variants.

[Current design specs](https://ux.redhat.com/components/card/)

**Comment by brianferry** [comment]
- [ ] Styling
  - [ ] Padding around card element (desktop / mobile are different)
  - [ ] Padding between header, body, footer
  - [ ] Font family / size
  - [ ] Title max height (200px)
- [ ] Card Themes  
  - [ ] Light mode (default)
  - [ ] Light mode alt
  - [ ] Dark mode
  - [ ] Dark mode alt
- [ ] Attributes
  - [ ] `full` - title has no padding (default is 32px padding)
  - [ ] `bar` - title has theme outlined here https://xd.adobe.com/view/d20a1c17-375c-4c7f-6827-5fe2f8c2d92f-a43b/screen/930cbfcc-d26a-49cc-85e9-30e360dde698/
  
@Nouveau let me know if I missed anything

**Comment by marionnegp** [comment]
@brianferry @Nouveau, @coreyvickery and I met with Adam about how to handle borders in FTS last week. We decided that all cards should have a visible border. In light theme, the border is always `--rh-color-border-subtle-on-light`, and dark theme cards use `--rh-color-border-subtle-on-dark`. 

XD link: https://xd.adobe.com/view/71513d55-f959-4fac-a41a-dfe9df3a0266-2402/

**Comment by coreyvickery** [comment]
@marionnegp Looks good.

**Comment by brianferry** [comment]
Added those borders @marionnegp @coreyvickery @Nouveau, thank you!

**Comment by brianferry** [comment]
@marionnegp

The changes have been pushed up to the branch and the tokens should all be updates as well as making sure the font-family and the line-height is being included in all sections regardless of if it's slotted or not.  

Also added demos of the `alt` attribute so you can check the background / borders to make sure that it lines up with what you all were thinking

**Comment by marionnegp** [comment]
It looks like the card title's font size is being overridden by the site's H2 size.
![Image](https://user-images.githubusercontent.com/95588923/233157966-f81aadf7-4350-41b9-becc-439e0ef636c0.png)

The surface color for the alt version on light theme should be `--rh-color-surface-light`. Sorry, I didn't realize what color the header bg was, and they should match.

**Comment by bennypowers** [comment]
we shouldn't be doing pr review in an issue thread, so i opened https://github.com/RedHat-UX/red-hat-design-system/pull/952

@brianferry please edit the description
@marionnegp please continue review there

Cheers :)

**Comment by brianferry** [comment]
May 19, 2023 Update - Added JSDocs for the css properties, props, slots and updated the background variable.  Added new demo to show off the new patterns.  Reworked what we could in the docs based on the current info, will update more as the docs files come in.
