### ISSUE TITLE
[bug] footer: Add no-js styles to reduce flash of unstyled content before upgrade

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#543]
## What I did

Added some light no-js styles into `rh-footer-lightdom.css` that adds background color for `<rh-footer>` and `<rh-global-footer>`.  I also sized it a bit to try to approximate what the heights might be.

I added some no-js styles to show the logo as well.  Since the logo is a very predictable size and location I felt it was a good addition to the no-js experience.

All other content I'm hiding with opacity 0.  I'm not using the [clip method](https://www.nomensa.com/blog/how-improve-web-accessibility-hiding-elements) to hide the elements because I want to maintain some of heights of the child elements to try to approximate what the height of the upgraded component will be.  The clip method uses position absolute which would have no height.

## Code review

- [x] https://github.com/RedHat-UX/red-hat-design-system/commit/f709269e6720f333d88a4766397216d9cb8e1ab5

## Testing Instructions
1. Visit https://deploy-preview-491--red-hat-design-system.netlify.app/elements/rh-footer/demo/rh-footer.html
2. On chrome, open up the dev tools, "Network".  Set "throttling" to "Fast 3G".
3. With the devtools open, refresh the page.
4. Verify that before the javascript loads you see just the skeleton of the footer and the logo.
5. Verify that when the component upgrades the logo doesn't jump around.

## Screenshots

![ScreenFlow](https://user-images.githubusercontent.com/3428964/191881934-539d6830-70b6-46e0-b9a0-38415e36d364.gif)

**Comment by wesleymiles** [comment]
very cool! 

1. confirmed that before the js loads i see just the skeleton of the footer and the logo.
2. confirmed that when the component upgrades the logo didn't jump around.

**Comment by heyMP** [comment]
@zhawkins Can you take a peek at it and see if that might suit our needs for now?

**Comment by zhawkins** [comment]
It doesn't look like the demo app is still deployed: https://deploy-preview-491--red-hat-design-system.netlify.app/elements/rh-footer/demo/rh-footer.html

🤔

**Comment by brianferry** [comment]
https://deploy-preview-491--red-hat-design-system.netlify.app/components/footer/demo/ please try this @zhawkins

**Comment by zhawkins** [comment]
That works @heyMP and @brianferry ! Looks much better.
