### ISSUE TITLE
[bug] content-set needs to respect accordion expanded index setting

### ISSUE THREAD

**Issue by zhawkins** [RedHat-UX/red-hat-design-system#551]
### Describe the bug

content-set doesn't respect the accordion expanded index setting. This means there's no way to set an accordion item as "open" by default when added through content set.

https://drive.google.com/file/d/1gZGiUvnzZEqQvCsxQ5lJZrX0rwF9xw_q/view

We've talked to @heyMP about this 

### Which Component?

pfe-content-set

### Steps to reproduce

1. Contact Adam

### Expected behaviour

content-set should respect the accordion expanded index setting

### Operating System (OS)

macOS

### Browser

Chrome

### Additional Info

This is likely only needed for WebRH via a patch since we're going to remove content set at some point.

**Comment by bennypowers** [comment]
we're chucking content-set, right @markcaron ?

**Comment by LyndseyR** [comment]
@bennypowers these are the takeaway notes in the [agenda](https://docs.google.com/document/d/17iSx7gVr6scH4AcQo4nsaGTCy8lOo2hLl2dVn00Zpss/edit#heading=h.sh39bheukjas) from last Wednesday 
Conclusion:
If the patch isn’t a big pain in the butt, patch it.
We can either patch it in webrh or pfe v1.
Moving forward we look at removing content-set. People pick a single pattern.

@markcaron if this has changed please let us know.

**Comment by bennypowers** [comment]
p. sure we decided a ways back that content-set was an antipattern
