### ISSUE TITLE
[bug] <rh-footer> | updates to demo page linked from ux.redhat.com

### ISSUE THREAD

**Issue by methomps** [RedHat-UX/red-hat-design-system#552]
### Describe the bug

There are a few inconsistencies that should be corrected in the demo/kitchen sink link that is linked from the footer component page on ux.redhat.com: https://ux.redhat.com/components/footer/demo/.

**These updates should be made to _any documentation_ we have for the rh-footer. Potter is working on taking down the codepen demos and application demos, so this may be all that's remaining to be updated. The visuals/screenshots on ux.redhat.com seem to be updated to show the latest.

![2022-09-29-14-27-ux redhat com](https://user-images.githubusercontent.com/103068985/193118889-203548ae-33e6-4b2b-876a-e3f645d6d38b.png)
(This screenshot from ux.redhat.com shows the current, updated content and design to use as reference)

On the demo page, https://ux.redhat.com/components/footer/demo/, these updates should be made:
1) The list order in the global footer region should be updated to match the correct list order. "Cool Stuff Store" and "Diversity, equity, and inclusion" should be swopped.
2) Red Hat Summit should be added as a text link to the end of the list.  see #534 for reference
3) Should we remove the statement about the privacy statement update (*We’ve updated our privacy statement effective December 30, 202X.) since this isn't a default / out-of-the-box section of content?

### Which Component?

rh-footer

### Steps to reproduce

1. Go to https://ux.redhat.com/components/footer/
2. Click on "View this component in action" CTA

### Expected behavior

The demo link is updated to reflect the latest design and content updates to the footer menu

## Testing Instructions
1. Visit https://deploy-preview-491--red-hat-design-system.netlify.app/components/footer/demo/
  - [x] Verify that the links in the footer demo match those listed in the [spreadsheet](https://docs.google.com/spreadsheets/d/1zE3U8C3eugi23R5HoHlZOIhi6bnyAV3Iolu55BLh1nw/edit#gid=1734190854)

2. Visit https://deploy-preview-491--red-hat-design-system.netlify.app/components/footer/demo/global-footer/
  - [x] Verify that the links in the footer demo match those listed in the [spreadsheet](https://docs.google.com/spreadsheets/d/1zE3U8C3eugi23R5HoHlZOIhi6bnyAV3Iolu55BLh1nw/edit#gid=1734190854)

3. Visit https://github.com/RedHat-UX/red-hat-design-system/blob/fix/footer/rhdc-bugs/elements/rh-footer/README.md
  - [x] Verify that the links contained in these instructions match those listed in this [spreadsheet](https://docs.google.com/spreadsheets/d/1zE3U8C3eugi23R5HoHlZOIhi6bnyAV3Iolu55BLh1nw/edit#gid=1734190854)

### Notes for Reviewers

The "Cookie Preferences" link is not displayed in the examples.  This is because of the was trustarc works.  I have a note in the readme that says the following:

```html
    <!-- If your website supports trustarc include this item to add Cookie Preferences to your site. -->
    <!-- <li><span id="teconsent"> </span></li> -->
```

**Comment by heyMP** [comment]
Updated the docs on:

- [x] ux.redhat.com
- [x] removed rh-footer related Codepen.io exampes

**Comment by heyMP** [comment]
@methomps This is ready for review.

**Comment by heyMP** [comment]
@methomps My bad, I've updated the links to reflect the most recent change. 
https://github.com/RedHat-UX/red-hat-design-system/blob/fix/footer/rhdc-bugs/elements/rh-footer/README.md

- Buy online (Japan) should be removed
- Red Hat Shares should have the updated url

**Comment by heyMP** [comment]
- [x] Rollup demo updated and screenshot updated https://github.com/heyMP/rollup-rhds-demo
