### ISSUE TITLE
[bug] ux.redhat.com/foundations/typography/

### ISSUE THREAD

**Issue by dcaryll** [RedHat-UX/red-hat-design-system#554]
### Describe the bug

Typography availability section is blank

### Which Component?

n/a

### Steps to reproduce

1. Go to https://ux.redhat.com/foundations/typography/
2. View blank section for Typography availibility

### Expected behaviour

Visible table

### Screenshots

![Screen Shot 2022-09-29 at 9 20 07 PM](https://user-images.githubusercontent.com/1249747/193169481-083cb17e-0c6b-4d49-bd98-c273589e27a0.png)

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by coreyvickery** [comment]
@bennypowers Table is still not showing up or am I missing a demo link?

**Comment by dcaryll** [comment]
@coreyvickery is there content in the CSV? @bennypowers mentioned in another comment: "if design teammates add typography rows to the csv, they will appear on the page, if not, the table will not appear on the page"

**Comment by coreyvickery** [comment]
@dcaryll I don't know if there is and I can't remember what content used to be there, if any. Do you think our font family, weight, and repo information should be in that table? cc @markcaron @bennypowers

**Comment by coreyvickery** [comment]
Fixed per this.

https://github.com/RedHat-UX/red-hat-design-system/pull/650
