### ISSUE TITLE
[bug] rh-secondary-nav (!) Circular dependency

### ISSUE THREAD

**Issue by zhawkins** [RedHat-UX/red-hat-design-system#557]
### Describe the bug

While using rollup to bundle `rh-secondary-nav` I see the following warning / error:

```
(!) Circular dependency
node_modules/@rhds/elements/elements/rh-secondary-nav/rh-secondary-nav-dropdown.js -> node_modules/@rhds/elements/elements/rh-secondary-nav/rh-secondary-nav-menu.js -> node_modules/@rhds/elements/elements/rh-secondary-nav/rh-secondary-nav-dropdown.js
```

It looks like `rh-secondary-nav-dropdown` is importing `rh-secondary-nav-menu` which is importing `rh-secondary-nav-dropdown`.

Looking into this with Steven it seems that `rh-secondary-nav-menu` is importing `rh-secondary-nav-dropdown` in order to define `isDropdown` _but_ `isDropdown` isn't currently being used.

So removing `isDropdown` within `rh-secondary-nav-dropdown` and removing the `rh-secondary-nav-menu` import resolves the *Circular dependency* issue. 

### Which Component?

rh-secondary-nav

### Steps to reproduce

1. Ask Zack to see the rollup config in rhdc.
2. Use that config to import rh-secondary-nav and check the error.

### Expected behaviour

There shouldn't be any circular dependencies if we can help it.

### Operating System (OS)

macOS

**Comment by bennypowers** [comment]
fwiw circular dependencies are fine, it's a design goal of es modules

**Comment by zhawkins** [comment]
https://exploringjs.com/es6/ch_modules.html#sec_design-goals-es6-modules

```Support for cyclic dependencies was a key goal for ES6 modules. Here is why:

Cyclic dependencies are not inherently evil. Especially for objects, you sometimes even want this kind of dependency. For example, in some trees (such as DOM documents), parents refer to children and children refer back to parents. In libraries, you can usually avoid cyclic dependencies via careful design. In a large system, though, they can happen, especially during refactoring. Then it is very useful if a module system supports them, because the system doesn’t break while you are refactoring.```

Interesting. TIL.

**Comment by bennypowers** [comment]
might still make sense to factor it out, but just keep in mind that this is basically rollup waving it's finger at you

**Comment by zhawkins** [comment]
Yeah, since it's unused code anyway, might as well factor it out.

**Comment by zeroedin** [comment]
The code identified was orphaned during a refactor.  I'd like to clean it up anyway as it doesn't get used outside a reference to the import.
