### ISSUE TITLE
[bug] Recent update to @patternfly/pfe-tools breaks `rh-secondary-nav`

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#568]
### Describe the bug

A recent update to devDependency: `@patternfly/pfe-tools@1.0.0.next.30` breaks secondary-nav.

Downgrading this to `@patternfly/pfe-tools@1.0.0.next.29` and nav works correctly.

When broken it appears as if `@query` decorator no longer works as expected.  I'm looking further into this to see if I can figure out an explicit change that causes the issue.

`@query` is used to get the `rh-secondary-nav-overlay` element in the shadowRoot and attach a click event listener after firstUpdated, the element is set to private property `this._overlay`.  However `this._overlay` returns `undefined` in the `firstUpdated()` lifecycle callback which is odd. The following error is thrown: 

```
rh-secondary-nav.ts:139 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at RhSecondaryNav.firstUpdated (rh-secondary-nav.ts:139:19)
    at RhSecondaryNav._$AE (reactive-element.js:6:5070)
    at RhSecondaryNav.performUpdate (reactive-element.js:6:4872)
    at RhSecondaryNav.scheduleUpdate (reactive-element.js:6:4454)
    at RhSecondaryNav._$Ej (reactive-element.js:6:4362)
```

### Which Component?

rh-secondary-nav

### Steps to reproduce

To see browser errors and lost functionality:

1. Check out the `main` branch.
2.  Delete `node_modules` and `package-lock.json`
3.  Run `nvm use`
4.  Run `nvm install`
5.  Run `npm start`
6.  Open the Secondary Nav demo and browser console.  Should see the error.

To downgrade pfe-tools to 29:

1. Delete `node_modules` and `package-lock.json`
2. Open `package.json` and in `devDependencies` change `@patternfly/pfe-tools` to `1.0.0-next.29`
3.  Run `nvm use`
4.  Run `nvm install`
5.  Run `npm start`
6.  Open the Secondary Nav demo and browser console.  Should see **no** error, and dropdowns and overlay work again.

### Expected behaviour

The secondary nav component should not throw this error.

### Operating System (OS)

macOS

### Browser

Chrome, Safari, Safari iOS, Microsoft Edge, Firefox

**Comment by heyMP** [comment]
Seeing this too with color context 

![Screen Shot 2022-10-05 at 11 45 22 AM](https://user-images.githubusercontent.com/3428964/194103977-53e739e9-30ef-4c89-9324-7fbde428435b.png)

**Comment by heyMP** [comment]
Confirmed rolling back to `@patternfly/pfe-tools@1.0.0-next.29` fixes the issue
![Screen Shot 2022-10-05 at 11 49 03 AM](https://user-images.githubusercontent.com/3428964/194104635-0f160fa6-a93a-4ea5-a7c7-f982a74f22d1.png)
