### ISSUE TITLE
[bug] footer: All grid-template-areas show gap regardless of existing

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#575]
Primary links uses grid auto rows to account for 2 rows by default.  Side effect is that grid gap adds and extra row of spacing.

## Expected behavior

- Space between the primary links and the global footer should be 64px.

## Current mitigation

```css
rh-footer::part(links) {
    grid-template-rows: initial;
}
```

## Screenshots

![image](https://user-images.githubusercontent.com/3428964/194872710-b953e7c4-66ba-4760-b8fe-22607df70431.png)

![image](https://user-images.githubusercontent.com/3428964/194872787-e5ab8a8f-d66b-40a2-a304-6eb2d52a89de.png)

**Comment by bennypowers** [comment]
could we solve with `<region>.isEmpty { display: none; }`?

**Comment by heyMP** [comment]
Unfortunitely not for this case, the region will have links in it.  We are using CSS Grid to layout the links into not only column based layouts but also row based layouts.  So this is the culprit:

```css
[part="base"]:not(.isMobile) .links {
   display: grid;
   grid-template-columns: repeat(1fr, 25%);
   grid-template-rows: repeat(2, min-content auto);
```

This was working when we were adding margins / negative margins to separate the first row from the second row of primary links.  But now that we switched to using row-gap it's adding an extra gap to account for the fake second row specified by: `grid-template-rows: repeat(2, min-content auto);`.

My solution is to get rid of row-gap in this instance and switch to a quantity query in the lightdom.

```css
[slot="links"]:is(h1, h2, h3, h4, h5):nth-of-type(n+5) {
  --_link-header-margin: calc(var(--rh-space-2xl, 32px) - var(--rh-space-lg, 16px));
}
```
I'm not overly excited about this solution as it will only work with lightdom css but it's a fix for now.  I'm wondering if there is a pattern for sub grid patterns or something?

**Comment by bennypowers** [comment]
let's run with it
