### ISSUE TITLE
Style and Design for Demo Playgrounds

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#581]
@markcaron @marionnegp I did a quick pass at a design for these demos. If you read above, Benny wants to:

> show the snippet only first, with a button to load the demo playground

I like this approach as it saves a lot of vertical space. We can also use several web components to build this larger one.

https://xd.adobe.com/view/0779bcd8-06d0-49d7-86c3-de81534d70b1-522a/

cc @bennypowers

_Originally posted by @coreyvickery in https://github.com/RedHat-UX/red-hat-design-system/issues/467#issuecomment-1276672420_

**Comment by brianferry** [comment]
Should add a loading indicator for the playground elements so the user knows when it is loading.  Currently looks like it loads in the shadow dom afterwards and then shows progress indicator, so maybe if no shadow dom exists we can add a loading indicator until the playground element loads?

**Comment by coreyvickery** [comment]
@bennypowers Possible to add a spinner while the playground is loading?

cc @brianferry

**Comment by bennypowers** [comment]
Yes that's a good idea. That's how I did it on apolloelements.dev

**Comment by coreyvickery** [comment]
@bennypowers Are we waiting for `rh-spinner` to be done to close this?

**Comment by bennypowers** [comment]
yes
