### ISSUE TITLE
[feat] Standard way to show a link is gated

### ISSUE THREAD

**Issue by dcaryll** [RedHat-UX/red-hat-design-system#592]
### Description

Can we standardize the way we handle links when they are going to something that is behind a login? Consider https://ux.redhat.com/components/link/. Should a link have an icon or description associated with it when it goes to a new link? What about when search results go to a gated link? Links in a navigation experience?

### Suggested solution

Icon, label or description associated with a link

### Additional context

These links could be inline in a page, in navigation, in search results, in learning paths, etc. We'd want to consider all of the context. It would be great to have guidelines at the link level for how we should handle this. 

Consider how customer portal is already doing this on their search results: https://access.redhat.com/search/#/?q=rhel

**Comment by marionnegp** [comment]
The design leads agreed that a padlock icon was preferred for gated links. Moving this to the Chansey milestone as we wait for a new padlock icon from Brand.
