### ISSUE TITLE
[bug][docs] <rh-alert> Close button non-functional, no way to hide the close button on alert

### ISSUE THREAD

**Issue by brianferry** [RedHat-UX/red-hat-design-system#593]
### Describe the bug

Currently the close button is non-optional and there's also no documentation currently for the user to set up their own hooks for rh-alert. 

### Which Component?

rh-alert

### Steps to reproduce

1. Go to the [rh-alert demo](https://ux.redhat.com/components/alert/demo/)
2. Try to click on the "close" icon
3. Nothing happens

### Expected behaviour

The close icon should either dismiss it's parent alert or should be documented on how to hook up the close button with its parent element.

### Element HTML

```HTML
<rh-alert state="default">
  <h3 slot="header">Default</h3>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eleifend elit sed est
    egestas, a sollicitudin mauris tincidunt.</p>
  <button slot="actions" data-action="dismiss">Dismiss</button>
  <button slot="actions" data-action="confirm">Confirm</button>
</rh-alert>
```

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by ocean-rh** [comment]
I was using the state="info" variation. I was also unable to hide the close button.

**Comment by bennypowers** [comment]
see also https://github.com/RedHat-UX/red-hat-design-system/discussions/541

**Comment by jvprh** [comment]
We are definitely looking for an option to hide the close button for a persistent alert the user cannot dismiss. 

Re: functionality for the close button, I would expect that it would hide the alert (functionality within the component). Can it also broadcast an event we can listen for? In an Adobe Target context, we would tap into that event to add an attribute to the user's profile, preventing the alert from displaying again. Not sure if we're having similar conversations about localstorage or using cookies to permanently dismiss an alert _within_ the alert

**Comment by brianferry** [comment]
An event is possible @jvprh that could be broadcasted & have us close it within the component.  I've just asked our design leads which direction they see this going for the user but as far as adding the hiding functionality that should be pretty straightforward.  

Cookies / localstorage would likely be something we'd be pushing to outside of a component from my understanding maybe as additional code that would be triggered from the user side from a bubbled event but I might be mistaken in my understanding there.
