### ISSUE TITLE
[bug] broken hyperlink needs updating

### ISSUE THREAD

**Issue by rblackbu** [RedHat-UX/red-hat-design-system#598]
### Describe the bug

Reporting a broken hyperlink on https://ux.redhat.com/get-started/fts-starter-kit/

### Which Component?

hyperlink

### Steps to reproduce

1. Go to the page: https://ux.redhat.com/get-started/fts-starter-kit/
2. Under the first paragraph for Flexible Template System the CTA link 'Browse Patternkit patterns' needs to be updated to link to https://webrh-demo.apps.int.spoke.preprod.us-west-2.aws.paas.redhat.com/schema/custom_band
3. See screenshot for reference<img width="909" alt="Screen Shot 2022-10-26 at 10 19 32 AM" src="https://user-images.githubusercontent.com/25234746/198058519-4c69787d-02fe-4ae7-b60f-927409b32fca.png">

### Expected behaviour

Upon click the site can be reached

### Operating System (OS)

macOS

### Browser

Chrome

### More browser information

Version 107.0.5304.62 (Official Build) (x86_64)

**Comment by marionnegp** [comment]
Thanks for finding this, @rblackbu! It's been fixed.

Closed by #600
