### ISSUE TITLE
[bug] footer links showing at 7.5px on Open Source Stories pages

### ISSUE THREAD

**Issue by alypilkons** [RedHat-UX/red-hat-design-system#604]
### Describe the bug

On Open Source Stories (D9) pages, the links in rh-global-footer are showing at 7.5px

### Which Component?

rh-global-footer

### Steps to reproduce

1. Go to OSS page such as: https://www.redhat.com/en/open-source-stories/common-connections/healthcare-made-human
2. Scroll down to footer

### Expected behaviour

Footer links should be larger - they are 12px on redhat.com

### Operating System (OS)

macOS

### Browser

Chrome

### More browser information

I saw this in Chrome, Safari, and Firefox. @zeroedin was seeing it in Safari and Firefox, but was seeing the links show at 10px in Chrome (we're not sure why.)

**Comment by zeroedin** [comment]
A fix also appears to be removing all `font-size` on `body` and adding `body { font-size: 1rem }` and if the bump to 18px at 768  then `1.125rem` in a media query.  These could be set with `var(--rh-font-body-text-md, 1rem)` and `var(--rh-font-body-text-lg, 1.125rem)` respectively as well.

**Comment by zeroedin** [comment]
This issue is related to #601 and #589

**Comment by heyMP** [comment]
I think it's possible we fixed this using this non-standard font-size method. 

https://github.com/RedHat-UX/red-hat-design-system/wiki/Root-Font-Size

**Comment by heyMP** [comment]
@alypilkons can you confirm that this is this still an issue?

**Comment by alypilkons** [comment]
Hi @heyMP looks like those pages aren't using the footer anymore so this issue is not relevant anymore. Thanks!
