### ISSUE TITLE
[bug] <footer> UX footer demo not rendering icons or rh-cta

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#613]
### Describe the bug

There are two issues on the footer demo page.

1. pfe-icons are failing to load.
2. rh-cta for the "Sign up now" button not being loaded.

### Which Component?

rh-footer

### Steps to reproduce

1. Go to https://ux.redhat.com/components/footer/demo/
2. Verify that the social icons in the top right corner are not being rendered correctly
3. Verify that the "Sign up now" cta is being rendered as a standard link and not an rh-cta

### Expected behaviour

pfe-icon and rh-cta should be configured properly.

### Screenshots

![Screenshot 2022-11-02 at 4 17 50 PM](https://user-images.githubusercontent.com/3428964/199594159-f2f5730e-0455-42f5-805e-d7e1e0e1d525.png)

Illustrating how pfe-icon is trying to load the icons from jspm
![Screenshot 2022-11-02 at 4 12 29 PM](https://user-images.githubusercontent.com/3428964/199594204-ed2337e9-0f83-480d-ae37-d604ecb5c35d.png)

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by bennypowers** [comment]
see https://github.com/patternfly/patternfly-elements/pull/2223

**Comment by heyMP** [comment]
@coreyvickery This is still an issue, we have to update the import map for pfe-icon on the demo page and we should be good to go.  Thanks for the ping!

---

We need to add a `pfe-icon/`
The import map has `pfe-icon` but it needs `pfe-icon/` to get the contents.
