### ISSUE TITLE
[bug] <rh-pagination> and dir=rtl

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#618]
### Describe the bug

When using rh-pagination on RTL pages, the next and last page arrows are drawn on the right and the previous and first page arrows are drawn on the left. The direction of these arrows is also reversed.

### Which Component?

rh-pagination

### Steps to reproduce

Place a paginator on an RTL page

### Expected behaviour

next and last buttons are on the left, pointing left. prev and first buttons are on the right, pointing right

### Screenshots

![image](https://user-images.githubusercontent.com/1466420/200188000-24b38a26-e1fd-41e4-a293-01906b2371d8.png)

### Element HTML

```HTML
<div dir="rtl">
  <p>צריך להיראות יותר טוב</p>
  <rh-pagination>
  <span slot="go-to-page">עבור לדף</span>
  <ol>
    <li><a href="/1">1</a></li>
    <li><a href="/2">2</a></li>
  </ol>
</rh-pagination>
```

### Operating System (OS)

Linux

### Browser

Firefox

**Comment by zeroedin** [comment]
@bennypowers should this get fixed before 1.0?
