### ISSUE TITLE
[feat] <rh-audio-player> MVP

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system#637]
### Description

This issue is for building the MVP for `<rh-audio-player>`.

**All features**
https://xd.adobe.com/view/6f46d2c1-deb2-4f6e-a8e3-7b92b06c2cad-3a15/

**Feature requests/ranking from stakeholders**
https://docs.google.com/spreadsheets/d/1quuxkd0LTVf7Qp6bXlwIKyIwiny8T-HUod0Qo9yXDDk/edit#gid=0

### Acceptance Criteria

- [ ] Design done
- [ ] Development done

### Link to design doc

https://xd.adobe.com/view/6f46d2c1-deb2-4f6e-a8e3-7b92b06c2cad-3a15/

### Other resources

**General discussion**
https://docs.google.com/document/d/1xwMN4DueI6Ed0PQbXnQEL81j7bVE47mF8F3aDj_1Sys/edit#heading=h.l730don4kfct

**Comment by nikkimk** [comment]
Should this be rh-audio-player or pfe-audio-player? XD docs say pfe-audio-player.

**Comment by zeroedin** [comment]
> Should this be rh-audio-player or pfe-audio-player? XD docs say pfe-audio-player.

[Pattenfly.org](https://www.patternfly.org/v4/) does not have an audio player, it is my understanding that this is `rhds` only.
