### ISSUE TITLE
[bug] lib folder not exporting with @rhds/elements

### ISSUE THREAD

**Issue by brianferry** [RedHat-UX/red-hat-design-system#654]
### Describe the bug

When trying to import the library into another project we see the export coming in as 

`@rhds/elements/elements/lib/ScreenSizeController.js`

Instead of 

`@rhds/elements/lib/ScreenSizeController.js`

### Which Component?

lib

### Steps to reproduce

1. Start a new project https://open-wc.org/docs/development/generator/
2. npm install `@rhds/elements@1.0.0-beta.27`
3. Try to import ScreenSizeController from `@rhds/elements/lib/ScreenSizeController.ts` 
4. Build

### Expected behaviour

We should be able to bring in the lib folder into our projects

### Operating System (OS)

macOS, Linux

**Comment by bennypowers** [comment]
Closed by #653
