### ISSUE TITLE
[bug] rh-alert footer has margin when empty

### ISSUE THREAD

**Issue by dcaryll** [RedHat-UX/red-hat-design-system#656]
### Describe the bug

When using rh-alert, if no content is in the `footer` of the alert, it still maintains its margin. 

### Which Component?

rh-alert

### Steps to reproduce

1. Go to https://ux.redhat.com/components/alert/demo/
2. Remove content from the alert footer
3. See margin that remains

### Expected behaviour

The margin should go away if the footer is empty

### Screenshots

![Screenshot 2022-12-09 at 12 53 56 PM](https://user-images.githubusercontent.com/1249747/206767185-b23947a9-d44a-4695-84ad-9dcc5f89fbb4.png)

### Operating System (OS)

macOS

### Browser

Chrome, Safari

**Comment by brianferry** [comment]
Created a PR here to fix this https://github.com/RedHat-UX/red-hat-design-system/pull/659

**Comment by bennypowers** [comment]
Closed by #659
