### ISSUE TITLE
[bug]  rh-context-provider change causes visual style issue on rh-secondary-nav

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#657]
### Describe the bug

In commit b7aa79aa1aea83d6d3b9234c20d492d402c17aca a `<div>` element was added to `rh-context-provider`. Doing so has side effects on `rh-secondary-nav` as it expects no wrapper to be inside of `rh-context-provider`.   When something like a `rh-cta` is added and its container is styled as a flexbox and vertically centered it will no longer do so correctly with this surrounding `div`

If this container is needed in other areas could we add a `part` attribute to it to make it styleable?

```js
  render() {
    return html`<div part="container"><slot></slot></div>`;
  }
```

### Which Component?

rh-context-provider

### Steps to reproduce

1. use `rh-context-provider`
2. apply element inside its slot 

### Expected behaviour

rh-context-provider should not adjust layout of contents

### Screenshots

![image](https://user-images.githubusercontent.com/13666/206788263-c262ec71-1626-4356-93ac-1788e4dda3be.png)

### Operating System (OS)

iOS, macOS, Linux, Windows

### Browser

Chrome, Safari, Safari iOS, Microsoft Edge, Firefox

**Comment by zeroedin** [comment]
I looked at this again and approached the fix differently than when I first looked.  No change needed to `rh-context-provider`

**Comment by bennypowers** [comment]
i'd be happy to remove the wrapping div, but i found that without it, rcp didn't actually apply background or colour styles

**Comment by zeroedin** [comment]
> i'd be happy to remove the wrapping div, but i found that without it, rcp didn't actually apply background or colour styles

Understood, and no worries, I have a solution to the div being present atm, but looking into a separate sorta related issue now but will ping you on the PR when it's ready for review.

**Comment by bennypowers** [comment]
ok, let's make sure it works with all the demo pages because that's where i encountered it. we ought to write some unit tests, or maybe a visual regression
