### ISSUE TITLE
[bug] <rh-blockquote> inline margin of slotted content

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#665]
### Describe the bug

The `<p>` inside the blockquote has the wrong margin/padding. It's indented for some reason.

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/1890950/207374613-3c002f2a-cb72-4972-8560-d44f6128f03c.png">

It should be flush-left:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/1890950/207374810-2cfc747b-0be9-42af-9edc-2dbb663ece06.png">

### Which Component?

rh-blockquote

### Steps to reproduce

1. [Visit demo](https://ux.redhat.com/components/blockquote/demo/)

### Expected behaviour

There should be no left/right margin or padding

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by markcaron** [comment]
[Original design specs](https://github.com/RedHat-UX/red-hat-design-system/issues/319)

**Comment by bennypowers** [comment]
Is this still relevant? on https://ux.redhat.com/components/blockquote/demo/ it appears fixed, as well as locally in the branch for #675

**Comment by markcaron** [comment]
Fixed.
