### ISSUE TITLE
CTA: various design-related bugs 

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#673]
The following styling errors may need to be fixed in a different PR:

- The spacing is off for CTAs with icons. There should be an 8px space between the text and the icon.
![Screen Shot 2022-12-14 at 1 49 02 PM](https://user-images.githubusercontent.com/95588923/207686057-b883f546-40b1-44c4-b98b-9b43f2142255.png)

- The hover states for brick CTAs and secondary CTAs are off in dark theme.
![Screen Shot 2022-12-14 at 1 49 43 PM](https://user-images.githubusercontent.com/95588923/207688354-2206a5e4-0830-4d4e-bb30-649eaac9dea6.png)
![Screen Shot 2022-12-14 at 1 49 39 PM](https://user-images.githubusercontent.com/95588923/207688362-09b2b4af-988c-42e1-ba90-0139b2a98dd5.png)
Background color for secondary CTA on dark theme should be #fff. The background color for brick CTA on dark theme should be #3C3F42.

- Padding for the left and right of primary, secondary, and brick CTA should be 32px. Right now, they're 24px.

_Originally posted by @marionnegp in https://github.com/RedHat-UX/red-hat-design-system/pull/661#pullrequestreview-1218078124_

**Comment by bennypowers** [comment]
@marionnegp I spun out a new issue for those. Would you mind dropping an approval here to merge this PR?

**Comment by bennypowers** [comment]
@marionnegp can you provide token names for the values you specified here, please?

**Comment by marionnegp** [comment]
@bennypowers, I can take this issue if you want.
