### ISSUE TITLE
[feat]: <rh-accordion> rtl needs better styling

### ISSUE THREAD

**Issue by brianferry** [RedHat-UX/red-hat-design-system#700]
### Tag Name

rh-accordion

### RHDS Only

- [ ] The component will be **RHDS only**, delete the PFE component once published

### Additional Info

See #594 

@bennypowers comment:

TODO:

- adjust rotate direction
- align texts
- change border alignment

**Comment by brianferry** [comment]
@bennypowers did you start a branch for this? Just checking to make sure I don't duplicate work if I start working on this

**Comment by bennypowers** [comment]
No, go for it

**Comment by bennypowers** [comment]
fixed by #711
