### ISSUE TITLE
[feat] <rh-subnav>

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#703]
### Description

Need a new component to handle sub navigation, like we have designed (and need) in our new [Docs IA](https://xd.adobe.com/view/25541eac-f320-4b95-a93a-dd16aeefa7f9-7007/screen/ffd50c94-de45-4aaa-bede-e8a7d687459d).

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/1890950/212708888-e55e49a0-53f6-40b6-9bf7-d835bbdcbd43.png">

@coreyvickery will post more concrete specs to follow. But, effectively it will look like the above and function similarly to Secondary Navigation on mobile.

### Acceptance Criteria

- [ ] Design done
- [ ] Development done

### Link to design doc

https://xd.adobe.com/view/25541eac-f320-4b95-a93a-dd16aeefa7f9-7007/screen/ffd50c94-de45-4aaa-bede-e8a7d687459d

**Comment by coreyvickery** [comment]
@zeroedin As mentioned, documentation XD link is below.

https://xd.adobe.com/view/9aeac027-7f86-4245-bad0-58022954fcd5-cfb9/

cc @markcaron @marionnegp

**Comment by coreyvickery** [comment]
@zeroedin Here's a conversation I'm having with Marionne about inset options. I'm posting it here too so it doesn't get lost if the XD link changes.

`Marionne Patel: Do we still need inset options? Not sure if you were in the meeting when I talked to Mark about limiting tab inset options to be small or none.`

Maybe the default inset value is 32px (remove `inset - none`) and the only other option is `inset - large (80px)`. On mobile, the only inset value could be `inset - none`. That's three values, but used differently.

So I guess our question is do we emulate `rh-tabs` (two inset values) or go with three inset values (`none (0px)`, `small (32px)`, and `large (80px)`)?

cc @marionnegp

**Comment by zeroedin** [comment]
> @zeroedin Here's a conversation I'm having with Marionne about inset options. I'm posting it here too so it doesn't get lost if the XD link changes.

Should this have gone under the [rh-tabs PR](https://github.com/RedHat-UX/red-hat-design-system/pull/634)?
