### ISSUE TITLE
[bug] rh-footer doesn't support rh-accordion

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#707]
### Describe the bug

The footer demo is currently not rendering the mobile links accordion dropdown correctly.  This is because rh-footer only supports pfe-accordion 1.x.  We should add styles to also support ~pfe-accordion 2.x~ rh-accordion.

### Which Component?

rh-footer

### Steps to reproduce

1. Go to https://ux.redhat.com/components/footer/demo/
2. Shrink the browser window below 990px
3. The primary links should now be in a pfe-accordion dropdown
4. Compare that with the rh-footer on https://redhat.com

### Expected behaviour

We should replace pfe-accordion with rh-accordion

### Screenshots

![Screenshot 2023-01-18 at 9 33 32 AM](https://user-images.githubusercontent.com/3428964/213202809-1465b415-0814-4717-b5e9-451f6a3d7f92.png)

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by bennypowers** [comment]
we released rh-accordion, much better tonuke pfe-accordion, no?

**Comment by heyMP** [comment]
Oh, yes.  Good call!  I'll update this issue.
