### ISSUE TITLE
[docs]: rewrite ux-dot CSS

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#773]
If you'd ask me, I'd say we're overdue to refactor the UX-DOT CSS:
- remove SCSS
- remove BEM-style selectors
- tokens everywhere
- maybe adopt Declarative Shadow DOM on ux-dot
  - [Mozilla's support for the feature is now positive](https://bugzilla.mozilla.org/show_bug.cgi?id=1712140)
  - [WebKit shipped it](https://github.com/WebKit/WebKit/pull/7798)
  - we'd apply the polyfill and use an 11ty transform to stamp custom elements with DSD templates 
  - we'd show other teams it's possible

The advantages we stand to gain are: 
- smaller node_modules
- fewer dependencies
- faster builds
- easier to grok CSS
- more dogfooding
- provide an examplary use of RHDS tech

_Originally posted by @bennypowers in https://github.com/RedHat-UX/red-hat-design-system/issues/638#issuecomment-1467407021_

**Comment by bennypowers** [comment]
cc @dcaryll @markcaron @zeroedin @coreyvickery @marionnegp

**Comment by coreyvickery** [comment]
@bennypowers Sounds cool. I am prepared for things to break a bit temporarily, but if that means sleeker code in the end, so be it.

**Comment by bennypowers** [comment]
ideally we could do this bit by bit, focusing on specific items, so that review wouldn't be too onerous

**Comment by marionnegp** [comment]
@bennypowers, yes please! I'd be up for helping where I can too.

**Comment by zeroedin** [comment]
We should pair this with moving reusable parts to `.webc` as well, further scoping the styles to components for reuse and overall less clutter in the base styles.
