### ISSUE TITLE
[feat] footer: Focus state on footer links should be around links

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#789]
Focus state should be surrounding the links, not the full "block"/row.

![Screenshot 2023-06-16 at 12 40 06 PM](https://github.com/RedHat-UX/red-hat-design-system/assets/3428964/58a49c92-2c5f-4381-8f4a-250d8726688c)

**Comment by heyMP** [comment]
Moving this out to Bellsprout since further discovery is needed.

**Comment by markcaron** [comment]
@heyMP, we need more details.
