### ISSUE TITLE
[bug] <footer> Mobile accordion has text overflow clipping issues

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-system#803]
### Describe the bug

![Screenshot 2023-03-20 at 8 23 06 PM](https://user-images.githubusercontent.com/3428964/226493458-40b58475-77d4-42fc-90b3-f4b16b13cfc1.png)

### Which Component?

rh-footer

### Steps to reproduce

1. Go to https://redhat.com
2. Shrink the browser to mobile mode so that the accordion kicks in.
3. You should be seeing the white boxes around the headers.

### Expected behaviour

We should add the fix to either rh-footer or rh-accordion

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by heyMP** [comment]
This is a super weird issue.  Half of the people see it, half don't.

User 1: visual regression
MacOS: 13.2
Chrome: 111.0.5

User 2: no visual regression
MacOS: 13.2
Chrome: 111.0.5

**Comment by heyMP** [comment]
> Not sure if this is the same issue or not

Yes, that's the same issue.  It seems to be an issue with `rh-accordion-header::part(text)` being set to `overflow:auto`

![Screenshot 2023-03-21 at 10 28 55 AM](https://user-images.githubusercontent.com/3428964/226638272-204fd0be-4af5-4c39-a0dd-76722149d620.png)

**Comment by bennypowers** [comment]
yup, good catch @brianferry and @heyMP, this is a scrollbar issue
