### ISSUE TITLE
[feat] <axe-lightdom-tester>

### ISSUE THREAD

**Issue by nikkimk** [RedHat-UX/red-hat-design-system#813]
### Description

While we are able to use `axe-core` to accessibility test components, we can't account for what content authors are actually putting into light DOM. 

We should create a controller that uses `axe-core` and can be run on when content is in authoring mode or with analytics reporting, to check actual light DOM content for accessibility and log issues.

### Acceptance Criteria

- [ ] Design done
- [ ] Development done

### Other resources

[Axe Javascript Accessibility API](https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#section-2-api-reference for configuration)

**Comment by bennypowers** [comment]
We'd like to use something like @paceaux's selector hound to do static analysis instead.
