### ISSUE TITLE
[docs]: playground demos should show a code snippet while loading

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#848]
## Problem
1. Playground demos are hidden while loading
2. The dependencies are quite heavy so this takes dozens of seconds or even minutes on slower connections
3. This creates a lot of layout shift

we should:
1. show the demo HTML as a highlighted snippet
2. lazy-load the dependencies in a `requestIdleCallback`
3. click a button by the snippet to load the demo playground

Similar to what I did for [Apollo Elements](https://apolloelements.dev/)

The snippet and demo should have a standard min/max height and scroll beyond that, to avoid layout shift.

**Comment by zeroedin** [comment]
Possible duplicate: https://github.com/RedHat-UX/red-hat-design-system/issues/581

**Comment by bennypowers** [comment]
Closing as dupe of #581
