### ISSUE TITLE
[bug] Links in CTAs are not clickable

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#850]
### Describe the bug

The cta shortcode for creating a `rh-cta` seems to not be working correctly.  The URL does not function and take you to a new tab. 

### Which Component?

rh-accordion, rh-alert, rh-cta

### Steps to reproduce

1. Go to the [Accordion docs overview tab page](https://ux.redhat.com/elements/accordion/)
2. Click `View the <rh-accordion> demo in a new tab`
3. No beuno

### Expected behaviour

The cta should take you to the demo in a new browser tab

### Operating System (OS)

macOS

**Comment by bennypowers** [comment]
There are two issues here:

1. demo pages not rendering
2. somehow this doesn't work
```html
<rh-cta><a href="./demo/" target="_blank">
View the <code>&lt;rh-accordion&gt;</code> demo in a new tab
</a></rh-cta>
```
