### ISSUE TITLE
[docs]: duplicated h1 on overview pages

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#855]
The fix will be to release and integrate the [PR on pfetools](https://github.com/patternfly/patternfly-elements/pull/2444), then set `renderTitleInOverview` to false

**Comment by zeroedin** [comment]
`renderTitleInOverview` will be available when  https://github.com/RedHat-UX/red-hat-design-system/pull/854 merges

**Comment by bennypowers** [comment]
#854 should also unset it in config

**Comment by bennypowers** [comment]
Closed in #854
