### ISSUE TITLE
[docs]: tabs update content

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-design-system#867]
following on the work in #859, we should polish, update, and revise the content in all the element docs pages, including tabs.

              Should we be saying not to use tabs on mobile?  I feel like this bit of content should get removed or edited.  

Maybe we can suggest not to use `vertical` tabs on mobile, but the scrolling tabs now are mobile friendlier.. ish :)

_Originally posted by @zeroedin in https://github.com/RedHat-UX/red-hat-design-system/pull/859#discussion_r1149827901_

**Comment by hellogreg** [comment]
Closing this issue, as it now falls under #933. I've copied the comments from this (and #859) into that issue.
