### ISSUE TITLE
[bug] Alias urls regression

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#874]
### Describe the bug

There is an issue with alias URLs as a regression in dev server and docs.

http://localhost:8000/components/navigation-(secondary)/demo/ should not contain parens.

http://localhost:8080/elements/navigation-secondary/demo/ are serving 404s.

11ty is creating to folders `/_site/elements/navigation-(secondary)` where the demos exist and `/_site/elements/navigation-(secondary)` where all the documentation pages exists.

### Which Component?

aliased components with parens

### Steps to reproduce

1. Go to https://ux.redhat.com/elements/navigation-secondary/demo/
2. Then go to https://ux.redhat.com/elements/navigation-(secondary)/demo/

The 2nd URL loads but other assets are then broken as they are looking in the same folder which they do not exist

### Expected behaviour

Only one folder for navigation-secondary should be created

### Screenshots

![Screenshot 2023-03-29 at 2 32 58 PM](https://user-images.githubusercontent.com/13666/228653721-786bab02-9392-44b9-870a-73b9e3401cd2.png)

### Operating System (OS)

macOS

**Comment by zeroedin** [comment]
I believe the issue stems from upstream in `pfe-tools` specifically `Manifest.ts` in `getDemoMetadata()`, the slug should maybe not return with special characters like parenthesis.

```
const [, slug = ''] = permalink.match(/\/components\/(.*)\/demo/) ?? [];
```
should be updated to:
```
let [, slug = ''] = permalink.match(/\/components\/(.*)\/demo/) ?? [];
slug = slug.replace(/[()]/g, '');
```

Slugs should most likely always follow `snake-case` with nothing but `[a-zA-Z0-9]`.

**Comment by zeroedin** [comment]
PR upstream: https://github.com/patternfly/patternfly-elements/pull/2460

**Comment by bennypowers** [comment]
Consulting the deploy logs, `/elements/navigation-secondary/demo/index.html` exists, as do the subresources. As well, the [immutable url for the deploy](https://642940c52b512e000890b73f--red-hat-design-system.netlify.app/elements/navigation-secondary/demo/) contains the working demo. Perhaps this has to do with redirect rules, browser cache, or the github pages deploy?
