### ISSUE TITLE
[chore] Update CSS custom prop name to something more semantic or less vague

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#879]
https://github.com/RedHat-UX/red-hat-design-system/blob/96453bf649f724cb9bb8b787e3bfc23aa831d13c/elements/rh-dialog/rh-dialog.css#L50

**Comment by bennypowers** [comment]
FWIW, this has a `_` so we can consider it "private", but it was good to update anyways
