### ISSUE TITLE
[feat] Update danger values with non-brand red values

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#881]
### Description

Update the danger token values and anywhere brand red is used in RHDS as a danger color to danger hex values defined in PF4/UX dot.

### Suggested solution

Use hex colors from PF4 or ux.redhat.com. Add a comment.

**Comment by bennypowers** [comment]
Addressed in #882, as a stopgap. We can come back and fix this in patch releases later.

**Comment by bennypowers** [comment]
Reopening to consider these uses of brand-associated red crayon values

```
elements/rh-avatar/rh-avatar.css
86:  var(--rh-color-red-500, #ee0000)

elements/rh-badge/rh-badge.css
34:  --_background-color: var(--rh-color-red-600, #be0000);

elements/rh-button/rh-button.css
35:  --_secondary-danger-color: var(--rh-color-red-600, #be0000);

elements/rh-tag/rh-tag.css
81:  --_before-border-color: var(--rh-color-red-600, #be0000);
82:  --_icon-color: var(--rh-color-red-600, #be0000);
```

**Comment by bennypowers** [comment]
Closing since @marionnegp approved these uses
