### ISSUE TITLE
[feat] Design token copy button with tooltip for ux.redhat.com

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system#883]
### Description

# Brief

We need to give users the ability to copy a design token name on ux.redhat.com.

# Needs

- The name text should have a light gray background with padding and rounded corners
- There should be a copy to clipboard button
- The copy button should display a tooltip on hover with `Copy to clipboard` text
- The tooltip should be oriented on the top of the button
- The copy button should display `Copied` confirmation text when selected for a duration of `3 seconds` then return to `Copy to clipboard` text ([example](https://polaris.shopify.com/tokens/colors))
- The design token name should then be copied to the clipboard
- `rh-tooltip` can be used

# Styles

### Text

- Font: RH Text Regular
- Size: 14px / 21 (1.5 line height)
- Letter spacing: 0.2px
- Color: #151515

### Icon

- Default color: #6A6E73
- Hover color: #151515

### Background

- Border radius: 3px
- Color: #F5F5F5

### Acceptance Criteria

- [ ] Design done
- [ ] Development done

### Link to design doc

https://xd.adobe.com/view/7dae9ef8-4dd4-4a8a-a05a-6192132c5e9f-28fd/

### Other resources

![design-token-copy-button-icon-default](https://user-images.githubusercontent.com/45767595/200391839-1157a3be-dc2d-46e6-8601-b4ba83a3a385.svg)
![design-token-copy-button-icon-hover](https://user-images.githubusercontent.com/45767595/200391843-6038c213-5cb9-457e-8cfd-c870f1efd25f.svg)

**Comment by bennypowers** [comment]
See also #717
