### ISSUE TITLE
[bug] Broken images and missing headings on All Elements and All Patterns pages

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#890]
### Describe the bug

- [ ] Fix broken images on [All Elements page](https://ux.redhat.com/elements/) and [All Patterns page](https://ux.redhat.com/patterns/)
- [ ] Add headings below each image on both pages

### Which Component?

n/a

### Steps to reproduce

See [All Elements page](https://ux.redhat.com/elements/) and [All Patterns page](https://ux.redhat.com/patterns/)

### Expected behaviour

Should be showing images and headings

### Operating System (OS)

macOS

**Comment by bennypowers** [comment]
Is this a duplicate of #872 ?

**Comment by marionnegp** [comment]
@bennypowers, images for footer, secondary nav, and primary nav are missing, so I don't think it's related.
