### ISSUE TITLE
[docs] Accordion docs need cleanup

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#897]
Accordion docs are missing Guidelines tab. Seems like some of the content under Overview might need to be moved to Guidelines.

Please review sections and ensure docs are complete.

Previous IA docs update issue:
#822 

Tag @coreyvickery for final design review.

**Comment by coreyvickery** [comment]
https://xd.adobe.com/view/ba7a7209-4d1f-449d-a3f9-042a0c7ebda8-ef29/

**Comment by coreyvickery** [comment]
XD: https://xd.adobe.com/view/ba7a7209-4d1f-449d-a3f9-042a0c7ebda8-ef29/
Content doc: https://docs.google.com/document/d/170X1VcI9CfMMAcFneLAcbDCtdSiIoNXpIlrou4jNn-o/edit#
Images: https://www.dropbox.com/sh/o5hgk2w5064dejc/AAAoXh8bUoHtgZdGykwDRYIxa?dl=0

**Comment by nikkimk** [comment]
This will be dependent on https://github.com/RedHat-UX/red-hat-design-system/pull/965
