### ISSUE TITLE
[docs] Alert docs need review/cleanup

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#903]
Please review sections and ensure docs are complete.

Current tabs: Overview, Style, Guidelines, Code, Accessibility. Most elements’ Guidelines tabs have a “Usage” section, but this one currently does not.

Previous IA Docs update issue: #820

Tag @coreyvickery for final design review.

**Comment by marionnegp** [comment]
Reopening this issue to get @coreyvickery's review on the [Alert docs](https://ux.redhat.com/elements/alert/) that were just merged

**Comment by coreyvickery** [comment]
@marionnegp Some questions and notes.

### All pages
- Is there always so much space in between the cross-links and footer or is there extra code we need to remove?

### Style page
- Anatomy numbers are indented and the line height is very loose, we might need to make a new style
- The line height of the text in the `Interaction States` section is very loose

### Guidelines page
- The `rh-alert` element in the `Severity` section looks different than in the demo

**Comment by marionnegp** [comment]
> * Is there always so much space in between the cross-links and footer or is there extra code we need to remove?
There's a margin below the section and padding right above the footer. Can you open a new issue to have this fixed globally?

> * The `rh-alert` element in the `Severity` section looks different than in the demo
I can see that the icons are aligned a little differently. I think it's something that should be fixed in the `rh-alert` element though. I can open this issue.

The other two points should be resolved by #943.

**Comment by hellogreg** [comment]
Reopening because images on the page are currently 0.5x -- and for potential content edits.
