### ISSUE TITLE
[docs] Call to Action (CTA) docs need review/cleanup

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#905]
Please review sections and ensure docs are complete.

Current tabs: Overview, Style, Behavior, Code, Accessibility. No Guidelines tab.

Previous IA Docs update issue: #610

Tag @coreyvickery for final design review.

**Comment by coreyvickery** [comment]
XD: https://xd.adobe.com/view/fe8152fb-ec3c-47f6-bcba-55a2a3ce61c5-abd2/
Content doc: https://docs.google.com/document/d/15pIDwmcCXYweZAcBx9ImnZ0DAlf-KAqHu98QRrtAJe0/edit#
Images: https://www.dropbox.com/sh/pl9vguisy8dif1i/AAAHDY1ZacH5ABlAU0pmyNHca?dl=0
