### ISSUE TITLE
[bug] Auto rebuild not working in elements/docs folder

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#907]
### Describe the bug

To see any change to a doc in elements/docs, the local server needs to be restarted.

### Which Component?

ux.redhat.com (not a component)

### Steps to reproduce

1. Run `npm start` to start a local instance of ux.redhat.com.
2. Try making a change in any of the existing pages under the elements/docs folder or try adding a new page to a element's docs. 
3. See if the preview automatically shows the change.
4. If it doesn't, restart the server. You should be able to see the change after that.

### Expected behaviour

Once you have a local preview open, it should be watching for and showing changes as you save them.

### Operating System (OS)

macOS

**Comment by bennypowers** [comment]
https://github.com/11ty/eleventy/issues/2909
