### ISSUE TITLE
[docs] Avatar docs need review/cleanup

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#909]
Code tab seems like it needs a little design love. Sections are tightly packed with no margin. Please compare with other doc pages and make sure it's not just an update in the CSS to fix them all.

Also review other sections for consistency.

Current tabs: Overview, Style, Guidelines, Code

Previous IA docs update issue #823.

Tag @coreyvickery for final design review.

**Comment by diwanshi** [comment]
@markcaron starting to work on this now

**Comment by bennypowers** [comment]
Take a look at the docs cleanup checklist

https://github.com/RedHat-UX/red-hat-design-system/wiki/Docs-Cleanup-Q2-2023-Checklist

**Comment by coreyvickery** [comment]
XD: https://xd.adobe.com/view/6f3078cf-c5d5-4c7b-8e30-509acd11525c-3a63/
Content doc: https://docs.google.com/document/d/1eEnyWKABadmP4RetzXIB7HXX542C9n-Dj_jjQ4uE_XI/edit#
Images: https://www.dropbox.com/sh/77vfksj34wwqcn1/AADuZQdzhWyxJkcTVt27C9h2a?dl=0
