### ISSUE TITLE
[bug] Repo status table not showing

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#911]
### Describe the bug

The repo status tables aren't showing up on the Overview tabs of element and pattern pages.

![Screenshot 2023-04-12 at 9 40 03 AM](https://user-images.githubusercontent.com/95588923/231476801-806ee13d-129e-4aea-b2b6-4ae439712c3a.png)

### Which Component?

n/a

### Steps to reproduce

Compare the [live accordion page](https://ux.redhat.com/elements/accordion/) to the [accordion page mockup](https://xd.adobe.com/view/d48af181-73da-4236-ba40-d16c2efeb2a5-81d9/) as an example.

### Expected behaviour

Repo status table should appear towards the bottom of the Overview tab. I think `{% componentStatus -%}{% endcomponentStatus %}` used to show it.

### Operating System (OS)

macOS

**Comment by bennypowers** [comment]
could be the `componentStatus` table is not receiving the tag name from the "ambient" data in the cascade, owing to the use of `renderFile` to render the `/elements/*/docs/*.md` files. If that's the case we might be able to fix by passing in the component slug
```njk
{% componentStatus tagName='rh-accordion' %}
```

**Comment by marionnegp** [comment]
@bennypowers, I tried it out with rh-alert this morning, but it didn't seem to work.

![Screenshot 2023-04-19 at 10 35 36 AM](https://user-images.githubusercontent.com/95588923/233109819-65eea003-d6c7-4db5-9e74-502fc3e5c36a.png)
