### ISSUE TITLE
[docs] "Related elements or patterns" & "Feedback" section

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#912]
We currently have this at the bottom of every element/pattern page tab:
![Screenshot 2023-04-12 at 9 48 28 AM](https://user-images.githubusercontent.com/95588923/231479028-7078b5fa-85cd-4169-a800-62dbff6321a3.png)
This is being pulled in by a `feedback.html` file under the `docs` > `_includes` folder.

We'd like to have this info instead:
![Screenshot 2023-04-12 at 9 48 13 AM](https://user-images.githubusercontent.com/95588923/231479095-e0cd31b9-663a-4f28-a43a-5f44d0b65d35.png)

The related components will be different for each element/pattern, but the info under "Feedback" will remain the same.

**Comment by nikkimk** [comment]
@marionnegp Is there ever a case where related elements and pattens will be empty? Is so what would that look like?

**Comment by marionnegp** [comment]
@nikkimk, I don't _think_ that would happen on an element or pattern page, but I'd imagine the Feedback section would move into its spot in the row. 

That feedback.html file also appears at the bottom of our Foundations pages (like [Color](https://ux.redhat.com/foundations/color/)). We wouldn't have related elements or patterns there. @coreyvickery, would you want to keep the Foundations section at the bottom of Foundations pages? I'd be ok with omitting or replacing it.

**Comment by coreyvickery** [comment]
@marionnegp I would like to swap the sections at the bottom of Foundations pages so `Feedback` is on the right, the same as what we're doing for the new Element/Pattern pages.

**Comment by bennypowers** [comment]
There's already a `feedback` template
We'd convert that to a shortcode (or webc component) and slot in the related elements (or set them in a webc prop or shortcode parameter)
