### ISSUE TITLE
[docs] "Card" and "Call to Action" out of alphabetical order in docs site navigation

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#914]
"Card" is currently listed before "Call to Action" in the site navigation. (Guessing this may be because the latter was initially titled "CTA")

![image](https://user-images.githubusercontent.com/642695/231486807-25d9ca0d-21a6-4d99-a4d0-8682be903abd.png)

**Comment by markcaron** [comment]
Done with PFE's PR: https://github.com/patternfly/patternfly-elements/pull/2479
