### ISSUE TITLE
[docs] “Call to Action” at docs site should be sentence case and not title case

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#915]
We should change “Call to Action” to “Call to action” (with a lower case "a") in the site navigation, its page heading, and any other locations where it’s currently title case. All other elements are sentence case, per [Red Hat's typography guidelines](https://www.redhat.com/en/about/brand/standards/typography).

![image](https://user-images.githubusercontent.com/642695/231488435-cfb0aaa3-5821-490a-9623-cd5ed348a44e.png)

![image](https://user-images.githubusercontent.com/642695/231488520-12fd92ba-edd6-4d0a-9d5d-94bdae0ae627.png)

**Comment by diwanshi** [comment]
this will be taken care in https://github.com/RedHat-UX/red-hat-design-system/pull/1045

**Comment by diwanshi** [comment]
@hellogreg let me know if we can close this one as i've included this change in cta docs PR
