### ISSUE TITLE
[docs] Spacing and typography style fixes

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#919]
- [x] `h3` font size should be 20px
- [x] Spacing between `h2` and `h3` should be 32px

- [x] `h3` spacing should be 16px between body copy and 32px between alerts. Spacing should be 16px between `h3` and images/example containers.
![Screenshot 2023-04-13 at 10 59 34 AM](https://user-images.githubusercontent.com/95588923/231801027-ab8c198a-d26b-402e-8e65-34abffc841da.png)

- [x] Example containers should have border radius of 8px.
- [x] Example containers should have 32px padding for small screens. Examples with darkest palette has 64px padding at any screen size.

- [x] Font size of body copy on homepage is 16px.
![Screenshot 2023-04-13 at 12 34 21 PM](https://user-images.githubusercontent.com/95588923/231826240-1f7414ab-569f-409c-9241-85003a7d3ca5.png)

- [x] Page headers should have 80px padding-top for large screen sizes
![Screenshot 2023-04-13 at 12 42 32 PM](https://user-images.githubusercontent.com/95588923/231828045-204c2a9d-c649-4cf1-8836-65b3d7edc479.png)

**Comment by marionnegp** [comment]
Heading 3 should stay at 24px.

**Comment by bennypowers** [comment]
as part of the docs migration, i added the `example` shortcode. most instances of the shortcode rely on the `style` attribute to add custom styles to a given instance.

I think that ideally, we should seek to get rid of all of those custom styles and just use a shortcode/component that looks correct in any situation.

**Comment by marionnegp** [comment]
This `example` shortcode has been working pretty well: 

```
{% example palette="light",
           width=498,
           alt="Spinner with numbers pointing to parts of the element",
           src="../spinner-anatomy.svg" %}
```

We also need a way to pull in images without adding the border and padding, but this markdown is kind of cumbersome to add: `![Alt tag](../spinner-spacing.svg){style="--inline-img-max-width:1000px;"}`

**Comment by bennypowers** [comment]
we shouldn't need the --inline-img-max-width prop, IMO, plain old images should be fine.
There are automated tools which can apply the `width` and `height` atts for us in post, e.g. https://github.com/divriots/jampack
