### ISSUE TITLE
[docs] Tooltip docs need review/cleanup

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#922]
Please review sections and ensure docs are complete.

Current tabs: Overview, Style, Guidelines, Code. (“Overview” heading in the Code tab has no additional description beyond the name of the element.)

Previous IA docs update issue: #830

Tag @coreyvickery for final design review.

**Comment by coreyvickery** [comment]
https://xd.adobe.com/view/f3089ecd-1286-4622-8a8f-548e9462d730-a65b/

**Comment by coreyvickery** [comment]
https://xd.adobe.com/view/df265b71-7bc3-47b6-bd8a-450f1d44212a-8a75/

**Comment by coreyvickery** [comment]
XD: https://xd.adobe.com/view/df265b71-7bc3-47b6-bd8a-450f1d44212a-8a75/
Content doc: https://docs.google.com/document/d/1HUa31FFVjv0Sl1qSt0qABqLyBsJ5hcL8ByxlT5Bg2Ko/edit#
Images: https://www.dropbox.com/sh/mlxkkff5rnifyoz/AABr--LcgoaGzm6aNXtcelpTa?dl=0
