### ISSUE TITLE
[docs] Badge docs need review/cleanup

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#923]
Please review sections and ensure docs are complete.

Current tabs: Overview, Code. No content in the Overview tab, currently. No Guidelines tab.

Previous IA Docs update issue: #512

Tag @coreyvickery for final design review.

**Comment by coreyvickery** [comment]
https://xd.adobe.com/view/f3089ecd-1286-4622-8a8f-548e9462d730-a65b/
