### ISSUE TITLE
[docs] Button docs need review/cleanup

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#925]
Please review sections and ensure docs are complete.

Current tabs: Overview, Style, Guidelines, Code. “Overview” heading in the Code tab has no additional information beyond a demo button.

Previous IA Docs update issue: #825

Tag @coreyvickery for final design review.

**Comment by coreyvickery** [comment]
XD: https://xd.adobe.com/view/7728dcb1-2285-45ee-92ee-41998615aa57-227b/
Content doc: https://docs.google.com/document/d/1t_bj0VzaMrSKcPkZGeN-aKUM9NdPjpiG1jjdzZjwWIM/edit#
Images: https://www.dropbox.com/sh/o4d1nkuq2uc3kk0/AADr5Jwzg1bulSASxKgKXSqSa?dl=0
