### ISSUE TITLE
[docs] Context provider docs need creation/review

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#926]
Please review sections and ensure docs are complete.

This element does not currently have a page at ux.redhat.com.

Previous IA Docs update issue: #492

Tag @coreyvickery for final design review.

**Comment by markcaron** [comment]
Going to remain in the wiki until we're ready to document it officially. Keeping this internal for now.

**Comment by coreyvickery** [comment]
@hellogreg Can we close this because no page for ux dot is needed?

**Comment by bennypowers** [comment]
the reason we don't want to document this is because we want to get rid of this element once css style queries are available cross-browser

**Comment by hellogreg** [comment]
Sounds good. Closing.
