### ISSUE TITLE
[docs] Footer docs need review/cleanup

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#928]
Please review sections and ensure docs are complete.

Current tabs: Overview, Styles, Guidelines, Code, Accessibility. 

- Has “Styles” tab instead of “Style” tab (unlike other elements, so probably a typo). 
- The Overview tab has a “Usage” section, though that section is typically in the Guidelines tab for other elements.

Previous IA Docs update issue: #606

Tag @coreyvickery for final design review.

**Comment by coreyvickery** [comment]
XD: https://xd.adobe.com/view/7dceb708-6c56-49f0-a6bc-a01d388ba872-289d/
Content doc: https://docs.google.com/document/d/1c-AA_VCzHX9tvstZOBgxLWPkahmtl9yuyCbqRCG_OWQ/edit#
Images: https://www.dropbox.com/sh/vl9g8mubbc8fho2/AACtWNeuBfnQo5bNV-h2Llc9a?dl=0
