### ISSUE TITLE
[docs] Navigation (secondary) docs need review/cleanup

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#929]
Please review sections and ensure docs are complete.

Current tabs: Overview, Style, Guidelines, Behavior, Code, Accessibility. “Overview” heading in the Code tab has no additional description beyond the name of the element.

Previous IA Docs update issue: #827

Tag @coreyvickery for final design review.

**Comment by zeroedin** [comment]
Code tab clean up was done here: https://github.com/RedHat-UX/red-hat-design-system/pull/964

Picking up this issue as a separate PR to go through the checklist.

**Comment by coreyvickery** [comment]
XD: https://xd.adobe.com/view/75edef5f-3cfa-4cc3-b12e-a1e3d5d37b5b-20be/
Content doc: https://docs.google.com/document/d/1Xd1sQl1fP1ivDQLPgV_D1Eadm456KmkJiW6ArcLie7o/edit#
Images: https://www.dropbox.com/sh/7lowxxd9e4aojr7/AADhM6fxgkVQQ1MSQUxjEbkba?dl=0
