### ISSUE TITLE
[docs] Pagination docs need review/cleanup

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#930]
Please review sections and ensure docs are complete.

Current tabs: Overview, Code. No content in the Overview tab, currently. “Overview” heading in the Code tab has no additional description beyond the name of the element.  No Guidelines tab.

Tag @coreyvickery for final design review.

**Comment by coreyvickery** [comment]
XD: https://xd.adobe.com/view/ad3bcf77-23b2-45e4-997d-f711a87173b1-f868/
Content doc: https://docs.google.com/document/d/1OssxunIUkzZS8NCGOFSpqSZ55TdokhzQgottKiHUdcQ/edit#
Images: https://www.dropbox.com/sh/abnzl3z2jbyzmzi/AABfpMYP3RYedjR1wrEKymAJa?dl=0
