### ISSUE TITLE
[docs] Subnav docs need review/cleanup

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#932]
Please review sections and ensure docs are complete.

Current tabs: Overview, Code. No content in the Overview tab, currently. Code section is pretty lean, too. No Guidelines tab.

Previous IA Docs update issue: none

Tag @coreyvickery for final design review.

**Comment by bennypowers** [comment]
I'd like to ship these docs even if they're incomplete, and we can always update the design guidelines later on. The reason being that we've already shipped the element, and it may be in use in the wild.

**Comment by coreyvickery** [comment]
XD: https://xd.adobe.com/view/258ee636-1778-4e80-9ee3-17a5568e3ef1-70dd/
Content doc: https://docs.google.com/document/d/1jqwnKB_4Z53JsWbvFOf2XrPROxnn6cjrWvUUUT4uDKc/edit
Images: https://www.dropbox.com/sh/3fvumvkervfar0s/AAAAUhK-5jIylqkBZv584T5Oa?dl=0
