### ISSUE TITLE
[docs] Tabs docs need review/cleanup

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#933]
Please review sections and ensure docs are complete.

Current tabs: Overview, Style, Guidelines, Code. Most elements’ Guidelines tabs have a “Usage” section, but this one does not.

Previous IA Docs update issue: #867 (which itself derived from #859 and #829)

From #859:

> Should we be saying not to use tabs on mobile?  I feel like this bit of content should get removed or edited.  

...and then #867:

> Maybe we can suggest not to use vertical tabs on mobile, but the scrolling tabs now are mobile friendlier.. ish :)

Tag @coreyvickery for final design review.

**Comment by zeroedin** [comment]
The other solution is to have vertical tabs display as horizontal at small screen widths.   This would take a change to the component CSS and then the language in the docs could be removed as tabs would auto adjust.

**Comment by coreyvickery** [comment]
@zeroedin Sorry, what are you responding to?

**Comment by bennypowers** [comment]
there's already a `vertical` attr on tabs, so we have the option to make this a pattern-level thing (requiring js) instead of a change to the component.

```js
window.matchMedia('(max-width: 400px)').addEventListener(e => 
  document.querySelectorAll('rh-tabs').forEach(tabs => tabs.vertical = e.matches))
```

**Comment by brianferry** [comment]
> Should we be saying not to use tabs on mobile?  I feel like this bit of content should get removed or edited. 

We're actually running into this currently in product trials when we were looking at switching `pfe-content-set` to `rh-tabs`.  On mobile the horizontal tabs has too much spacing / the content is cut off so we were trying to figure out whether or not we should change that text from 

> Tabs can’t be used on screens that are less than 576px wide because the limited space will cause too many section text labels to get cut off. In this environment, tabs will convert to an accordion.

to something like 

> Tabs _shouldn't_ be used on screens that are less than 576px wide because the limited space will cause too many section text labels to get cut off. In this environment, _you should convert_ tabs to an accordion. 

In either case the actual switching of tabs to an accordion and vice versa will need to be its own pattern.

**Comment by coreyvickery** [comment]
XD: https://xd.adobe.com/view/d42498d5-d4fa-4c23-a8b5-99ccba266bfe-8177/
Content doc: https://docs.google.com/document/d/1rCeNm93x0KVFO5oocMAOKA9lWilfgMeYAXbePUmHGSk/edit#
Images: https://www.dropbox.com/sh/gywoodntdxz1c21/AABNiZ8YiZMaA_U_Dp8xeL35a?dl=0

**Comment by zeroedin** [comment]
Will start working on this on Monday
