### ISSUE TITLE
[docs] Tag docs need review/cleanup

### ISSUE THREAD

**Issue by hellogreg** [RedHat-UX/red-hat-design-system#934]
Please review sections and ensure docs are complete.

Current tabs: Overview, Code. No content in the Overview tab, currently. “Overview” heading in the Code tab refers to it as “tooltip” and has no additional description. No Guidelines tab.

Previous IA Docs update issue: none

Tag @coreyvickery for final design review.

**Comment by coreyvickery** [comment]
XD: https://xd.adobe.com/view/11e76e09-10f4-44af-b74b-1f3e562970e5-44b4/
Content doc: https://docs.google.com/document/d/130NPvOgY00F2RkYwzeHNTgx-t7NSyUS44gbNR6QngIM/edit#
Images: https://www.dropbox.com/sh/5diilvza2kwfcbu/AAB8SyeGmgA__OJ7dE8slr55a?dl=0

**Comment by brianferry** [comment]
May 19, 2023 Update - Tag has the updated docs, images, content.  Code review currently happening

**Comment by brianferry** [comment]
PR has been approved & merged.

**Comment by coreyvickery** [comment]
@brianferry One super fast edit.

### Style page
- [ ] Change `Light Theme` to `Light theme` and `Dark Theme` to `Dark theme`
