### ISSUE TITLE
[bug] <rh-elements-playground>

### ISSUE THREAD

**Issue by nikkimk** [RedHat-UX/red-hat-design-system#938]
### Describe the bug

When viewing a component Overview on ux.redhat.com, the playground doesn't load and the following error appears in the console: `ps://ux.redhat.com/assets/playgrounds/rh-elements-playground.js net::ERR_ABORTED 404`

### Which Component?

rh-elements-playground

### Steps to reproduce

1. Go to https://ux.redhat.com/elements/accordion/
2. View the playground.
3. View the JavaScript console for the error.

### Expected behaviour

Playground should load without an error.

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by zeroedin** [comment]
Looks like it works for me today.  Was this resolved when @bennypowers cleared the deploy cache as well as noted in #939?

**Comment by bennypowers** [comment]
i'm not certain that's what did it, but it's a fair assumption, as all the demos are keyed of the manifest, and the primary symptom of bad github cache is missing manifest

**Comment by bennypowers** [comment]
probably closed by #943
