### ISSUE TITLE
docs code tab

### ISSUE THREAD

**Issue by nikkimk** [RedHat-UX/red-hat-design-system#939]
### Describe the bug

In ux.redhat.com, the content from the code tab has disappeared.

### Which Component?

rh-*

### Steps to reproduce

1. Go to ux.redhat.com.
2. Go to any component with a `code` tab.
3. The. page is blank.

### Expected behaviour

The API documentation is not there.

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by bennypowers** [comment]
I cleared the netlify cache and re-ran the build.

**Comment by bennypowers** [comment]
The netlify production deploy is fine: https://main--red-hat-design-system.netlify.app/elements/accordion/code/
This is the gh-pages deploy: https://ux.redhat.com/elements/accordion/code/
Clearing the github caches should help. we should stop using gh-pages.

**Comment by dcaryll** [comment]
@bennypowers what would be the process for disabling the use of GitHub pages? I have no reason to urge that we continue using them. They were set up initially by Wes who helped to launch the v1 of the site.

**Comment by bennypowers** [comment]
We'd have to [add a CNAME for the subdomain](https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/#configure-a-subdomain) to the DNS, or [set up "netlify dns" for the subdomain](https://docs.netlify.com/domains-https/netlify-dns/delegate-a-subdomain-to-netlify-dns/)

more: https://docs.netlify.com/domains-https/custom-domains/

**Comment by dcaryll** [comment]
Thanks! @markcaron can you please work with JVP and team to figure out how to make that switch? IT Marketing would be involved.

**Comment by bennypowers** [comment]
merging #910 (after clearing the github cache) fixed it for now, but the next production build is likely to break it again

https://ux.redhat.com/elements/alert/code/

**Comment by bennypowers** [comment]
probably closed by #943
