### ISSUE TITLE
[bug] <rh-tabs>: vertical styles at mobile screen size.

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#940]
### Describe the bug

`<rh-tabs vertical>` Vertical tabs do not have great mobile experience.  In prior documentation we suggested to not use vertical tabs on a mobile experience.  This came up again in #933 and #867.  

However now that tabs has a mobile experience baked in with horizontal scrolling we should maybe auto convert `vertical` tabs to a horizontal tabs style when under a mobile sized breakpoint thus gaining the scroll feature.

We will need to determine at what breakpoint `vertical` tabs display back as vertical.  My assumption is this is most likely at`(min-width: 768px)` would be acceptable.

### Which Component?

rh-tabs

### Steps to reproduce

View the demo on a mobile screen at: https://ux.redhat.com/elements/tabs/demo/

### Expected behaviour

Vertical tabs should look like horizontal tabs and scroll on small screens

### Operating System (OS)

iOS

### Browser

Chrome

**Comment by bennypowers** [comment]
there's already a `vertical` attr on tabs, so we have the option to make this a pattern-level thing (requiring js) instead of a change to the component.

```js
window.matchMedia('(max-width: 400px)').addEventListener(e => 
  document.querySelectorAll('rh-tabs').forEach(tabs => tabs.vertical = e.matches))
```

**Comment by coreyvickery** [comment]
@zeroedin `(min-width: 768px)` is acceptable and I will edit my XD to reflect this as well.

**Comment by zeroedin** [comment]
Updated XD spec: https://xd.adobe.com/view/e0eb07d2-71ac-498f-9d74-b872dd7c204b-b5b8/
