### ISSUE TITLE
[docs]: footer code tab content organization

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#948]
> :point_right:  **TL;DR**: When an element page has to document multiple elements (`rh-tabs` + `rh-tab` + `rh-tab-panel`), should we separate each component's APIs into per-element sections, or interleave each *kind* of API ("slots for all elements, css props for all elements")

This is a design question about content organization for complex code tab pages.

Components with multiple subcomponents may have many repeated sections on the code tab for each subcomponent.  Using `pf-tabs` as an example here as it is directly relational to `rh-tabs` so its content on this page will be similar so we can look at [its documentation](https://patternflyelements.org/components/tabs/) as an example analogous of current state.

`pf-tabs` is made up of 3 components `pf-tabs` wrapper `pf-tab` and `pf-tab-panel`.  For each of these components you can have each of the following shortcodes:

```
{% renderSlots %}{% endrenderSlots %}

{% renderAttributes %}{% endrenderAttributes %}

{% renderMethods %}{% endrenderMethods %}

{% renderEvents %}{% endrenderEvents %}

{% renderCssCustomProperties %}{% endrenderCssCustomProperties %}

{% renderCssParts %}{% endrenderCssParts %}
```

For `pf-tabs` we just repeat each section with a seperate header tag, `renderCssParts` is used in the example below to show all 3 components outputting their content:

```
{% renderCssParts %}{% endrenderCssParts %}
{% renderCssParts for="pf-tab", level=3, header="Parts on `pf-tab`" %}{% endrenderCssParts %}
{% renderCssParts for="pf-tab-panel", level=3, header="Parts on `pf-tab-panel`" %}{% endrenderCssParts %}
```

For each of those shortcodes we are then generating a different `header`.  So we end up with 3 different sections which renders as the following screenshot:

<img src="https://user-images.githubusercontent.com/13666/233384190-107861ce-bdc2-4677-846a-d31900c13768.png" width="320" alt="Screenshot 2023-04-20 at 9 30 44 AM" />

When it comes to a component that may only have 1 of these 3 sections such as on `pf-tabs` where only 1 of the 3 components has an event section.  Should we still display the other 2 and have them return with None with headers saying for which subcomponent.

```
{% renderEvents for="pf-tab", level=2, header="Events" %}{% endrenderEvents %}
```

Right now I believe the example above to display an issue with the `pf-tabs` example whereas the header should state this comes from the `pf-tab` component, and not the default `pf-tabs`.

I was looking at other component libraries for ideas and there seem to be a couple different approaches.

Some list each subcomponent as their own docs pages, which I don't think we want to do as it doesn't fit into our IA in how we are collating both design and code documentation.

The other idea is what Fast Components are doing as seen in their [tabs documentation](https://www.fast.design/docs/components/tabs) which is separating each sub component into a block of all the docs related to that sub component.  I think I gravitate toward this idea, and would like feedback if this is maybe worth looking into.

How this could translate for us: (pseudo not refined code)

```
<h2>`rh-tabs`:</h2>
{% renderSlots %}{% endrenderSlots %}

{% renderAttributes%}{% endrenderAttributes %}

{% renderMethods %}{% endrenderMethods %}

{% renderEvents %}{% endrenderEvents %}

{% renderCssCustomProperties for="rh-tabs %}{% endrenderCssCustomProperties %}

{% renderCssParts for="rh-tabs" %}{% endrenderCssParts %}

<h2>`rh-tab`:</h2>
{% renderSlots  for="rh-tab" %}{% endrenderSlots %}

{% renderAttributes for="rh-tab" %}{% endrenderAttributes %}

{% renderMethods for="rh-tab" %}{% endrenderMethods %}

{% renderEvents for="rh-tab %}{% endrenderEvents %}

{% renderCssCustomProperties for="rh-tab %}{% endrenderCssCustomProperties %}

{% renderCssParts for="rh-tab %}{% endrenderCssParts %}

<h2>`rh-tab-panel`:</h2>
{% renderSlots  for="rh-tab-panel" %}{% endrenderSlots %}

{% renderAttributes for="rh-tab-panel %}{% endrenderAttributes %}

{% renderMethods  for="rh-tab-panel %}{% endrenderMethods %}

{% renderEvents  for="rh-tab-panel %}{% endrenderEvents %}

{% renderCssCustomProperties  for="rh-tab-panel %}{% endrenderCssCustomProperties %}

{% renderCssParts  for="rh-tab-panel %}{% endrenderCssParts %}
```

This way each section is represented for each sub component, and a user could be sure that specific subcomponent does not have events or methods etc.

If this presents is self as too long of a page I think there is possibility to also dog food `rh-tabs` as the interface to switch between components content.

**Comment by bennypowers** [comment]
@nikkimk let's use this issue to track the only remaining element that this applies to: footer
