### ISSUE TITLE
[docs] Create autogenerated CSS properties tables 

### ISSUE THREAD

**Issue by marionnegp** [RedHat-UX/red-hat-design-system#950]
Design tokens tables should be autogenerated from the element or pattern's CSS files. Started a PR for this: #949 

Example of tokens table:
<img width="784" alt="Screenshot 2023-04-20 at 12 57 42 PM" src="https://user-images.githubusercontent.com/95588923/233436179-4b77aba2-2400-44bc-a9d0-234085cc0e3e.png">

**Comment by marionnegp** [comment]
@markcaron @coreyvickery, do you want this to be part of the [Docs IA updates #1](https://github.com/RedHat-UX/red-hat-design-system/milestone/4) milestone?

**Comment by coreyvickery** [comment]
@markcaron Probably more of a question for you.

**Comment by coreyvickery** [comment]
@markcaron Making sure you're aware.
