### ISSUE TITLE
[bug] endless loop in dev-server on `npm run start`

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#962]
Running `npm run start` will run a endless loop on what might be caused by the minified package?  More investigation needed.

Video of bug https://youtube.com/shorts/OokdnGavq4A?feature=share

**Comment by brianferry** [comment]
Problem seems to be related to `@11ty/eleventy@2.0.0`, upgrading to `@11ty/eleventy@2.0.1` fixes it for me

**Comment by zeroedin** [comment]
> Problem seems to be related to `@11ty/eleventy@2.0.0`, upgrading to `@11ty/eleventy@2.0.1` fixes it for me

Unfortunately that does not seem to fix it for me.  Doesn't happen on every change.  Sometimes seems to be triggered a couple changes in.
