### ISSUE TITLE
[bug] <rh-accordion> Accessibility: arrow keys inside nested accordions don't work as expected

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-system#971]
### Describe the bug

When navigating an accordion inside another accordion, the arrow keys don't move through the nested accordion. Instead, they jump up to the parent accordion.

Related: https://github.com/patternfly/patternfly-elements/issues/2490

### Which Component?

rh-accordion

### Steps to reproduce

1. Run accordion demo locally
2. Find nested example
3. Expand first accordion item
4. Tab inside to the child accordion
5. Hit the down arrow (assuming it should go to the next item in the child accordion)
6. Focus jumps to the parent accordion header

### Expected behaviour

Arrow keys should navigate the currently focused accordion

### Operating System (OS)

macOS

**Comment by markcaron** [comment]
See same bug in PFE: https://github.com/patternfly/patternfly-elements/issues/2490

**Comment by brianferry** [comment]
PR has been merged to address this
