### ISSUE TITLE
[docs] Repo status table updates/edits

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system#973]
### Describe the bug

Requesting to change the component status table on every element and pattern page.

### Old
<img width="1046" alt="Screen Shot 2023-05-03 at 5 38 46 PM" src="https://user-images.githubusercontent.com/45767595/236080064-8b4f591d-89cd-4919-b3c8-458fac3853ca.png">

### New
<img width="1051" alt="Screen Shot 2023-05-03 at 5 39 08 PM" src="https://user-images.githubusercontent.com/45767595/236080133-9e5adfdf-fce8-443b-90dc-af98c3f3f1ae.png">

- - -

## Edits to be made
- [ ] Change heading text to `Repo status`
- [ ] Add body text: Learn more about our various code repos by visiting [this page](https://ux.redhat.com/about/how-we-build/).
- [ ] Add `Element or pattern` as first/leftmost header in table
- [ ] Change headings to `RHDS`, `WebRH`, `WebDMS`, and `Adobe Target` only
- [ ] Remove `Last updated:` text
- [ ] Can we use a check glyph or icon somehow instead of a text `x`?

### Which Component?

ux.redhat.com

### Steps to reproduce

N/A, just look at the images

### Expected behaviour

Detailed above

### Screenshots

Added above

### Element HTML

```HTML
N/A
```

### Operating System (OS)

iOS, macOS, Linux, Windows

**Comment by eyevana** [comment]
@coreyvickery does WebRH and WebDMS map to any of the existing columns in the previous template?
