### ISSUE TITLE
[docs]: tooltip missing screenshot image

### ISSUE THREAD

**Issue by zeroedin** [RedHat-UX/red-hat-design-system#978]
Tooltip missing screenshot image on [all elements page](https://ux.redhat.com/elements/):

![image](https://user-images.githubusercontent.com/13666/236556775-163a9b5c-ac48-4001-8659-4b8d894b86eb.png)

**Comment by coreyvickery** [comment]
@zeroedin `All elements` page thumbnail images are below.

https://www.dropbox.com/sh/vlpos6ghlv1oabj/AACpCj-9gKQVDXY3o8mvxK5aa?dl=0
