### ISSUE TITLE
[bug] wireit: command not found

### ISSUE THREAD

**Issue by kunyan** [RedHat-UX/red-hat-design-system#981]
### Describe the bug

The  devDependency `wireit` had been added into "postinstall"

https://github.com/RedHat-UX/red-hat-design-system/blob/fde62697383da2bb8922d516785dc0975fa292f9/package.json#L63

The projects that depend on `@rhds/elements` should not need install `wireit`

### Which Component?

no component relavent 

### Steps to reproduce

just did a `npm install @rhds/elements` in other projects

### Expected behaviour

install without any error

### Operating System (OS)

macOS

### Browser

Chrome

**Comment by kunyan** [comment]
Workaround: 

```
npm install @rhds/elements --ignore-scripts
```

**Comment by bennypowers** [comment]
I wasn't able to reproduce this, unfortunately

```
❯ cd /tmp
❯ mkdir f
❯ cd f
❯ npm init -y
Wrote to /tmp/f/package.json:

{
  "name": "f",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
❯ npm i @rhds/elements
added 208 packages, and audited 209 packages in 19s

43 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

❯ which wireit
which: no wireit in (REDACTED)
```

Can you give me a little more information? what's your node version? npm version? operating system?

**Comment by kunyan** [comment]
Hey @bennypowers , I found I can not reproduce it as well, I'm using nvm with latest lts v18.16.0

So I was go back to my previous project, it still has this problem, I was think if it is caused by I added a `overrides` scripts to force upgrade some dependencies, but it looks not.

I took 10mins later found the root cause.

I have a `.npmrc` file which include Red Hat internal npm registry.
I don't know why it cause the postinstall scripts of @rhds/elements running 


```bash
➜  /tmp mkdir f
➜  /tmp cd f
➜  f npm init -y
Wrote to /private/tmp/f/package.json:

{
  "name": "f",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


➜  f npm install @rhds/elements
npm ERR! code 127
npm ERR! path /private/tmp/f/node_modules/@rhds/elements
npm ERR! command failed
npm ERR! command sh -c wireit
npm ERR! sh: wireit: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kyan/.npm/_logs/2023-05-07T15_15_09_024Z-debug-0.log
```


I'm happy it is not impact the public user, but I don't know if any other people use private registry will have same issue

I'll leave message in Slack to you for the reproduce details.

Thanks

**Comment by kunyan** [comment]
I had tested with some other 3rd party public npm registry like 

registry=https://registry.npmmirror.com


all works good. I think it might be our registry issue, but I still confused why it is trigger the postinstall scripts even the scripts name in `@rhds/elements` is `_postinstall`

**Comment by bennypowers** [comment]
I was able to reproduce using the custom npm registry you sent me privately.
Unfortunately it does look like that registry has the latest version, so I'm not sure what the issue would be. Perhaps that registry doesn't have `wireit`? I don't think that's the problem though, since installing from the default registry doesn't install wireit, and that installation proceeds as expected
